apiVersion: v1
kind: Secret
metadata:
    name: zilean-postgres-env
    namespace: media
type: Opaque
stringData:
    #ENC[AES256_GCM,data:f0uaL8ouM7uWsW9jD1ppj9VYWg==,iv:ZIOT7iaeK3oVNm4PnOkGLri15YYLFQPA9XT2FyhwDcQ=,tag:R53+fzA6HU40DtIT/l7y1A==,type:comment]
    POSTGRES_USER: ENC[AES256_GCM,data:tI+KEzvGtRs=,iv:XAPhH6Mz09ETYghJhRzL1t0QAu/c2hV91wSGkgZpZlk=,tag:1fUW6m7iY12KqiVO5hYXzg==,type:str]
    #ENC[AES256_GCM,data:0wzExHw/00nW9e8gmvDtBuJEWe08DA==,iv:WdgYbR5PXPu9qAVdX/msZagDjzO8I0yInYGd1lFaH9I=,tag:upZsqMCNaYipkAGhV93lEQ==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:6nqYssv/zy8=,iv:XT2WkLiySgPRYfFOljfy5amdKHECVQ9xFvo6+6yygpk=,tag:+qg5nwG/zX2oKr+rXs2/Bw==,type:str]
    #ENC[AES256_GCM,data:zgsX/Ox0F0BkhiUywJSJrL0fG0XwGzE=,iv:7J6qs3tFyGoY1TcdNRn+4hxK5WbzsV//5J9JKLg9LK4=,tag:MkHxLB6JcFenChyYSO54hg==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:BqLgzqR/,iv:kD/XAsqLIsrU3IOpsREDwENcFSUEQzUlHqb0SZOINts=,tag:RLAxaCQEUCoIGWLWBRSZFw==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrb1lyYnlyajk1REUrRDB4
            RldlWTNSeEsvNnNTVEx3VmptMFAyT2p4ZnpnCjNVZm1ZWklUcVJOZWd5VFlpMzlH
            a3N0cWVDMndUUVl3NVJwZXlQWFVjeXcKLS0tIDdOWStqengxenpsMS9FdFZjWG9j
            dlBwVkV5ejJ5VDFpaEpzTi9jN2N0MzAKLpB62VXqfGbhb37i6ukihHMwFm+/HKEl
            yacPuS5o27tLfZhkswJISICh7GVJ6TTPNelXuJulV+EgGLtav9pTDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T03:56:03Z"
    mac: ENC[AES256_GCM,data:++VOVwQ22W9gWeJ+CxSDxFPccvC526oiy6boekiMMhzZr3Qqc6H2meMZpM2uSkzahJy6omqhp8IG5mcwWEZHVvaTHJBrwfaJIQBhpB8ZMfBgLCbSZ3efB8ZPvnHyth7IG4B90zQtGC9ENRWLe5AW0bnsPcQcobndtlLGfgSWzgU=,iv:mDpzZUhvBZ1QZgsUZMhJT6x7ZmQbw1YXyCY21zVI9fk=,tag:TFDoy/vNbz+XzXaSNjlTBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
