apiVersion: v1
kind: Secret
metadata:
    name: komodo-credentials
stringData:
    KOMODO_URL: ENC[AES256_GCM,data:CqXEsYdoPOu4I8NObqldZUluLrD/53qgrg==,iv:2ONGMrC/9Nly9Li78pQz98EuGvP2bGMXs6R5ufFXmWc=,tag:4lnPtUBNK64nwS5dIhTioQ==,type:str]
    KOMODO_INIT_ADMIN_USERNAME: ENC[AES256_GCM,data:tmNKBEo=,iv:X6UKmxaFoTgh51Wk/MO8IC1LSbJFcN7o9CcHtvCbK0E=,tag:7LW0epW+88BWgN9m5h2qjA==,type:str]
    KOMODO_INIT_ADMIN_PASSWORD: ENC[AES256_GCM,data:GsuEQL4DB6qup2AhtfR+nEFSSM1GgkWc,iv:D1O9O7FthHwfT4L+Ue09yLlLni1LoXjcrrRlMicxHHE=,tag:ofX71NnxdnCgjZn0md+XhA==,type:str]
    KOMODO_DATABASE_PASSWORD: ENC[AES256_GCM,data:0KpFTxoPMyo7iJI0XdwQVln7Q+aaZkCCPAgS2mZGzBI=,iv:mh5LTB2LKjm/Q9a5YG8DKn2UIzoIa2g3c7X28MTBSCQ=,tag:txGLs6Okc0NkhlOHyFKyiQ==,type:str]
    KOMODO_JWT_SECRET: ENC[AES256_GCM,data:nkQp9PQML6jx3tY2TL0uckJhtPQqqcgOUWZ18kcR1TYAFRqTUHjrxCkQYuQ+aGf14xzmEdnY9HCkEcUyEylKew==,iv:4dDXnsdkc+qQVVtN+EkEQqlpd8LE2BXlFfgyabPvt2E=,tag:LkrFdfRJGoljAW3+m3b7HA==,type:str]
    KOMODO_WEBHOOK_SECRET: ENC[AES256_GCM,data:FJB3wdFTXIpTpNCwhX85qXHRtbi/MjohhZfMiLye+PO5C42ZMw6SpRNWYJbovUBbHyKhVpfFOmeH+upuyC51MQ==,iv:1EJY55oRqZf/X8hYqIDm/QOo1AtnNyO4ytaNC4f2Hr8=,tag:EiothvEMtSp978fR+5qjVQ==,type:str]
    KOMODO_OIDC_CLIENT_ID: ENC[AES256_GCM,data:fJ81LiW7baMWJ4XCs/7mniJ0njCsSl4Uk033XRb8kNmzn4SCvLmE0A==,iv:ICQ1lDkmK68OXDTroFCRiHOjWUm/wC2P/YhP3yvAScg=,tag:icVkU/H0v5At6St8p8bCNw==,type:str]
    KOMODO_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:FRX+xXNolueRUdqAHYA4tNlHcK2ALNySqVXsAycLQw2tFR1HJF21wP2+HY7cxuuqj7SnRmNvE3FzyVD4rdbxWVQmi0QXneaiY1OGr1bkDczsfYqZXjE99q0XFPPZFPso,iv:PiFX0YaQPSBbhVmIYGLYn+ayn3y5qSmUQKecHWfpbOg=,tag:5wXaeDAyEoueC9OND3GMJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbGlIay9DaEIyZDJNazg5
            eUpaS3BSZGVQLzBLeENhSGVqZzRYU1NPZ0Z3CmdzanZycTE1cWxwQVZWSXk0Smxy
            SG9NNjFvaWVldEhLNkVjeHBFbjVLWmMKLS0tIGVrM20waEl6Zis3L1JTcWNMSU9r
            dTlvNXNmMytEUnJ5LzFtZHlWTEtlcm8KEo4PKpWyJAcf/O+B3KthdNY/sXMaY/VN
            Rmnd2EvBnsVGwmQ777Q/Gr+w8JvkyXos+MvTiLNlkwUoL25jlEMbJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T05:04:02Z"
    mac: ENC[AES256_GCM,data:3DYo6h6iaTFBjE/9jcBwTkGR8LEuWHUqvSa2Ojshv5pqIVrPo0vZAqklb0I/KPQbmjndGgSUzEr7PSVaFFsCv6PZ56ZB0NG3ekiJlj6GotB5hiBUocyOQxLaTBXIjG9HI/9cSXe022qvdp1OG64JJDilPn39YhutgO0Hgza7YG0=,iv:XeZAXsYsMtoSJXAvEhQJIOm6laNWr3w8Erjkw6yLEOM=,tag:rG0D56BPeHGCBV2O0nZnKQ==,type:str]
    version: 3.13.1
