apiVersion: v1
kind: Secret
metadata:
    name: komodo-credentials
stringData:
    KOMODO_URL: ENC[AES256_GCM,data:/AwouQ/5GjF4L++q/kAX2vid37HpT8Ks1A==,iv:hWa7bCbrnh+0tipiWN/ehFZpLeRUMz95CjwOJtQ/9RE=,tag:02whzeU8wAwp3WQuI9vN5w==,type:str]
    KOMODO_INIT_ADMIN_USERNAME: ENC[AES256_GCM,data:xb9Eyw8=,iv:q/jYlh2Pf2Hn2KNmY7aPmkL/i/TuJEpOwQyYwCy6HkQ=,tag:8lX9MOEW2nmI761s1g+gKg==,type:str]
    KOMODO_INIT_ADMIN_PASSWORD: ENC[AES256_GCM,data:rLZgVPNrVUMNjj3w4VwfDLu6uYTcuzOO,iv:Yza39X/P4uU9bb8elRUiquiyIyGRfMVFwqiBOeC655M=,tag:rqOQ/tEAeuov0hQHGSb7Vw==,type:str]
    KOMODO_DATABASE_PASSWORD: ENC[AES256_GCM,data:PyR1V06CocPh+5y/thYL+FL0i7e/mPqQwd7YGurJSZQ=,iv:VGONvkJjdni80gJRsXp9kEiX0QMyaSOFlSIBmJbGWJo=,tag:RzirfS6E4gZlfiyZtuvJlg==,type:str]
    KOMODO_JWT_SECRET: ENC[AES256_GCM,data:4P47TCKN7IGwQMX55gnbpHMfv+7+4gU4ScGfLGQ115hBAYExr2Rony2+VhLWLQ2f+vp/r5mnTxIgI5Kb8AhlqQ==,iv:CQ7Jd+Lmug2x5UUj1hSdYTOSaVdFUjCn9xQxP2j8cQc=,tag:QVLXnVMUzyIQJXBd3d7Zng==,type:str]
    KOMODO_WEBHOOK_SECRET: ENC[AES256_GCM,data:ifnJ6sDoy1FfB7YhsekCX+8pRyCaoqScexV30YK2fBYD4gswhuZ5NZXDipAve8g5cB4pz/RlQZBfaSHLI1+kjQ==,iv:SjL8h7jnSoNNsqU3qRoB2Yp62LXWd9/Ad0utIdwWyYA=,tag:Cz2u8nAYalJt/aR7ZsIiSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WW4vS2RwYktmbmZkUjhi
            MEVjeTdpNE04U1IwTmQ1bWQ5ZTZ1Y05MdVhrCjQ0WHE0b1BlZ25zVExoRGsvOFBP
            REpEU1k4T3RHQ3lZSWQyZVpwazhnbEkKLS0tIHRmSDVSQU9aWXVRVHlZckJBcTBF
            RDBwS0FMdWk2MjF1UFdCa1RZY040aFEKw1rAS5Hm4Yxs+hMfrZI7MetklCyB6VNA
            IFkdCUmkavHzFUlSsCvOKDxP+soasfMD5D5CegGgEkcfhfyi7RFSuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T04:17:08Z"
    mac: ENC[AES256_GCM,data:R831r8tsZuDBg9hzR07+luA+bUWPcs/9xmKsmoQorf2AOMUxx817iqWrteAJVmGmFzmH/Ts3xpkcuD0F0+CJqM/kKVozHuQeCyWHsFFu2OhiH9omXDEaliAKbinIbr0odD1ApoSZcpio4caalItAxN9DZAkTDufyihTybmWK8Ic=,iv:jQg0uayi2hd4vNOBOvMIg30QR8+QiNAe7J6wDTivrgk=,tag:sDXzznXgKwme7n7azx4/zA==,type:str]
    version: 3.13.1
