apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-qnap-media
provisioner: nfs-subdir-external-provisioner
parameters:
  # Root inside the NFS export where subdirs will be created
  # This is relative to NFS_PATH (/QNAS/data)
  pathPattern: "${.PVC.namespace}/${.PVC.name}"
  onDelete: retain
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1