apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: joplin
resources:
  - joplin-namespace.yaml
  - joplin-db-pvc.yaml
  - joplin-secret.sops.yaml
  - joplin-release.yaml
  - joplin-ingressroute.yaml