apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wiki-js
resources:
  - wiki-js-namespace.yaml
  - wiki-js-postgres-pvc.yaml
  - wiki-js-secret.sops.yaml
  - wiki-js-release.yaml
  - wiki-js-ingressroute.yaml