apiVersion: v1
kind: Secret
metadata:
    name: wiki-js-secret
    namespace: wiki-js
type: Opaque
stringData:
    #ENC[AES256_GCM,data:6w5iDVMzEbs31g+LlXIoLCkXX89sMQcJN5XKr5DOOlVFc1tx9k3sKJ/CwdrRtC/4mIiSrQ==,iv:cEVbeFqt5bnwlDwhdc6H/YTHAAoucwaBXw+rfVX9M6c=,tag:VMHA3bDO7yGN5Qx2rYXRTw==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:hh4WSQ==,iv:PFC7PmJ2YqK2Kf3fJeEO36ETz+OX62HWMkg1yPFhpVM=,tag:ptK5mArazEP4EdcOKegvKA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:SlWJCYH6,iv:MDwbDpqturfvDxbTL7mlbs19zVE8e6ysDRROuEacSaE=,tag:3dC9HSrqqscUU+wp4gvAlg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:hTjm9gb9zO5bKws=,iv:SeQE2xoBZwPersGn8s3IEWccZcy+nsHrvPMvYi2tZdc=,tag:5lgRF4twYtbSzKuEAEH72A==,type:str]
    #ENC[AES256_GCM,data:sS4WcCEzGI8uU9vxAFKeSFxzIxFz5RSK4v3HgwH3juM7cKyaELObVF6znXUAMYyqruL6cg==,iv:W33bJckM5YWL8UMxELF10jjfEMx2h2ehXemQ3j5oB60=,tag:WnrV6umKm1bPqQOqa6hbug==,type:comment]
    DB_TYPE: ENC[AES256_GCM,data:FjPlmT4CPOU=,iv:NJeYh1+46Iy3YSsYvEbkZm9Wd+kzAG2bloMf54l9xnM=,tag:pu1OkWTMnv4vK6wgXF+7ZA==,type:str]
    DB_HOST: ENC[AES256_GCM,data:hjgrx4g6AppL,iv:sCi8JnZZmQvUmBefTxEZFsU3cWKs4CMvAxrV3HkevDk=,tag:qtT3FkVrizUvzNaObuEb8A==,type:str]
    DB_PORT: ENC[AES256_GCM,data:0YfQ4A==,iv:nzXIsEqPkZqfQhx5sQzrl4raT6IOhGYtIYcsS3CF7WM=,tag:VrFPpVZmxwLWQnKVRVBaZg==,type:str]
    DB_USER: ENC[AES256_GCM,data:+YV5UgsS,iv:IV1ekLzebqM0okxDzIFyltJtPJ4I2xZpH3D8UFg7O6E=,tag:g3PrHCefkXialBn877hHMw==,type:str]
    DB_PASS: ENC[AES256_GCM,data:wEEUXaZBk6t+I9o=,iv:XATSbRQNDxlzfjwMVKtw0X04g3rTrRYbqcbfyIm/Rws=,tag:rc3W9Cfgj/5XwVOA3SOY/g==,type:str]
    DB_NAME: ENC[AES256_GCM,data:E3Yh+A==,iv:rNGVMBieAyR9iUrvYMrxUeb8K/Xi/ZJRKDQdDmQdwW0=,tag:CqJ1tL0eYnhgdHKYtsKVag==,type:str]
    WIKI_API_KEY: ENC[AES256_GCM,data:oogTnToyknTbByV1MGA6X+gDYWcN4hfdW8H0So9ZbYgdgc+uw1y35YCZAY90081Z9hF7jz8JYVcYTJiQ5R+is2+ccM22gnCi06oTaxpMfCv1ukfCn/WdMBFkaPjHRNuw3WUq/QfWlrTdgl9hx00xUvmpnrbe0ev4KozRU4xrgHgD98hfh3lZ/+BYFu11UYS80Y6gr+omaUKokcZSI0PKm/NC+PeLlczHfMS36IlXLPHPzXhGt3k3w8AYFQx43f59Q0uD4sLkgQH6P7UOlvomlpP+NFdlYWTk1Qk+2NZ3RCY/6RWN5K6/8Xjc7DmACoPF5+JsK+sSbPKD2r+B1L9EiJ5qaNK1tW3uAZGnCBqD1IiFKxfPGCycrN+os+oMzKSKFCGly4ApCBf8v14D4DovJdYP68rsF4gqV9EBbGUPYbF9+yKyx6aPXo6wXzbc+fNSSdhGt1tOnPobw8F4pocBaS1qVB5ehksp8ynlvRIibc1oXs3KaHivYTP7U21aTzbCNUk9jRaexrZfSEAuCNJdvNpW0dz+vbIDuIre2GcRjlwOmGONOxNxQcebyKAcQUBF7K/J4RZRTLzrLEhTIz654F2zWHQp8/USFSivgkD8iSKlIAMwgnb7UvHxxc8mih9qx/XEkW+cehp5j1ohpFEAvvsjB4HNFA==,iv:zskIrOPhcRMaK8zzx9beqIS9DqRXqP8YC+ffnvEMj2w=,tag:2+dkOprLnWFnUxB1HzMr7A==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:yjUif6SJ8GiSFWnooj36PLM8lczGGdPQy7rXwuKQ7crbq84NtTHiGw==,iv:btNzMqkBqgWL8yF3A3l438loAaEU9f20cD5ojd7q+PQ=,tag:sYqdyOWy2nycfyatDieSkQ==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2b0g4RHdpeHM1QlJ1UU04
            TWlwZHB3MUFrcS9NQmVsNW1PeFZSQzJqN0NnClF1VmZEQzU4N05Ma3hXWjdjd3lz
            QW9ocXEvTmkxUkR3Z3N5MzRheVdFWTAKLS0tIHNRMWdJbFVaT1pCNlE4YnFkeE5M
            M3ZQQ0xWYk4vb0s3MFBIVHYwNWxTckkKNyvYF2bPiw1Vnof95fHY1kTNPormw80Z
            tiMAmJ8KzAl7uj/DbIrhfJKsCfx58CNO1QyhLJd7TEfDVgm6N+NhXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T01:50:26Z"
    mac: ENC[AES256_GCM,data:HmRmmeanHSwg7oHTCGhk/0PKLrYGAtlZejiNm4DaxXF4FJZML/G6st7TCCuJNeL1nh3SzIQX0K1/V1EFgvcGgwUQuKU4yDJnuy/Mo7i8ELPbHo9yQyleOKGQLJFgqnw5jM5lLbsgNNDzutiI4JHQcKtis3oajd+kQ3i+7UT6bMc=,iv:CLQd8FNjxShj47ZBiQi1fs6stnE4sewd9hGrYY9HdkU=,tag:Qvg4c+kBlQK3STTA1ewQgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
