apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: grafana
stringData:
    GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:NDi5QjPPLdZ9,iv:rTbvbNSHHoCBjdTMtgmOUXwjrXKLfNwUsOzKujp2nfs=,tag:d43u1Sz5h61AjO+szRzDsQ==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:YFe6xNQQY+NpGfVo,iv:FYEEgajr+fc1nE2zX0RQV/dVk9c6BPzk4rJ9lK8CFlQ=,tag:yHZUPA5T86Gkqjq8RTEfLQ==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMXRaNFNkcXBtUHJtYUM1
            K0VkU01rWFErRkh3MXN6VWZKNjNjNi93REU4CkNUTVpxaWhzYVhGajdIckxKRmJa
            VEhDQm4zYjBuc1pWY2VkbEU1Wm5TK1UKLS0tIHRleStvVmpLMnYrbEd5czB5cnJo
            Q1cvNXpIN2lKN0h5T1MrMVBsWXNNYzgKBP8hjCz82kap0uKnt1kLHE83y7IYHRPX
            a4VXqu70NjdzLDjNjPlX2bpFa3ATWN5erEreEayVY8SOelsu2UGw8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T14:32:15Z"
    mac: ENC[AES256_GCM,data:yDxQNZbzVQh4ENB9bn4rcr/35FQhTo6OGCCd5e9GCcyxLU/0bdv+haMDp77IfBzF/mKVypzYUj1DD3c4xMSs13y1dZlYlu98aVx9SgrKvEATLl3h6WK60GTKLHmwhhM7sDSTiLONCe7AVbwWN4P3aLihjp+uHeShCWj1gw0ZGPM=,iv:IYzuhKNbgOTuAqQ3umseN/HRsKJrSBuoTLAZIDXt/Mw=,tag:ueOvTUAUhIUhHIhLl9DXOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
