apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt
    namespace: zigbee2mqtt
type: Opaque
stringData:
    ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:HtmUmPHxFGOE,iv:Z23scQwHoIGHlYlRCZqnHhqUzEPcDYoUsD8qcn0MJ0k=,tag:qkqlgayQZ/giHnBg1XYN0g==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:gN0t2vi8OEsoFL91,iv:y5leMW74Udna9g/6vLwqD46mVFMtAIRcpB9/Kl3vLnM=,tag:VEi0BPm33xgjsg88xipDOg==,type:str]
    #ENC[AES256_GCM,data:94j8Gkvvdg9oTvoUqnHznPbrOxOibxmXOGKNsjlTGcmZUuvoPpcT9SWEXsoiF/gp0PU=,iv:lx8z72df73gt2Q9Uvf52pRmahZ0gifEdxUCKMxgJr9Q=,tag:QaNazt7dD3gKkZD5raVPyA==,type:comment]
    ZIGBEE2MQTT_CONFIG_SERIAL_PORT: ENC[AES256_GCM,data:W3wXFRIlfgx2YPF/8QTJ2VEAdypsVZs=,iv:lXgEoTOcmms1gTP3ZX8JPBiL9QcKCIM/GAYb84W91U8=,tag:tfPYdEir/JRMv2mT7dSd/A==,type:str]
    #ENC[AES256_GCM,data:unBrsdMtiLE2sV6HaqQrIGT/FPYlL7FpqNgUQ16U0tI=,iv:RxyTvlHxREmUHudbzJyl2CdQBloU04ofC5x/zkwVLb4=,tag:JJfJ8jX1MTxdrwGAm6rfCA==,type:comment]
    ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: ENC[AES256_GCM,data:uUapQmtw,iv:Skb2MqWBj3LegCHWpvNPJwwn65DMec5MuqPEec32rXM=,tag:jgHRP4iXcF523+7wdBW14w==,type:str]
# Optional but helps keep MQTT tidy if you want a specific base topic
# ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: "zigbee2mqtt"
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VWFOZUw4eXdnR0E0R2dz
            K0hSeUpMSFVCN3RoN2duM2xkdTJkYitGaWlZCm02bzlBN25aYTlQVkwwTDR5RCtM
            WERrMklVNGEreENZbHZ3bXF6Tk9weTgKLS0tIDlWNEM5VnpnWThpWHhiOGJSNlNz
            WE41eEFlQWhXUEZ5ZW9NWng3d1RrczQKt4TqPzmsQaLj3ZJArYYt2BYQpEw4ZvOJ
            NzljNyzOyuWzOCSuAQ9TH+cD/K8M/Jnprgy/LAsMZ9Qi9ord8y4CuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T23:30:34Z"
    mac: ENC[AES256_GCM,data:yE1j2a7dgtXeCykvvYuPg3xdW0dcSJ0RogH3LDSPRbBXtWUw0Z1529autI2Vjr66qa5D3A0fzT1rqYdWUaZACslSMkZh/x+iD4RnJ4nOoIbCRO9JRULujZiy8XWLDnngm/7LKSvMtyCLpL/H8cT84YHB4LheE239qqWrGjlw5QU=,iv:gxTpbw07BVv9JEiSld53KKlYQa0ifQ6aV0nLubbKW60=,tag:yXj3AbB0kJ8ev7TD6CrhjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
