apiVersion: v1
kind: Secret
metadata:
    name: dumb-secret
    namespace: dumb
type: Opaque
stringData:
    TZ: ENC[AES256_GCM,data:LE5IdtI0DT9jIIRDdWCKHg7cDQ==,iv:QhrKnf5lmRk8mXX422lLTiHdjOyrox0v4NMhsGpA1Bc=,tag:SctHnY4wi4tBQPb7IDU0eQ==,type:str]
    PUID: ENC[AES256_GCM,data:y24a0w==,iv:eiuS49gMBO6nwVB7469C7evhlAhJ2/pTEKT7u5NdKkM=,tag:LsIBmplS70i4Vv4Bws/o7Q==,type:str]
    PGID: ENC[AES256_GCM,data:4pe/Qg==,iv:VuLuJpa33SGzRtCowOpl7byhxSuEcAHtcnBtpfY5Uwo=,tag:uyF/uA6BWPctOHCqk214UA==,type:str]
# Future placeholders if you decide to wire credentials this way
# REALDEBRID_API_KEY: ""
# TRAKT_CLIENT_ID: ""
# TRAKT_CLIENT_SECRET: ""
# PLEX_TOKEN: ""
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbktIczBqZUQyRUY3ZS80
            MlhNOGNtMlQzSzQ5SU9ldlpTcTBwa2FvMmtvCi9LbVcxeWtwRmsydWFqVmo3d0M1
            UTYxOVhkbmd0TjFERGplUmJlMXd2UWsKLS0tIHlSSTdkeEFrT0hMMlJzcG9NV3BH
            NFNTWUZzeW9ueWkyZmtaTThsYklwQ1EKmaMdkVw48XSuqO0fnzQd1EeJY639qr+O
            /M+NFMudCVkIC6R3mnIQhlpFgsB1s0qDZVahu4vKwDPhPEvt90aHAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T00:29:16Z"
    mac: ENC[AES256_GCM,data:17kadQRD9w3ncPUG1rLNPFn5YuuhTd69cdKDhSHNl025Kql0t+k5kS7GmiSCm7fAnzrlOoiIL4s9mt2Do5uMse3GZ6ctgpSFGil3ZxSV6wZ4nbaxXGLdFe7f3/vHWw7W/A8w1svcIllZxnmEznEEBrQKrReUN0B1/5CPoM/LwSk=,iv:KUGhI9mkQCfVLdDTU55WMtq1W14bu8S2pqUWNfeRDq8=,tag:gpuTr0ZYsCN2cMZKT1vgSw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
