apiVersion: v1
kind: Secret
metadata:
    name: volsync-dumb
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:FfGZt1CYtIDALoQDFJ5ct2bwL+yvQMT+9oecLWxvP0QK4pgx,iv:0e7SLKsbzCxzXm72vLSqq6ZHi2+558tMs5x8Wfr5Htw=,tag:FXxHhX0btsZJFONKEMwARA==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:S7FgkGKGyZVPvrK/,iv:0tHZMzSqNDLNNiOa/pqmwZHMvVnE+xBOixcaUUQF/nw=,tag:3gmNkujLBJNNTpnGAXiBHQ==,type:str]
    AWS_EC2_METADATA_DISABLED: ENC[AES256_GCM,data:zNi876cjKvQ=,iv:hk2wAaBDzRiG2cp1fjywoIO9MueU+cpjUgHLPbFld0A=,tag:0ec0FnvWJj9LoiOHWLILLg==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:vhAlKzZD4qw5127k,iv:u0Z/fh9RhkW+9pC9LbYy+xx263lc2C9pJk8FLPjfQOI=,tag:iWKdKXZWrzs0nkoBCy0Kpw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ESzR3R+eOwrGzk3Hq6wT5qluF0GPYymuQIYvHmpttBKRBpvIKMIiukxzM/1ic784GNuOLaApx8YQ9hSgOQ7onSaSwNoeEmpZJpToRtCuIYX2rkY47cqL9A==,iv:0ggceh6SKTh8Nwcuv1raDUf5kMOTrj88PP3DuBYNot4=,tag:K4cxOK0G4y1MwM1ZymYL2g==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:8L9CJwFVvAjT85HgTJLXuK2t7FR0pRcEEmKusJmJUMa3MexHyy+/6nXXRUxEB832snLAgZEj2rmo37js,iv:1S7EUwUHuTtwP0KtdvOwlKy/8rUAuQSXbivxJX/WMqQ=,tag:8N3WrQqbMLy2oIfl9pvvQQ==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:iid/xMxWZfqLlBcTlftpH8p2sCznBpG4MFYfKplapasFurr6ZVSeTob+qxM1BgLHIeSeMhkfPG+bFLTg,iv:ZS8gRRXkiDQHcoE0u5PhUIsQidnE2C85ifB6YZODbLs=,tag:Y+f/d6N1THbJ+QkpKiUUNQ==,type:str]
    KOPIA_S3_BUCKET: ENC[AES256_GCM,data:bQmnrqSIVXWjK6AY5A70AIVZv4Q=,iv:p4kWqk/jvhfZi4OZzMEx8NzFhpJeaI+xyaxVCbkyW1s=,tag:14AFXmMpNeyp89QMqXQ8Dw==,type:str]
    KOPIA_S3_DISABLE_TLS: ENC[AES256_GCM,data:uwDb0SUC4kI=,iv:9nbwWdndvKko3dXwgYa4n/zVTqV8zrhkFmSALOBNfeI=,tag:OEmCeWm5MKKJLD4NXgoPXw==,type:str]
    KOPIA_S3_ENDPOINT: ENC[AES256_GCM,data:tnD1WShXlxKpnEEDIVv7mc89QPl6y4AKbTJGlSEKj3c=,iv:SDO/W28+HLsQG0qzmR4Fxve65lOaZQRAFJ8sLTarnTI=,tag:YnS2ah9oIXRPgqIfix9q5w==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieVFOTVlaVEozMWtheitq
            cldpL3dmS2hFWkhWeDczZCtFblI4Z3pQU25zCnVmZlVTdjd0Ly91Uzl3VWVLV056
            QVpLT2dablJ0ZWVOTU85L0hOUTFxaVUKLS0tIFI0SVNwWVJjaXhKcVhpS21zNUtY
            Zmd0S3hLWDBxeXlqSG9ob1NnbUQ2QVEKYBsRqR+Zz3Q3jgs069XLCTvmXBkBeOP2
            FRVcY4DdCnMAIHkIIOME4JgC8t3HR5NjXz2+yiu1SreE/XJWdZccRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T20:23:54Z"
    mac: ENC[AES256_GCM,data:MTBL2yf0QQwsMQmUAp7HfPd8xRBrCo73b97mBgTWEeOavAXP9E6EvefuOfBEPvjq7ggw4vj+O/nzyUxPr49v+FiOO9CSPo/e5YWObKky6fqU//afA3WZItjp28v1AndhDjUW4AxRY4CKsXrFhSBvB0hylCAmkO/I4Pw2fnkLgzQ=,iv:tyXOqtP17IcvRBH2J1j5YCMeaVptxEdWPZtk93/S1CI=,tag:PX7b8gsRbtEu0u0Q+iOUGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
