apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dumb
resources:
  - dumb-namespace.yaml
  - dumb-secret.sops.yaml
  - dumb-release.yaml
  - dumb-ingressroute.yaml
  - dumb-api-ingressroute.yaml
  - dumb-lb-service.yaml
  - dumb-service-ingressroutes.yaml
  - dumb-rbd-pvc.yaml
  - dumb-library-pvc.yaml
