apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - riven-namespace.yaml
  - riven-data-pvc.yaml
  - shared-media-pvc.yaml
  - riven-ingressroute.yaml
  - riven-backend-configmap.yaml
  - riven-frontend-configmap.yaml
  - riven-release.yaml
  - riven-backend-secret.sops.yaml
  - riven-frontend-secret.sops.yaml