apiVersion: v1
kind: Secret
metadata:
  name: "${APP}-volsync-b2"
type: Opaque
stringData:
  RESTIC_REPOSITORY: "${VOLSYNC_REMOTE_RESTIC_REPOSITORY}"
  RESTIC_PASSWORD: "${VOLSYNC_REMOTE_RESTIC_PASSWORD}"

  # If S3-compatible:
  AWS_ACCESS_KEY_ID: "${VOLSYNC_REMOTE_AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${VOLSYNC_REMOTE_AWS_SECRET_ACCESS_KEY}"