apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-remote
type: Opaque
stringData:
    VOLSYNC_S3_ENDPOINT: ENC[AES256_GCM,data:AsxBBLVRmhpXqqSXWpKXU9I7CgvrsGVjU/3+wuSz1OU=,iv:xf7XhO/f4xE8gmF4HoWs5MjfnOZv1aYDO+S684UONHI=,tag:oVYibbYwaAuMs9i73TXW9g==,type:str]
    #ENC[AES256_GCM,data:OQJWJ2uq5LVfGDWL21yDunszQk1N2E13exicW5gIpnNoP7vInOwKh06+k09TiPU=,iv:ki5D/4E5n6edpRa8hN6NFJCwYN9k7mXnxd5G7LvGPv0=,tag:jQEByG+YFUtuWKcqr7ZeuQ==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:iSHMisqPtY1/hopgDt5C7R04IoT1N/PvUWzm5ISe7qgNoKVsOLDiLIyV7kh+D2E=,iv:o9fcrDIPkVF64Ht4L1kgc9g67pM11b3FpZKvNYlZtf8=,tag:5U+gxafjGbo1Io1cA3L6/w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:iZ8kpLedcXMuF2veG+9xe9/J7oiM330ZCcI=,iv:2o5ygwtfzi9x18EW7AC+UBcOPD5QW8+szBuuhPIyhBA=,tag:K/GsyITURG1v5QqJJIanKw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:9rKMKSIGWPnDtSWP3cQ4UmWYLRqkFaF1565OYw==,iv:fhxaeW2ofdJ228DC2P5yxSNFFEupCdHQabU7p+Iqc1Y=,tag:kzm9Bmnp9QDt+P7Pr22n0g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:B9imJz1EWNICQ/2PFhkzRiG6w/+tNeRhxex+yvsXKjI=,iv:vLH+dAnzJPmMnxNQvq2sCvgc2yIDz8/2m8rkrzvmHU8=,tag:MgNlzKX6Rnk8raA4VSZbpA==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:e+6N3IQQKa0zfIO+5fuz39Uy50WVQMulPfZmxIRsgw==,iv:9sbBt5UJA/hZl7Z7Iz6WQBNcR+I5gHHvpxKwH5mqz4g=,tag:EKJdGuW7Tr7k68FBITMf4A==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:3H5WPkWECrvwWFGnBulP1dNvB7o4HfQ+IKr9Zwu/fQ==,iv:myj/5B4SvrlFdUnuuulqi+Khx/1Rewz3m91JTb7jyCE=,tag:Pmidng9Cjg1PIQVuXc5JYg==,type:str]
    AWS_S3_FORCE_PATH_STYLE: ENC[AES256_GCM,data:sCqk3g==,iv:36vgQ4MjirKgDaQTLMxw2lDyIZ0QnUwL7QiX+XhlURM=,tag:rSFZcS1sReTvs1/A8QuHqQ==,type:str]
    AWS_EC2_METADATA_DISABLED: ENC[AES256_GCM,data:BZMTdA==,iv:VLeAGVvGzZ7LR4PdxilFPSVchjDa4/NhYLcoUIcAtbU=,tag:rhUOZAtKomzcC+hyODOJPQ==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZ012V01LcnoyOWZRb1JQ
            ekdjelhtWmFsUnc0d3RmV3JGV2wvc0VEUEZZCkxoMlcyYjRYbmxHWUkzenFLZ05G
            aE1DdlJObmxpblhyZjZtL2hUeUR4NncKLS0tIFBpb1d3b3RaOVcxZFQwZ1lPVE1j
            eVE4OVQ5Qk5RblZJVVg2NHFvMWxiSGsKXebmB6Yo6+dwftgIzGRZBvkBFA0EwGMR
            t4i7mPOQASb8/6EAK39RGh0RjQezM+12OeRGBbfsZmCU30WHuRlfTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T14:32:00Z"
    mac: ENC[AES256_GCM,data:D66iXotI4OPo6eeoPIEvdXRyJiMmDeK3ykoYr5PyE6+NMDFDkyf8+jtsnFh2wjLqrgIZTgqvHUStk+krIwgd1KR6LZtDTPomV4JghA2A0qRNUyMe0kzaBsIAHqDxfeitg+as5Rn+UC8ln0YfYFXr0tM7tjiBXm3MmlK8V1f7008=,iv:kUUkqug4Ver0Xc6nMgVZVDtkZm1sTmtNLzNV1hWZWtk=,tag:MQ/UlQcwLJqVUOitYkO42w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
