apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-remote
type: Opaque
stringData:
    VOLSYNC_S3_ENDPOINT: ENC[AES256_GCM,data:kP8KwnYsEuOwXoVzTOeyWkdSfxliPnbn2TIHyyngY3s=,iv:rMzPPP43Nmr9niPbYPLCpthZZiVWE86QJ6bqc+1BuK0=,tag:4Ze6bUTz7ZIhivLSgHT6rQ==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:UkD+4K5FVykyfQankgYT+OLdXLPTSsuND/On3NqeIMsNPdYe0HF31w==,iv:2B1rFTHPdqcGfvFnGZbiG8SkwHk5zri/nas1cphE8dg=,tag:vWQlFnoV329M56OIqOuI/g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:akbVwZbfOEi4tb+INIr+xKLGteGBKW2JwMEYEBj2UgY9,iv:LUs9kTuHhzIXtVyDCYXz7c84Z7MwpBPIW2mGzJSpCpI=,tag:ab0DQdVKSrKr9uL/Qprx1Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:px59Iy07BqpDjSmT3u/HY3suNMvD2rhPKYfPDixabb/AHew=,iv:UUyS39iWFCgGBa2uA2KL7sSj1RDsH5VI+BLiuVhbktw=,tag:VchWEXk0dnFfyfg5jT05pw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lSM4IkiiCkJBQjPzBdcppzX2n5iXyRNQegXUyUkW+0XDAUJNIsyi,iv:AEm/RJzCvtcZc20GXFBhQEYipCGoMYc5dftM/UNsMRM=,tag:u+iJZBZd4vdutA2yuHii1w==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:e+6N3IQQKa0zfIO+5fuz39Uy50WVQMulPfZmxIRsgw==,iv:9sbBt5UJA/hZl7Z7Iz6WQBNcR+I5gHHvpxKwH5mqz4g=,tag:EKJdGuW7Tr7k68FBITMf4A==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:3H5WPkWECrvwWFGnBulP1dNvB7o4HfQ+IKr9Zwu/fQ==,iv:myj/5B4SvrlFdUnuuulqi+Khx/1Rewz3m91JTb7jyCE=,tag:Pmidng9Cjg1PIQVuXc5JYg==,type:str]
    AWS_S3_FORCE_PATH_STYLE: ENC[AES256_GCM,data:sCqk3g==,iv:36vgQ4MjirKgDaQTLMxw2lDyIZ0QnUwL7QiX+XhlURM=,tag:rSFZcS1sReTvs1/A8QuHqQ==,type:str]
    AWS_EC2_METADATA_DISABLED: ENC[AES256_GCM,data:BZMTdA==,iv:VLeAGVvGzZ7LR4PdxilFPSVchjDa4/NhYLcoUIcAtbU=,tag:rhUOZAtKomzcC+hyODOJPQ==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZ012V01LcnoyOWZRb1JQ
            ekdjelhtWmFsUnc0d3RmV3JGV2wvc0VEUEZZCkxoMlcyYjRYbmxHWUkzenFLZ05G
            aE1DdlJObmxpblhyZjZtL2hUeUR4NncKLS0tIFBpb1d3b3RaOVcxZFQwZ1lPVE1j
            eVE4OVQ5Qk5RblZJVVg2NHFvMWxiSGsKXebmB6Yo6+dwftgIzGRZBvkBFA0EwGMR
            t4i7mPOQASb8/6EAK39RGh0RjQezM+12OeRGBbfsZmCU30WHuRlfTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T07:31:38Z"
    mac: ENC[AES256_GCM,data:B82mNbPUkFtSxVTOQMa+u1Qm5gXwDYa5XPlOR9Vhy0X2B2AoOtFMIcrtkNkjU9uyOok5P6XuyJ1m4J8kwj3mqyDgaUzK4ZVzlfyJEpNbC4ss4td4mCSYXXF0SxE6TnUOH9VpD/Yg1pgFIDAhvKkJm/22bIzJ1FjnxSr7QkpaLxs=,iv:OU0I+YpHY5xhXIsEWccKyFHYRjBbZOmztAtoPO5SwZI=,tag:NPcCGIMbjNhi9B26yYGjqA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
