apiVersion: v1
kind: Secret
metadata:
    name: authentik-postgresql
    namespace: authentik
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Q/6NTdTxChAL5VNP2195KYsOUGrYD93FUdkELgk=,iv:0GJj3aKEXZjWmQ45QUtyKzGrYg43cFT0qFZa/B+7x3Y=,tag:imNejb0UMd7vuVpsGopd0A==,type:comment]
    #ENC[AES256_GCM,data:BtdneC/03fc=,iv:Im0gbh38b5blwwQzmyg15c+nl0hNfZ0/Kmm/pK6Q8Os=,tag:bU4XUq3GA6fMG82rIg+Vpg==,type:comment]
    password: ENC[AES256_GCM,data:W+SWc/LrE50mbHz9yE63b9vAGlOBfDJS4/Fjtox1xV4DUHScWdKhhpolqVs=,iv:Etavik2eIEbPaYeH7n/oFdoAwQSojtYVOF8MA+RUlsU=,tag:gzugJpiLh3XnTI3EX64rlQ==,type:str]
    #ENC[AES256_GCM,data:5rf2GeeD9ZHb,iv:wnG7gxTb0Cba3gl5B3Ye/vKdbyPx39AxmMrGSkgtZLs=,tag:c3Z2bksBVfx6xdTOrPHX3w==,type:comment]
    postgres-password: ENC[AES256_GCM,data:oYOpvt689EZJRDT1U87C7CKGhZdWeq1DJAXmZnArKHGYkhiKFH2Exzo09UA=,iv:PR9Jnu+RMZxrVzjALYobHAB8F3UZu2zygJSzD7ITgvE=,tag:ntl4ndbJ/NNMXX3asD+HCg==,type:str]
    #ENC[AES256_GCM,data:G6lkS5Yax3Q=,iv:DGgEbhXIssx2+51Moyvt8vDeS7hZSlMXTsEAqjIxy2E=,tag:VdjT80r07ltrrtqDzTcoig==,type:comment]
    replication-password: ENC[AES256_GCM,data:aVmft32e7AlVHO7kJuWAPLS0D02o2G4te2UJEU98SKz3eNosdTDl5R+4oY8=,iv:4kHtodAPlre5j7zDkFBbKCt6raiIbXqSHdrT9gWB4D0=,tag:Yg9gTIgzKae2VazJVReUBw==,type:str]
    #ENC[AES256_GCM,data:APQBQifG/GyJCZ0ri3VXdLoMgb4eDPiRzt6zyUX8dTvmsbdckQ==,iv:btHdtNmcwkMJeaI8s5HQQxH3un7JulkfXh1jPeZZoQM=,tag:ML1Cl6WoyEz6egJdvQ7voA==,type:comment]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:5JjTPupsMf/PrKr034DvLen9HFyMPPXFJ82EuX7p+YADMflyHLHZYmuAeQx52jo517oVehvZg91RRWTHiACjNg==,iv:HjZo0MRhlVdzW/sXaIb0tqFsa7GqZIiT1UgvnNSqrc8=,tag:S8I5E0JR1Aodocy9vTDZyA==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:6QleVaE5lybnU1v2kL+CyV1LWw==,iv:TeywUqAxNl3P7r3gaLw3jVIlU3MFwZdoX89wjrAZjBo=,tag:/DFpd0TPH4YbebtEtSG8qQ==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:bDNK+4Hkmn9ftg==,iv:XgeBsvg98oZhaGIZ+MsIMcMm/Jsw3mM6LDXJjA94DKI=,tag:8yr5VK3NvVZ1tFZLocfh0A==,type:str]
    #ENC[AES256_GCM,data:/+uMn1LOQKcutQyEaMaVi0nGF2puE97w02p61qaQHsyk,iv:/rRDr63q4CxbhJ8r613DvTMRTAO+vhTrGIcbRYTA5TM=,tag:sAb+ZNHewgCLAiHyNjm0mg==,type:comment]
    AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:aZc2C9vtQRgiefZXm3uAg3F7FQ==,iv:mOpH2e6z70QvP59AUjEQ4GEvY+oxirBYWsjkzna5SDE=,tag:AvYavSCRe4BxyAEoCIpKOQ==,type:str]
# NOTE: Do NOT commit this file in plaintext.
# Before committing:
#   sops -e -i apps/staging/authentik/authentik-postgresql.sops.yaml
#
# SOPS will add a `sops:` block down here with encrypted data.
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Vi9MRW9mVFVwMUk5ajR3
            ZGkzQnlMZDJLWFNsUWd2SGJxS1dYdGdYNmlFCldxYVlWd3AvK0Y4M1hCbHoxbDF6
            dTdjemNuMkZ4VlBpVzcyR3lHNG5BcTgKLS0tIC9NWExlUU0wdzNIQnh5Y0FxMkZo
            ZjY3WGZzRUdrNGxUSjVWNkswc1BKRXMKqvvY/GixR6r6DA/kjREjfklafMGUopGC
            wt/tMRemt2HRGBEsmfRHkQY4NpBdKNoB0VaDZcOOojXVZd2XohW/4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T22:09:00Z"
    mac: ENC[AES256_GCM,data:psbNEalXqOHrakzJ+6GlwIbar7I8Tw/ZQA40S421MOAE4kW7DzLlU2JyH1E33D3tZrqOfSZdCgC9N8nvc0lqsHdNsRWM/8yXOz+xvV3BO8tH4Awpavv6VfU05U+7rwcaGvitYt75vIWrM0sGSwRlqrO3Z09i4zjYVd3fU8WjKBc=,iv:Erp+qtOWsFjYr1QJUmMBN6oC3rrcV2Q/D+1lZvL6KEo=,tag:48ccWD9ModNXx001CidKPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
