apiVersion: v1
kind: Secret
metadata:
    name: pocket-bridge-secret
    namespace: open-notebook
type: Opaque
stringData:
    #ENC[AES256_GCM,data:r2AE1suYFPRq60PFqCpJ2OBfZKooaAPWBapC9fVIjbFIv2/LH8FDqubRdCELBOw5ydbRDB0H8wmG4N1cfg97gsgFY3xU378OgQ==,iv:7hm15KWUy4CcEq7PGWnXjqDlNzwrMJp/lnsWgVnV+3Q=,tag:SWWJEcpDH04BAuhcFYXH3g==,type:comment]
    #ENC[AES256_GCM,data:V/cqhU/RUeCOQtZm4f4d7XdfZqy7c9ePpXOmyGvOgpEYuMZ6gij2OfF37Mjz9ab9g5zCj8AlFgD5S5T3eBQSmnYe2SCZ,iv:FaeIStxwFw9VGssSM4i9mHOZiOx/FcKYwTTGpW+9yK0=,tag:CDDWmLv1Mg5owKbz4/Fnbw==,type:comment]
    #
    #ENC[AES256_GCM,data:NA5nNdy/8ZKv3ZtVh9Z8whYLkVuCOmrCafMx3rDuNr3L3D7MmIQ76Q6W3thnMTCAGh1h1DPM6pWN0TCq4MJ54g==,iv:moAXErcLf9e23s9GdNxmXviBOEBFnLiCkvaLpqf4gM4=,tag:/y9YCMwD9O+dElA2sPCE4g==,type:comment]
    #ENC[AES256_GCM,data:FBdSMv2rvRuCOHXmCFY88IyQuMkTI/FJkCtxDvCYJYOTENLiJfJGF2Dmg5ccx9WSiYq4tEknSYYWQCOqlcvemoc97g+/vQ==,iv:OYQR33wMSC0HclHGoMK4XVMbRN2TirNmWaMvjYWHTDg=,tag:edicrev/CVhKMmO1xrnHcQ==,type:comment]
    #ENC[AES256_GCM,data:wEuzHq8hbi7dVLrXo+l5nP6RZa5ZB5ajt3DxKKB3rWQFL0fvOK7wqLYMM/I9ReDQciTznQn5T6AplEZP6RjGexwkND5+yU250O8h,iv:p3Cfdm+tT2HJhxrH21O1VZphlcGkdyjPM8G15l2uvs4=,tag:Z6vnz/6Rw6hRXaxB0r16+g==,type:comment]
    #ENC[AES256_GCM,data:BM8B/Gh9xYtq8n7kThTyli6kT2UFBepzG7NYk5bXzvQL/FVIBgY6NDCJ08AUGTN8tS8m+o1HacpmhNoV48EiJ6kaigiwM9Z0,iv:cV+hrPCNiMkvSUf/xi9Z3g/5eAljpNhaHpJciiPyGbg=,tag:MCZlBfGq/yn3TF26G8SyfQ==,type:comment]
    #ENC[AES256_GCM,data:fBvzXIx4DgGuusht6AWDiEZJfw8Jl7DUIlJaj5NCdNEQR/J0+MsMaACaGchq+v7gqf0PzMsE3VPDeh+78rA1fYM917k=,iv:5SckPG303dlzFppRuc/McCGTqdAU2ZMcCyXPdfZH9QI=,tag:qJzTr7uLp88r7fTPvfg69w==,type:comment]
    #
    #ENC[AES256_GCM,data:s2It6QCccP1AWsBBjmlZ6DlHlart7mbpX2SeS4bqqqE9hGLJUwpfpR3P9W4b+XY5IWligz88Lgb99LNu1DnBHdXlwpSvVLzygneEPRWq,iv:R12s6NMaK+uRYmzxExeeMTNq5r5WK5ylqRqYCJzaKmY=,tag:89GS58hl+jKZ7vk0yqR4Dw==,type:comment]
    #ENC[AES256_GCM,data:GHl3oN9e5PSQlzQ9EUQkqBMSgTjQtGleTE9XQZ2JcBoHsCz+nbHgrTS0iBMNlQcps74CrYeF2vBLy87JrTUK,iv:8bK+xy022RA17H7im3+JvHchX72zjv85TMLjyRAl4d0=,tag:0tdditkmR3xAVcxnY/vDCA==,type:comment]
    #ENC[AES256_GCM,data:+KUBNX2QHK6YETZ2Mdy+g1W0FigdGfWsYm6bRT+xg9yza6jfXyGOSS7zIzwqoiT8GLtp2EXeQrY/z9JidRoVeQ==,iv:gBs/28cRN23gbAoxRKbkZAqLCpjT2aLSOFsODC6Y7hg=,tag:jcRbhCuG7t29eSXbTnO5EA==,type:comment]
    POCKET_WEBHOOK_SECRET: ENC[AES256_GCM,data:SoQN/mjnXZFSlDQCTCDx1CsTP4/fxFkij4j2ACtY+vILIszJ+SxBikYX1dB7gjr71sNQk/oKmEwj955IS+O85A==,iv:zSDMg1GqdySCW2ig5vUvuOLVSexemkAbdrheutl0PIg=,tag:/B6qWMPMhdJuSysPIpa0uA==,type:str]
    REPLAY_ADMIN_TOKEN: ENC[AES256_GCM,data:/1OQXm7s4cqkU4D+zyqweaHWhgWwTItswc5kdLzohc2sKJf/nevJOQU3dY5tBoMaBYbSyE4vpFUXJ5+l0KfAzg==,iv:GmkqaYQiyBzUjcna1gFnpJAymPJ2/OkxwT0mUVBeZ/s=,tag:gfiWgD8lAV1o/nRilbrxuA==,type:str]
    POCKET_API_TOKEN: ENC[AES256_GCM,data:nLIKXM1qwAVIZ4RizVJt8v2t9Y+5U94qmIUW8FrRcCcOehVdYVgXm4neGLOGnnAfXldfoGa3gMgVEAv6owNfnbt6ZA==,iv:dsHf3Q4sGCmBHFqJ23PX2P3F3QX/pa61obsoDECKHXo=,tag:6HR4lwIkwzILA/No/l+5wA==,type:str]
    OPEN_NOTEBOOK_API_KEY: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMzhodGtmK3pCU2NsZHMx
            QmxpeTMra1JlNGgza0UwRWhCU1liYmFTR1V3CnpNb3dZME1aait2YjM4YzAyclFv
            dUN5KzB4eE9qQ0VHdU5YZUdkYVMyNXcKLS0tIGVyMlpHNXBhMFBDbnpEalJQVlIy
            azQrRUl5T21zUWExTUhoRFVEcEt2cVkKGSm2diqTbX3h47qlC4IE4DpHh6/VnPqC
            QtIxN+BJvOvsxTvGlBs+HcvhmFRG+b89UNjwJ4r6/v8W0gETPNV/aw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T04:46:24Z"
    mac: ENC[AES256_GCM,data:uTlpRqO5WQrg+0AHBaaKgl1ovviVyCJzcMpB1WaHa47wWyqoZbXZEuUVPM5FaFkSURPo1CnDsuRW4gN9OR65nrple1LwCJu0J0h8IQNMHbnwvr2BinEauMrNKy6JUTu5dr19UTA3uatny8QzMGgVP/xIJQhTNlv5PIMgb+Lf5IY=,iv:XlsWsEvJ9TlAs1wWBV92vzjRsmLhxOZ98lOMds2YMkY=,tag:ErfHKOhJLjxLRc8SqflTHA==,type:str]
    version: 3.13.1
