apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  authentik.lab.mainertoo.com.server: |
    authentik.lab.mainertoo.com:53 {
      hosts {
        192.168.90.180 authentik.lab.mainertoo.com
      }
      # optional: fallthrough so other plugins still work for other names
      fallthrough
    }