apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt
    namespace: zigbee2mqtt
type: Opaque
stringData:
    #ENC[AES256_GCM,data:XNGi4PlTKcmX1HfsukDfUG/zZF1kx24fFBkCEhVWToVnGg==,iv:+qCyaBZoYPh0u74rmHr6u+H1lnOEAOXfq2St2gOLKNg=,tag:WClhhuZG8Jy2kXstJEww0Q==,type:comment]
    ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:1nz9Htq+1Tug,iv:ZoGree/6L+S2ljJxA0Sosc842D55IkwwVNa73oyGKx0=,tag:95+gj5M8eC9USAhH6KAy7g==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:6IaGmU9sikGCgS7O,iv:wo2Lt6u4hPSMP5089RhfjLDHTAisc/3SS/xMeAqC90g=,tag:bFmZZ8XBt147icsjXVsDjQ==,type:str]
    #ENC[AES256_GCM,data:fh2VHLfGqvF4AvSOfFTUjKLA0urjTsQY4OcifhrBO4Y2ubnH23kFlbmulGwWQKmWFHEQMamkrhQK7aOvvFwg4ukLpzvOFGngsoOYWpEvLoTSHIQoVGnNve+/TkXnEA==,iv:GZqJcr8j1at+dzhGT55SAd0nUuCE5tZEgNL4hkUOMVY=,tag:YKNdlmXBC1kuW3+J4T+6Sg==,type:comment]
    ZIGBEE2MQTT_CONFIG_SERIAL_PORT: ENC[AES256_GCM,data:oXsibBd9LvAWLvrRrL45gT6aytrG/lceOyOXXnlOwkkIkhx4R5A31uI3jANguEP9uZH6+abOPCe4kKIb5oR5WHyIw3vx2Q9A2u9NXkGa8utn648y,iv:6FyPkiM/ZlP68qibmFHMxN+LU6CqEG4JoqzeflS7tpU=,tag:QpZlFu+Fnpzhw8VspNmYxg==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZXJJcEJrdldscktBWWFl
            OXBFWTM4TXEyTThVRlMwbjdjSGttZ2IrWWdjCk9nVVg5TVRoUHJkMjNoQWs4bVV4
            L0N0dC9Nam5neWhVRkkrWEJlRldCd00KLS0tIHl6SjlQb2VST3dtMFM0Z2txbSto
            bXlBczRpL0dQbXc4WGV3dUtaT0xmbVkKMrNnK3Mjomzm2QzYrd5GeoisJgKFd2Or
            ZSXUF6z2+8lxr5sMaDw/JbpivB6OJNtAk6t1sEJpHIPL4z6k+hvW3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T14:29:23Z"
    mac: ENC[AES256_GCM,data:jE760boTPyd1m6qeByAwpnR38zrZyhjDb/x3w6YdqbgNjsSHy1Yxw3AS5stBbE8ZRvj6eSBcWlhafCiWpVQtd+mQD+QtQjLf8DfNaw16ckwt7F/beaggoiFBZJpo8BQprZ1XLolhNNI1+Vj2XU2tx/SoZrruppp4jJMleKMa4Bk=,iv:70hZQY3WEdXGpvBBIIeDrcyf1UqFto1ZlSv41mrHTo8=,tag:yg9yQtyEFsL0XuHrM3PGjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
