apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt
    namespace: zigbee2mqtt
type: Opaque
stringData:
    #ENC[AES256_GCM,data:XNGi4PlTKcmX1HfsukDfUG/zZF1kx24fFBkCEhVWToVnGg==,iv:+qCyaBZoYPh0u74rmHr6u+H1lnOEAOXfq2St2gOLKNg=,tag:WClhhuZG8Jy2kXstJEww0Q==,type:comment]
    ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:1nz9Htq+1Tug,iv:ZoGree/6L+S2ljJxA0Sosc842D55IkwwVNa73oyGKx0=,tag:95+gj5M8eC9USAhH6KAy7g==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:6IaGmU9sikGCgS7O,iv:wo2Lt6u4hPSMP5089RhfjLDHTAisc/3SS/xMeAqC90g=,tag:bFmZZ8XBt147icsjXVsDjQ==,type:str]
    #ENC[AES256_GCM,data:Y51MNYJAMx4fqje3O3xYQxzA0b5L6SfAia28qhDzBPKcyEZw/GkxG0qdgRSi4ip5xw==,iv:aRlpNxaese5Ndi+b/GfuJB9SDTNeisUkBH1CikAx0XE=,tag:1/D2bzwzu+xtOmnFo/E+bg==,type:comment]
    #ENC[AES256_GCM,data:Ej10J4ErHCKK8u3wW5yivK2RU8nnq1kz5d8l4OD0suO+8v5uu7wgDzEw0E2jVr0ooAsC+aBmE+IBDHd927VTkiqHrasEjyO95A==,iv:E5FMngMqk3Fo8YZvUyqzReqQWR1/zSN40AGgnCo0jy0=,tag:5EKECJeqpOGrBCLrOzcNQw==,type:comment]
    ZIGBEE2MQTT_CONFIG_SERIAL_PORT: ENC[AES256_GCM,data:tzgLvZGLnsyiJrlPpCOM1KBNMU88tfo=,iv:fEKx+n/HIpDha2ABdH8Yu79k42pjnnI4w6QAfNGaUGM=,tag:G/WNm4y+Qk4qwU/viC5Blg==,type:str]
    #ENC[AES256_GCM,data:STXt6ZsmdJjm7ZKuRH9og93xMmXw4KRR37U5/VS7Gn4X9F/Irk/t03LM4fbRPUeBwymn/dXTT4lT,iv:Va1t14aKnI96e6aeVdoInJWH5mlPH6/XhVUBZw1TWSI=,tag:aQarUHJv/8LfeKIgQQ45UQ==,type:comment]
    ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: ENC[AES256_GCM,data:SRd7l4W9,iv:+66psUKpoLSR5zs0m05H+ctGlB3ZyYqLYulrxsg5meI=,tag:lxiFFEvkbdGijL4OwOfuVQ==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZXJJcEJrdldscktBWWFl
            OXBFWTM4TXEyTThVRlMwbjdjSGttZ2IrWWdjCk9nVVg5TVRoUHJkMjNoQWs4bVV4
            L0N0dC9Nam5neWhVRkkrWEJlRldCd00KLS0tIHl6SjlQb2VST3dtMFM0Z2txbSto
            bXlBczRpL0dQbXc4WGV3dUtaT0xmbVkKMrNnK3Mjomzm2QzYrd5GeoisJgKFd2Or
            ZSXUF6z2+8lxr5sMaDw/JbpivB6OJNtAk6t1sEJpHIPL4z6k+hvW3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T18:32:40Z"
    mac: ENC[AES256_GCM,data:EajoFAbDY1/HwPYByn41ZdLsKU/TR6wG0Tidn9NaxHYBOrMiHXmRhN67zjd50FSZ22dWiqwxyn7U6UwXhQ9JF7ZLyAlaVjgGE/LURG9s6wqcig0djxbPeBwg9eIOBjXvcCcH4yi7ysPo3YLJS5IXqaNkQp1SkVMkT9Q0WB5g7i8=,iv:bdfGctqFfaY0smv9+L879WaAbBcoXPpWNRWom2Es8sQ=,tag:d9RctPrN49ROjZsood/6+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
