---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP}"
spec:
  accessModes:
    - "${VOLSYNC_ACCESSMODE:=ReadWriteOnce}"

  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: "${APP}-bootstrap"

  resources:
    requests:
      storage: "${CAPACITY:=1Gi}"

  # Your default for most app PVCs on Ceph should be RBD unless you explicitly need RWX.
  storageClassName: "${APP_STORAGECLASS:=ceph-rbd}"