apiVersion: v1
kind: Secret
metadata:
    name: homebox-secret
    namespace: homebox
stringData:
    #ENC[AES256_GCM,data:IR80wA5mkNf5AnH/MnwaNNPaFRU3kBNKScIDMu0U6RE/vGeyg6LLOalnwJQaG3fVyW7xESEzR8KEhoT8/w==,iv:q/q1hF2VhCvT0TWc7q1oZTl1ZGfWEBJHAmts766D1lM=,tag:0YGXk4+vd8uTlUF6VN4vTw==,type:comment]
    #ENC[AES256_GCM,data:WyqCeHStw/Oetg/S/hbWcw==,iv:36UzqomdWBJpD3Pdy0scpa2/cYqR6YHjDD1ewMqT7CM=,tag:8713uZqJOllhVKxLEAKedA==,type:comment]
    #ENC[AES256_GCM,data:xJEIODtHgeebrLAL/jGwqaU5ZncdZB9Y5DQj7So7eWXWEd/oXi6hPpVYlzzP5daFee7AA38f++aQPYHFknfAhePlLzXUTYLUqrqIvCnlQHT6cSQ=,iv:3fofx6UIERKw8t1WRR0McSYcZQZarCFOGQx/0nBjOZQ=,tag:843yDOuGg+jGs2eeesoA0Q==,type:comment]
    #ENC[AES256_GCM,data:xhNa8tC9YsycBjFPTDqzwEx+dO6zjJhYomzxPlUqiSVY,iv:18tHlXbv6AggZgdR5GdGvduwYCDJlsUkeZoqMtuLUk0=,tag:thuXLwxKlpQRVzYp455KHA==,type:comment]
    #ENC[AES256_GCM,data:SqGyyysHmpnjjagIL3PoGm/Y3nJBnrlfQPKIzlik29jgJ3U3ny/Vyp3rFb+rXP34l6SO1QpZ8plA,iv:slfYUIRRiQUufzmj6AYBpl0QwvS8KVBBMCVbfhUrJ84=,tag:5wVLczJ85e/2F3ko5fViSw==,type:comment]
    HBOX_OIDC_CLIENT_ID: ""
    HBOX_OIDC_CLIENT_SECRET: ""
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDODlvaU5NdVRQeHovcjIv
            eVhaSlBqMEV2WDkxUGFJOUVjQzlsQ0gySFZzCjZNQlhpNVhUd1U5L0ZuQkg1QVpH
            VWpHQ0ltc0FlS2xUUzlpbWc5V3AyZlEKLS0tIC9YYXFiZlBnbmpaL3VCMS9mOUFs
            NnRLNDkzRUF1OEdSQjNWdXdCQWM4bHMK2cEqB7y6Myt3rSo8D0bUYKrSY40P8sFs
            8fGbYOW5AHsXTlI+r9qly5uK+kA4d31rHcYXpro+v9IfDdBV+DkBHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T06:09:47Z"
    mac: ENC[AES256_GCM,data:0RWPKXMOqIjaAxnCu25SlylqYigjSS/Vm/Glfqi+WDJ13X/7eZAWFrs8TYkZT/OYp2O1Hy0XNaWuq4ifvAS6OnYQF80+y6eQH5vRp3yqByKSZaZriXtNUqZmCqK8g/LMKYmzNnSWjSsLT4jmHHKq/BpHj9XNXoQ9Sa9WAXk/HMo=,iv:oIFAnQiu8BStAnPc1mfQjpbxnOxmf0pBMdOTOwypsF4=,tag:CqpOEgb6WH73ZpEaXvlh2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
