apiVersion: v1
kind: Secret
metadata:
    name: homebox-secret
    namespace: homebox
stringData:
    #ENC[AES256_GCM,data:IR80wA5mkNf5AnH/MnwaNNPaFRU3kBNKScIDMu0U6RE/vGeyg6LLOalnwJQaG3fVyW7xESEzR8KEhoT8/w==,iv:q/q1hF2VhCvT0TWc7q1oZTl1ZGfWEBJHAmts766D1lM=,tag:0YGXk4+vd8uTlUF6VN4vTw==,type:comment]
    #ENC[AES256_GCM,data:WyqCeHStw/Oetg/S/hbWcw==,iv:36UzqomdWBJpD3Pdy0scpa2/cYqR6YHjDD1ewMqT7CM=,tag:8713uZqJOllhVKxLEAKedA==,type:comment]
    #ENC[AES256_GCM,data:xJEIODtHgeebrLAL/jGwqaU5ZncdZB9Y5DQj7So7eWXWEd/oXi6hPpVYlzzP5daFee7AA38f++aQPYHFknfAhePlLzXUTYLUqrqIvCnlQHT6cSQ=,iv:3fofx6UIERKw8t1WRR0McSYcZQZarCFOGQx/0nBjOZQ=,tag:843yDOuGg+jGs2eeesoA0Q==,type:comment]
    #ENC[AES256_GCM,data:xhNa8tC9YsycBjFPTDqzwEx+dO6zjJhYomzxPlUqiSVY,iv:18tHlXbv6AggZgdR5GdGvduwYCDJlsUkeZoqMtuLUk0=,tag:thuXLwxKlpQRVzYp455KHA==,type:comment]
    #ENC[AES256_GCM,data:SqGyyysHmpnjjagIL3PoGm/Y3nJBnrlfQPKIzlik29jgJ3U3ny/Vyp3rFb+rXP34l6SO1QpZ8plA,iv:slfYUIRRiQUufzmj6AYBpl0QwvS8KVBBMCVbfhUrJ84=,tag:5wVLczJ85e/2F3ko5fViSw==,type:comment]
    HBOX_OIDC_CLIENT_ID: ENC[AES256_GCM,data:a/9+jJwrTSanpa8w8RPLB9ylsWF0W1uvp1hhWJ9JAwrmce41yyvbKg==,iv:wpcfLIFl9foN0qO41Mr8M8YZPmCzCDWicmTNzRn5w4M=,tag:7GjdCFjygksCJ8Nv4B9w0Q==,type:str]
    HBOX_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:IGZYzQvdZjk5fKu+gCNl21x8CLhBKh6O8/USoClueaFktfP9sT8+CuPiDCTnY2OZUkD9G2kD1qhbabNLgOVvsqZ6niiHySnyGd73y/aRs2GNUbLNdeWG4VWXWPK+Un1yXexg1nc2QH5fBLbNjP0imJUCd/67T05HwgiT4cRBfEA=,iv:z9ZaVfYFn14T0O1kws6sTbN04UJrTQhF+TE+abV4vmQ=,tag:xAe5evVSnFVrimqsQ9OKdA==,type:str]
    HBOX_AUTH_API_KEY_PEPPER: ENC[AES256_GCM,data:II5QgPj61tDdT+S6axm8yAPAwnZhv7loZzle2IhkvmXsOCOXBtHxZL3TrJXY78RklUu5vxsDWGnzSsJcHlLSdg==,iv:73vB15usZq/PRxv8ZSRGJcSzocG2tK3s08wTpbzOOZ8=,tag:wiKT/pZwYYtPSl6PpOof4w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDODlvaU5NdVRQeHovcjIv
            eVhaSlBqMEV2WDkxUGFJOUVjQzlsQ0gySFZzCjZNQlhpNVhUd1U5L0ZuQkg1QVpH
            VWpHQ0ltc0FlS2xUUzlpbWc5V3AyZlEKLS0tIC9YYXFiZlBnbmpaL3VCMS9mOUFs
            NnRLNDkzRUF1OEdSQjNWdXdCQWM4bHMK2cEqB7y6Myt3rSo8D0bUYKrSY40P8sFs
            8fGbYOW5AHsXTlI+r9qly5uK+kA4d31rHcYXpro+v9IfDdBV+DkBHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T03:10:07Z"
    mac: ENC[AES256_GCM,data:8q9RMrQehlaredWTVCBHQXi2fVJzpYbAklz70W7UJie36DWdm6YGA8aAvW/UB9gZoYkdNsJ+su/bvOABmBNV5ZIKiuEmdwkhibty+IOh+HOF+vlLyKQFZPafiHSh/JdLqTPmFHO9BP3oEZSPcm2Y4Ef17SRpOkAuLeSP2ePwmiE=,iv:hWglGCcHpF8J/OBqiCXZnPy/M/PpwFnu7OdTyOs6ePc=,tag:/zsbT2Hnf956tDRORsJwUw==,type:str]
    version: 3.11.0
