apiVersion: v1
kind: Secret
metadata:
    name: homebox-secret
    namespace: homebox
stringData:
    #ENC[AES256_GCM,data:IR80wA5mkNf5AnH/MnwaNNPaFRU3kBNKScIDMu0U6RE/vGeyg6LLOalnwJQaG3fVyW7xESEzR8KEhoT8/w==,iv:q/q1hF2VhCvT0TWc7q1oZTl1ZGfWEBJHAmts766D1lM=,tag:0YGXk4+vd8uTlUF6VN4vTw==,type:comment]
    #ENC[AES256_GCM,data:WyqCeHStw/Oetg/S/hbWcw==,iv:36UzqomdWBJpD3Pdy0scpa2/cYqR6YHjDD1ewMqT7CM=,tag:8713uZqJOllhVKxLEAKedA==,type:comment]
    #ENC[AES256_GCM,data:xJEIODtHgeebrLAL/jGwqaU5ZncdZB9Y5DQj7So7eWXWEd/oXi6hPpVYlzzP5daFee7AA38f++aQPYHFknfAhePlLzXUTYLUqrqIvCnlQHT6cSQ=,iv:3fofx6UIERKw8t1WRR0McSYcZQZarCFOGQx/0nBjOZQ=,tag:843yDOuGg+jGs2eeesoA0Q==,type:comment]
    #ENC[AES256_GCM,data:xhNa8tC9YsycBjFPTDqzwEx+dO6zjJhYomzxPlUqiSVY,iv:18tHlXbv6AggZgdR5GdGvduwYCDJlsUkeZoqMtuLUk0=,tag:thuXLwxKlpQRVzYp455KHA==,type:comment]
    #ENC[AES256_GCM,data:SqGyyysHmpnjjagIL3PoGm/Y3nJBnrlfQPKIzlik29jgJ3U3ny/Vyp3rFb+rXP34l6SO1QpZ8plA,iv:slfYUIRRiQUufzmj6AYBpl0QwvS8KVBBMCVbfhUrJ84=,tag:5wVLczJ85e/2F3ko5fViSw==,type:comment]
    HBOX_OIDC_CLIENT_ID: ENC[AES256_GCM,data:a/9+jJwrTSanpa8w8RPLB9ylsWF0W1uvp1hhWJ9JAwrmce41yyvbKg==,iv:wpcfLIFl9foN0qO41Mr8M8YZPmCzCDWicmTNzRn5w4M=,tag:7GjdCFjygksCJ8Nv4B9w0Q==,type:str]
    HBOX_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:IGZYzQvdZjk5fKu+gCNl21x8CLhBKh6O8/USoClueaFktfP9sT8+CuPiDCTnY2OZUkD9G2kD1qhbabNLgOVvsqZ6niiHySnyGd73y/aRs2GNUbLNdeWG4VWXWPK+Un1yXexg1nc2QH5fBLbNjP0imJUCd/67T05HwgiT4cRBfEA=,iv:z9ZaVfYFn14T0O1kws6sTbN04UJrTQhF+TE+abV4vmQ=,tag:xAe5evVSnFVrimqsQ9OKdA==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDODlvaU5NdVRQeHovcjIv
            eVhaSlBqMEV2WDkxUGFJOUVjQzlsQ0gySFZzCjZNQlhpNVhUd1U5L0ZuQkg1QVpH
            VWpHQ0ltc0FlS2xUUzlpbWc5V3AyZlEKLS0tIC9YYXFiZlBnbmpaL3VCMS9mOUFs
            NnRLNDkzRUF1OEdSQjNWdXdCQWM4bHMK2cEqB7y6Myt3rSo8D0bUYKrSY40P8sFs
            8fGbYOW5AHsXTlI+r9qly5uK+kA4d31rHcYXpro+v9IfDdBV+DkBHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T06:16:53Z"
    mac: ENC[AES256_GCM,data:G9xwg0thCqTBc1NgcHF0BnPvJ1Gui1o+A47m5011NgquT0GQM8YM7Gk+SaGNECkgKA/B7wKx4YhCW2AsMHdQO/4gq637fk+aeY4uQWoFurdYWWJjBxwSADopsLJnN2EAu6voeMAKTdE5fbOcD5ga0e0fVjk7XAzHSUvAVwPiekM=,iv:4qCVKUKLGeYhyEF5lqkoJSXFcraWnDEGxnHq7Vy7Mjo=,tag:onjSyOpVu0Yk2+bwK740Mw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
