apiVersion: v1
kind: Secret
metadata:
  name: ceph-rbd-secret
  namespace: kube-system
stringData:
  # Ceph user and key; create this user in your Ceph cluster:
  #   ceph auth get-or-create client.k3s-rbd mon 'allow r' osd 'allow rwx pool=k3s-rbd'
  userID: k3s-rbd
  userKey: "AQDIIP9oFPXpAhAAzHR+I3BaTrisUFh8f8bgKA=="
type: kubernetes.io/rbd
