apiVersion: v1
kind: Secret
metadata:
    name: ceph-rbd-secret
    namespace: kube-system
stringData:
    #ENC[AES256_GCM,data:j6SpRc3Fsxrff8FMIgyCTuIw9poUWFkSbxtQxcSaQuRsGk3IfBnRUA+6bBfgKaR2Cc628Y2E+pK3Zg==,iv:GXwAQQdgBCjw1tiNLrDtN5pecWXVgnNRx06jX0AGB7A=,tag:oFeahJbSDHfo9gwTqsx7jA==,type:comment]
    #ENC[AES256_GCM,data:4U9lJuBcrxPmOqhCaX/rioZIng2DggKhvEbSMY8HLIUwM5LEXYcIncswr89v0SLYo4g/IiGhPE+tswKd0SZQ25hRs5br8GxjcPOjuGKicZ4x7zEY,iv:Mg+z6y2LX2WYzgb1xBkd/VoUfHoYKQhcwrMLzyv51tA=,tag:2WIqcSGz9ucdr305Q06XZw==,type:comment]
    userID: ENC[AES256_GCM,data:WTqrOwHF1Q==,iv:jpnpiACStJ9/MIKnyZJ4o/JJ2C2y1NlWo4uSsXiN6SQ=,tag:BQyNtY5e4QaiQAhpG+Hlfg==,type:str]
    userKey: ENC[AES256_GCM,data:Q79armRvNBWVu56RR6Z0YVYkc2YGaGc7Od1ocOuVRrfT0YSCBsOwcSOLMWYSkr4j07FPSyZC9twRAF8Z,iv:Qwanb9CUMjW9sd90ZDPYe9qUde/bYZiGlz2q/aSGiHk=,tag:dfdHz/XWbxJx6oXVX2XsYg==,type:str]
type: kubernetes.io/rbd
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTStXVjBUY1JVZE96NDJP
            MURnVWExdU5ZRThNZkdqTEtuZytUNERxUkNnClR0VDVncisrZlYrV1V6YnRFV2hS
            V2pwVks0ZHdBNGdpQjZLSmRoS2dLM1UKLS0tIFNINjhUU1pKRng4dDZqWjAweG5W
            NVlJeEUvSkdzNUpQQWJIeGFCN0R5MVkKrWo+7Rk7T5KoXHQvKgpGZ9cJZ11nbwJG
            M9vGZMThsdZBGjOmYLxcNdCgw5HVyzRA5+VpGXJsMF4fJzhQupJasw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T08:55:16Z"
    mac: ENC[AES256_GCM,data:kpmuz9LMEbjdiDH7kUSWP8EjfFlcC1iMv6DLQ+mlkMGfL57vhdQC5y4fW25zA6OXeRM8NgWiR56mTSX0TPIWARgUZLvk6S24jcGeFvlBm3j6XmE9cALctLqzoo+mI4JhF7eFgXzdDBucGgbeEPRJtaQw2M9Pd+1eyWWPJU1NDEM=,iv:kdXje409cQHX5QyhjXJl4DiQdbyaoSUmC566VWfMugU=,tag:TUuP8/eYItwibqijppAErQ==,type:str]
    version: 3.11.0
