apiVersion: v1
kind: Secret
metadata:
    name: ceph-rbd-secret
    namespace: kube-system
stringData:
    #ENC[AES256_GCM,data:j6SpRc3Fsxrff8FMIgyCTuIw9poUWFkSbxtQxcSaQuRsGk3IfBnRUA+6bBfgKaR2Cc628Y2E+pK3Zg==,iv:GXwAQQdgBCjw1tiNLrDtN5pecWXVgnNRx06jX0AGB7A=,tag:oFeahJbSDHfo9gwTqsx7jA==,type:comment]
    #ENC[AES256_GCM,data:4U9lJuBcrxPmOqhCaX/rioZIng2DggKhvEbSMY8HLIUwM5LEXYcIncswr89v0SLYo4g/IiGhPE+tswKd0SZQ25hRs5br8GxjcPOjuGKicZ4x7zEY,iv:Mg+z6y2LX2WYzgb1xBkd/VoUfHoYKQhcwrMLzyv51tA=,tag:2WIqcSGz9ucdr305Q06XZw==,type:comment]
    userID: ENC[AES256_GCM,data:WTqrOwHF1Q==,iv:jpnpiACStJ9/MIKnyZJ4o/JJ2C2y1NlWo4uSsXiN6SQ=,tag:BQyNtY5e4QaiQAhpG+Hlfg==,type:str]
    userKey: ENC[AES256_GCM,data:2n2iE28amGy/M+vCLT7eQ+TQ62F9dT+SvGxSk4CNfxLJzwijQXW6pQ==,iv:EYl/Mje+piZhWubCvP3BHcxIdXSlzZOwN9AVS7D8aao=,tag:KhiFpZ04ueOQsRH3A6e/Rw==,type:str]
type: kubernetes.io/rbd
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTStXVjBUY1JVZE96NDJP
            MURnVWExdU5ZRThNZkdqTEtuZytUNERxUkNnClR0VDVncisrZlYrV1V6YnRFV2hS
            V2pwVks0ZHdBNGdpQjZLSmRoS2dLM1UKLS0tIFNINjhUU1pKRng4dDZqWjAweG5W
            NVlJeEUvSkdzNUpQQWJIeGFCN0R5MVkKrWo+7Rk7T5KoXHQvKgpGZ9cJZ11nbwJG
            M9vGZMThsdZBGjOmYLxcNdCgw5HVyzRA5+VpGXJsMF4fJzhQupJasw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T02:43:23Z"
    mac: ENC[AES256_GCM,data:CQ4bMBBBUJhAD1OsCmf1Y3l1hx0F/wrwTm0/zV8BGXbvOYMgEJgzr36ff0xZdI2yhRtlHNK/O19a4xZVpOcF5s2AYTiGDTtL74hNVZwmmYGEK/LF0AC89Fu6oqx/IDPojLh/ObWhs5YqqwAxuinhbgZqeLzn+mm/7FqrBcSUfFs=,iv:E5clBIy9DfnVlMejdI7OGEevzrzLl9e3W+uY7q2LEpY=,tag:Hlm3zg5Z36QRn7TBRXJEOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
