apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-rbd
provisioner: rbd.csi.ceph.com
parameters:
  # Ceph cluster FSID
  clusterID: 2b142655-7791-4f14-8934-0ea16121b652

  # RBD pool for block volumes
  pool: k3s-rbd

  imageFeatures: layering

  # Monitors for your external Ceph cluster
  # Adjust ports if you use 3300/v2 or a different config.
  monitors: 192.168.99.12:6789,192.168.99.13:6789,192.168.99.14:6789

  # Secrets for Ceph-CSI
  csi.storage.k8s.io/provisioner-secret-name: ceph-rbd-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/controller-expand-secret-name: ceph-rbd-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: ceph-rbd-secret
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system

reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
