apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "6"
  creationTimestamp: "2025-11-19T22:47:12Z"
  generation: 6
  labels:
    kustomize.toolkit.fluxcd.io/name: infra-controllers
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: csi-cephfsplugin
  namespace: ceph-csi
  resourceVersion: "1446948"
  uid: fec61754-80b5-409e-8488-f333a9ece837
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: csi-cephfsplugin
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: csi-cephfsplugin
    spec:
      containers:
      - args:
        - --nodeid=$(NODE_ID)
        - --type=cephfs
        - --nodeserver=true
        - --endpoint=$(CSI_ENDPOINT)
        - --csi-addons-endpoint=$(CSI_ADDONS_ENDPOINT)
        - --v=5
        - --drivername=cephfs.csi.ceph.com
        env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CSI_ENDPOINT
          value: unix:///var/lib/kubelet/plugins/cephfs.csi.ceph.com/csi.sock
        - name: CSI_ADDONS_ENDPOINT
          value: unix:///var/lib/kubelet/plugins/cephfs.csi.ceph.com/csi-addons.sock
        - name: CEPHCSI_KEYSTORE
          value: k8s_keystore
        - name: CEPHCSI_KEYSTORE_K8S_NAMESPACE
          value: kube-system
        image: quay.io/cephcsi/cephcsi:v3.15-canary
        imagePullPolicy: IfNotPresent
        name: csi-cephfsplugin
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kubelet/plugins/cephfs.csi.ceph.com/
          name: plugin-dir
        - mountPath: /var/lib/kubelet/pods
          mountPropagation: Bidirectional
          name: mountpoint-dir
        - mountPath: /dev
          name: device-dir
        - mountPath: /etc/ceph/
          name: ceph-config
        - mountPath: /etc/ceph-csi-config/
          name: ceph-csi-config
        - mountPath: /etc/ceph-csi-encryption-kms-config/
          name: ceph-csi-encryption-kms-config
        - mountPath: /tmp/csi/keys
          name: keys-tmp-dir
      - args:
        - --csi-address=$(ADDRESS)
        - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
        env:
        - name: ADDRESS
          value: /var/lib/kubelet/plugins/cephfs.csi.ceph.com/csi.sock
        - name: DRIVER_REG_SOCK_PATH
          value: /var/lib/kubelet/plugins/cephfs.csi.ceph.com/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.0
        imagePullPolicy: IfNotPresent
        name: driver-registrar
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kubelet/plugins/cephfs.csi.ceph.com/
          name: plugin-dir
        - mountPath: /registration
          name: registration-dir
      - args:
        - --type=liveness
        - --endpoint=$(CSI_ENDPOINT)
        - --metricsport=8681
        - --metricspath=/metrics
        - --polltime=60s
        - --timeout=3s
        env:
        - name: CSI_ENDPOINT
          value: unix:///var/lib/kubelet/plugins/cephfs.csi.ceph.com/csi.sock
        image: quay.io/cephcsi/cephcsi:v3.15-canary
        imagePullPolicy: IfNotPresent
        name: liveness-prometheus
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kubelet/plugins/cephfs.csi.ceph.com/
          name: plugin-dir
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cephfs-csi-node
      serviceAccountName: cephfs-csi-node
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins/cephfs.csi.ceph.com/
          type: DirectoryOrCreate
        name: plugin-dir
      - hostPath:
          path: /var/lib/kubelet/plugins_registry
          type: DirectoryOrCreate
        name: registration-dir
      - hostPath:
          path: /var/lib/kubelet/pods
          type: Directory
        name: mountpoint-dir
      - hostPath:
          path: /dev
          type: Directory
        name: device-dir
      - hostPath:
          path: /etc/ceph
          type: DirectoryOrCreate
        name: ceph-config
      - configMap:
          defaultMode: 420
          name: ceph-csi-config
        name: ceph-csi-config
      - configMap:
          defaultMode: 420
          name: ceph-csi-encryption-kms-config
        name: ceph-csi-encryption-kms-config
      - emptyDir: {}
        name: keys-tmp-dir
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 6
  desiredNumberScheduled: 6
  numberAvailable: 6
  numberMisscheduled: 0
  numberReady: 6
  observedGeneration: 6
  updatedNumberScheduled: 6
