apiVersion: apps/v1
kind: Deployment
metadata:
  name: riven-frontend-debug
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: riven-frontend-debug
  template:
    metadata:
      labels:
        app: riven-frontend-debug
    spec:
      nodeSelector:
        kubernetes.io/hostname: mainertoo-k3s-worker-2
      containers:
        - name: frontend
          image: docker.io/spoked/riven-frontend:latest
          envFrom:
            - secretRef:
                name: riven-frontend-secret
            - configMapRef:
                name: riven-frontend-configmap
          env:
            - name: TZ
              value: America/Los_Angeles