apiVersion: v1
kind: Pod
metadata:
  name: wiki-js-migrate
  namespace: wiki-js
spec:
  restartPolicy: Never
  containers:
    - name: migrate
      image: ubuntu:24.04
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: db-data
          mountPath: /mnt/db-data
        - name: wiki-data
          mountPath: /mnt/wiki-data
  volumes:
    - name: db-data
      persistentVolumeClaim:
        claimName: wiki-js-postgres
    - name: wiki-data
      persistentVolumeClaim:
        claimName: wiki-js-data