apiVersion: v1
kind: Secret
metadata:
    name: riven-postgres-secret
    namespace: media
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:KogckQROOgk=,iv:wya+FhIWlNmvJemNu0fqFT0jrvD+H2ntm0v9wgrn1as=,tag:oBIV34s7amo1SHk4EVk96g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:YrM/iM2K1M0=,iv:vYixm/LXDF1Vcoq9KpanVuianxwTJmioLYnNe6df3pk=,tag:A3wCMJCol3hIZCI6Oxzzsg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:x0ls8EZ1nW37fcZyECY=,iv:YmWBIvWWeh9rZqfjNfP9SqBPVq/yzJwuUfiVLXzKq4Y=,tag:i6gUdG4Vf6nxXRtGz9QHBw==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoY292MTVCWldyK25mbHdZ
            N1JSNzd2eC9wRVRiL1hKdTl2SnlSUkpJdkNVCjRxSm5zZmdOYjlYUFVJdWduZERz
            ak9hTUpzTnlheUFLTFVYbncvL2RzYmMKLS0tIExLYjJrMzdZK2dnL2dKelExRnl6
            TFIvYU95QVgwUWs5c0djaUhHQXN1SVkKc8OYqf2pD4XAJfKnlAdzuMD3B2FqkK3k
            V0r+rCL4X/LD02biHZt4MC8WwfEI83O3sl0dlWSsv4yjZwUFAfvg/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T22:55:55Z"
    mac: ENC[AES256_GCM,data:K4rYLu2gMaQx1ccyFBflFT9RUExQsvuZ0FQD4IRG9Kgt59cBBPan/a0HuARVwgCW8gezJiCh5g3JMdvqpMdyhI0gfas9VY+TIeVJNsrtI5ZyAM1sjte2xNH/LDd1Ttkd7kbahxgSNoOQc7Q/a9cRurXy9E2s2Aihdq98oJGp34E=,iv:gPy412/4r6UwDlfZohlJoNNi2CmNqWKpjeJRXbatOVQ=,tag:CCCU6w0C42XnXR82RyswyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
