apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media
  namespace: authentik
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: cephfs
# new addition to hopefully fix media permission issues
server:
  podSecurityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000
worker:
  podSecurityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000