apiVersion: v1
kind: Secret
metadata:
    name: authentik-ldap-outpost-token
    namespace: authentik
stringData:
    #ENC[AES256_GCM,data:axY7NS3OThMZ0z1P6UIM6oznKRc/f9t2uDFtNw0FvnhZxF4YVMEORXghRMgjQyBSw1joOJZo1OAfS2rjzCW0Mt7MAuFTq9GLw0BOw0Nmpo0=,iv:Gbz9FjL18IhmHmSyjSgLbfSVcR2567n+2kw4XE9cUcw=,tag:SZjgyXdz7K61blybsjAhXA==,type:comment]
    #ENC[AES256_GCM,data:wMxIHT31+UaAhrBVl0HBkTsQifP01Sd7czvIVMAP1QcgEJv4AfNi93vEdNUS3bFr6Rbhv2xM7wRcv/y9HXho15TuA6qYVrT9rUpzLr64jwWNU6qVaA==,iv:kndtaYIXeDzko5EMQCDN0Hht4zlCWr6dKSUJZy+Hmts=,tag:7ExSJ1Ts48gWwQKTUbu0Mg==,type:comment]
    #
    #ENC[AES256_GCM,data:usYstgHTmoXhCo/6ZcGIjEDZmxDfrP84LHXx4BVRjK9FUEyZKaKsRu4tB3Idal04tmEkakt8ay3bW4Bu6Vuj1hu7GU7rXWz9cIs5QGPbrALo9njTEn40YFbF4KuttJ8=,iv:OwTE9xfxmW2t/xmdmt7Z3luCJcQ8z4dZ5ihPXVQeKA4=,tag:Znw4k6bXgZxVYT5E7XLLnA==,type:comment]
    #ENC[AES256_GCM,data:828QniuU0g5KvATAjunVRfkNjvWCLxS6G6RXKKkhwDfViEygN7FWPMSNtF9T0fsV6A==,iv:oGlOuP0Ak7GrdggaRfw2N6VTnSGz22Otn/htjxQMR+c=,tag:S31qSGUHsDwrXR9WExn+2A==,type:comment]
    #ENC[AES256_GCM,data:Qe34eQE/gZYOSxry4mtnjKafDaHAKNj/bETy1XLPfF+kop8ILmTr8uRqs5yoLABE61aSrtHlPFMkoEYgbXqfBBjmDfqmHPdtY9Ejca0I4S+XiVo8xQ==,iv:BSHFCUvo1nyXSZ/ZulzmfEq86WTkUwSR39mc2X+xcr0=,tag:N4ftLfxuMBZlWKSwnXz48A==,type:comment]
    #ENC[AES256_GCM,data:ROzecZ8Det4UbgweKTx2J/Qv6oogBeB6G7ZDfqgAQ5EP15julP8VxucWkbybesvsKiNhTOK/6BQ83IM=,iv:v2IPhIGVhgVg26vULEJAHxcqBWtE71rSDbVEg+BLGxo=,tag:jwa2M4y8dcFH5ob3vREQkA==,type:comment]
    #
    #ENC[AES256_GCM,data:UNt9uCZyU4FoStDjtyqkR8RDJzxXGK9QqIMbDiUUPjjhIxTpqAgAdoLAUufSkN7cjAcgoYG/AJdLUK6KM3ZXiDPk/kn6OLHtbQZvmcJljpiWdr5Oi34=,iv:YqNEPV9oFcr4d5mtyFEbiyP3Zo5RUSzex36PzsPLjwE=,tag:UqNOOops89UF5Yx/FtK6zg==,type:comment]
    #ENC[AES256_GCM,data:wcqnd5xjvmIRd8DKc9PBTQ341RQMo2n3abx+7u91ja2ei9yWnBd3hl/qlnlbtrgUeSrRW6RBHvsxlfyU0zB8Ke+wik6AKpCRtMPxYkif3doA707lOpY=,iv:dNw+ZQTPONMhO3nGFIf2kDi8A+DvSFtLF3DMKcXGw+c=,tag:O90jvnl8B2F/RyzKAG5CoQ==,type:comment]
    #ENC[AES256_GCM,data:Ktqhs/iEzqYGOIL6Q+MEwEh4EU5p2wuMojPUPutwt9aE/kPJgEpc4hwB819rk8oGOJlFumNPPmEStu/ugkZyvGvr+vuzkc24BmRKcAHpMhid4jeMe0qmbxc=,iv:SqQJB8gBUrsbbvYXUYHryRxmf6GJ5iwhcGmeqtiSe1I=,tag:dccRSi3qfr0mxX3cMfXIIw==,type:comment]
    #ENC[AES256_GCM,data:dT5dK7+A4fMsoeQW2WLzVv9iadXg+7Fg9pUMglgJjdEdajnWq4Ek/w8=,iv:DB1u691ntnxtPRln0r2hfoTHkvL13FEKOM+dNeD6mQE=,tag:4PVTW1Gg3gYbKUq9vLC56Q==,type:comment]
    token: ENC[AES256_GCM,data:Mw+q4bAfEfyjRp0OxmIqVodmP59sciYRU+CZ42W2gSHOVoBxm82CK5hedkxqZHH/xaY=,iv:ihfrzxONbnZID7yI4nsJ6B4MWjMzgQLx34o/kK0MHFA=,tag:CtF53lLSoaPSL4kQjrOs+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0djA4VnVJOFlRYU9wMlRa
            UGRxdmFsK1pmbHV1QnJaNWQ4S0xUbkk4dkZBClJtZ29LTmRRRHA3cjVQcUcwNXNZ
            SVYyV0t1dTM5RHJjV1VYU0ZPTjR6cEUKLS0tIFFEOFJMVjh4STIxQ3FDdmg2N1Bj
            SWoreExxdjVhMHZBTTFrZTdmS01LdmsKJKC6EE3DkZZDzwgLKaFnu4NFBw7y6MKY
            JERyV6QftNEnxTtQBGQdoquZqYczCP4BGrSqgbZ9IrTZBP+YsrdFpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T13:51:00Z"
    mac: ENC[AES256_GCM,data:co58YoMef0esFL3gpfUnAOCuDXI3BwCsDnmnppB1/3ZJHEMNBzqiVlEuDrl8IFObPtBRP4Ik7h9sh3TmpH57SJgLFNwjCrmTNOfVfELbd08PdVXrnyLK103FL387BoYy7Ud09ACPadQf0aAksjPSPsGWGwELhaxl9I+rOCmHTS0=,iv:hU/Q02CdgS03QbdSwJURwvbpJqmvfgP1daNopi65Ydc=,tag:BAKCCm2DFdgaxOKEoF7tuw==,type:str]
    version: 3.13.1
