apiVersion: v1
kind: Secret
metadata:
    name: authentik-postgresql
    namespace: authentik
type: Opaque
stringData:
    #ENC[AES256_GCM,data:OGk8g2J+YpwL+BJuh8FZ93kVGnFnQzi8C+81TQ1gD+ghhO/fUzLM+ZhkZWTGsDD3c1Qjk8m/H7gru4k6CBaCWNpw+mHTyEGk6A==,iv:GrGZjmrFUV+/OL2uOaMSyUF3I+GyAgdwcNDMO+XDIIc=,tag:LoJacYsn2AN6BbxGoXcj5A==,type:comment]
    #ENC[AES256_GCM,data:8b0hgZTkOiE6ftc1MtRJyemS4yxXSDQfKe7k2wR3Wshntxv8bK6vcA==,iv:uEFoDQ4sqBcI6E0YLwr13Z4KEKrGEOVQBCqqOVLMbgA=,tag:4D3Fm+P8XwgyTYlYVa2dWA==,type:comment]
    #ENC[AES256_GCM,data:HQ6X3jFsy78Ja2wU7MQTs50CRrsVXZ5Mcc2STh+4Ostqwe3MC85sGKz4,iv:wVppnNw5AiQfYuZ91vpYk3l7fEccFcf/ObONyyyHazA=,tag:/zXFaQLIGp7rhDOUqGU/Yw==,type:comment]
    postgres-password: ENC[AES256_GCM,data:xIejmanQ9VGkKgAGf8A+0CPDnY8zGNTp4DD4SEcye18lSdLk7Bjdbg53Tok=,iv:yW9n4qIy23XF15BXhotUd6DX5OKIzm9GsAvDwpGbils=,tag:hSDOWEobFP4/xld4JIrdNA==,type:str]
    password: ENC[AES256_GCM,data:Z2V/y4jOPu/s+Wz8F7yHljcypK6pbA+qKTWXSEpHwygnT4n8scmukGnd1k8=,iv:wx1FH6eppTiKKZtni1fWVb9EN34sfxG3s+vXAo+5IfQ=,tag:h0fQkrpSjidzvrVFH4aiQA==,type:str]
    replication-password: ENC[AES256_GCM,data:158xxyFdDJzLkfgIoEXujoIsXI1JiRkDXNWjBA0ANLWTDUo4i7AMtl5LiYk=,iv:4HvqfBSOaKqpMr4PkIFAMOODE7ibEs3JI8oRiAyUbRA=,tag:e/vjQqP5XbP8+hJoLWv+rA==,type:str]
    #ENC[AES256_GCM,data:Bdf8A6U/ZUxLV5kMzWosbbiMbeS6XjLoD9DH7cb6cP3URIFsQetEgLFnmi2+m6G+k3Jl3J7Q77D1YMBOzWl2ZHnoYmbKip/ba2k=,iv:xdHQt2YDVaH+K748YsqjCFmM5/tfWw0cZVJaKnmJWtQ=,tag:IO1MmejHkcOplamOvo1LZA==,type:comment]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:6XXjirDmFgVCUBEpgnWCoQPfxOMj9Tpv3EUKb+Xk/h20oPrsPHSOdDT5Ew13b0wPr7JQP7ssY8Wr4ksMgkLOqA==,iv:LV9gsKam8U30sAp7mh95yWQmpxepl1YiyCrLht8wbZg=,tag:RanH7lOV4F1iNxzXxJeqUw==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:hexgZLkQNjMNJZIL3hFd+NxbFA==,iv:WCMZrprSr7rISb/EXqzyjIPZ9mtTRL4xSaFwm7KfDII=,tag:k/20iIO54jLCW4pi1NdcXQ==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:Fjbs682D/LxCZA==,iv:vIawgC0YSQabPj9Q6q10KbEOJrYiqdhdMWAgMA0fKJM=,tag:K6APfCGv2PJp/RkM0ssOiw==,type:str]
    AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:7WOkA4NUcas61lWaFCc2UaJQBg==,iv:ys/TeGXILdWpQxJjkFKnNvEqVY8E+Tmen3RU3qiKT4I=,tag:h/0wuYD+VsZvrj6RYsvRyw==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bVJNMFdoQkZmWk1wYy8r
            QTdYQWkraWFDSVQ5dSs3SlVMTG1EYmpmVUVZCmduU0ZDb0I4eVdSdjRrOWVPVHpt
            UC83QUlaMDBZaGJ4THlIRFdnNFlMc1UKLS0tIGVYbUY4U3ZDd09hSTNLYU9CMGU5
            NTJiWnZieGNkWXdZbHE0OHlheFl2alkKaG1CneixR78KC7+5ic6nNPmsZkFWpGi6
            nIgH9M0fDizbtGOtRgSUPZcrOw394PXCJV2pNyYjzNhHtsxSu2pYbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T00:40:27Z"
    mac: ENC[AES256_GCM,data:akH7cOv+OAsPUt6hxHnvUHZWwxtZwF2K1elyf7sUSJorTMVknaGappAzxsAx5yEiFMmCzwy8Jzmu85V3jyCMeaxbWYakuN9FF0euOVM3Av1CWFuJ+Mb5/CseKMIOZI0RmynDjmx4VP9aSlcftL+hNCNu571kSEsAbJ9Qr18U8Hg=,iv:u2xIKZ+JcQrPCPfDv8RMhxVh6x42VkMEJXhya1Q+Q3s=,tag:Naq1HISMNQ+NmmC7weB3oQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
