apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: kube-prometheus-stack
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:ZvlCStfWrKa/QfhIugD7/iNTOpc9ErjsB0O5lPz8RTejTh6ghN6euLD/j0lcHwtEYJfDJOPabtVi44Sz3C6Ah1zQDcNsTtHs15L9rc8i8qdJ5cSuGqJqE2kfhMQhf7Gv9PsZGGgdfC2pcqajpHjiNshHyup7O6erPln7AIj41fGb627ytPu6JYLDQZd8hPJwV/pBqLOjERaOM1C5IA5NjzxbgwbECgi4zEEZ5zcVi1GubKD2gZBEZLqn2onakQf6pjBfuiMC8S+gOU9B0m+FIApD6eq6QhJX06MXXnVXRq4SBADryCxL53Ekm3PWssgy9y+TlhQZ9ARBeNSEUavebdpRZ6Nfaa8xGa9M11U5UFJl3vtFZnYJB9VZFVrbga6+xP6Ne5UTlOyNhf44UdXlCo4232czb33yBPUvb1Cmvz3fZVwjo0lTsR+cDpnpcOP7JvIbiD9tbF+/EMQkjs7XFOjudORghQTnfKq34DBDXrA2U8/GwhgFbZgOCvpndcz+2hAyzBMXd7cMNQJqrpLc0oDhnIg=,iv:Zo9RzC+kY42Jh7MwMZZBVUBHbjk85DGb3c+J0S887Us=,tag:5gnFzwMKtWSBzdgGzS5ZxA==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcHBtVS9OTEkxSTE4amJ4
            NHRKM0hxenhhUzJkSlBaUXozbCtoM1ZQWFFNCkZqa2VQejNLVGhLclNMTnhaS0Vk
            VzNqZG5OZXdsaW9kUC9RWHhGdDNrN2sKLS0tIHRCQXdCZk5kRjI2Sm1EeXB6L3p5
            bnl3T2VIMWpCU3pNMmpCbTQzTkthVlkKJZ3TdVMcKyWJNg1YIN30UoA6Oa4Pj5Xp
            CFEucnPRe3Jh5qi1/x/AGleUnV8x8TwbJ8vTyTKNbvMMsSqcWAp2IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T11:39:07Z"
    mac: ENC[AES256_GCM,data:c/WFfN/JkGJzM48TcTnDChPx0wFMRws+DGVdHxVrJgZbVKZqECQysHVUDnvKKoCPxkt2HGnuYasG697r4lwu0eohzXgZcZwCTk0FbsAbBT7sgf+8RTrENI7bfuHg7MwqgkNnYK4QEzIQcJNDsx90ytrvpNU5fuIbDWIRTjhofKs=,iv:3N8kDB5q9WojcMFVJVqxP5MVpo7p6XeP4Bmj7fmP0rw=,tag:h9xnxT6O8TroDbwONh/ulQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
