apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dumbassets
  namespace: dumbassets
spec:
  storageClassName: ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi