endpoints:
  - name: "${APP}"
    group: internal
    url: "http://${GATUS_APP:=${APP}}.${APP_NAMESPACE:=${APP}}.svc.cluster.local:${GATUS_PORT:=80}${GATUS_PATH:=/}"
    interval: 1m
    conditions:
      - "[STATUS] == ${GATUS_STATUS_INTERNAL:=200}"
    alerts:
      - type: discord