apiVersion: v1
kind: Secret
metadata:
    name: newt-secret
    namespace: newt
type: Opaque
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:/bfpumy+/M/okHWtr8f2C1hO0/6Pe7KtVrlAvLy7,iv:+F/+2tvsUI4ISpOZl9P2oknV+M/wImir8a8bN1LVwT4=,tag:b/JsNZBRfMUz7QvDZ8MdKg==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:/BfMfY3tu6tHCeLUldbb,iv:5wn7ydVvG6bajonHSoinrrCp4zcivtY7CUtVzV/SGpE=,tag:naLUz0zQ4RFIJ6yebQUZbw==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:az/XaCndfZY1wwHhtu6pQvsaPqFD+Offn+LDPY/kFUWhyGsGzlAioMFxr6F6weSd,iv:MIZcfWmx8wNVXn16F6mpKg1xvmqUH/f1vnb84yElujc=,tag:BojtOF6cDbqWgo+ch7xMkg==,type:str]
    ACCEPT_CLIENTS: ENC[AES256_GCM,data:DA9SUg==,iv:3JU9yG/8ddH6RJDhsGZ8GHXXJRY+/aXrWouMniSg+rU=,tag:AS9XkppugfjPDR+y2wsT2Q==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdmx3UmxZQ0xnQlFEYmtn
            VHpOeEFFK1RuNFdUSmppV09ZbWFLTDFMZ3g4CmpXQk8xMlorSDNQSVhISzJqejIx
            NGszK1RmUUZuaVR5QWJ2bG53S0FURHcKLS0tIGtxdy9kbHFOcVVaazAyODNCQkdF
            cFRoZnZVWDFJcURHNyttYXJnbWo5QzgKyLw2cdZVMbUzSh2L7KLTArf06voNoZ36
            pjSQniIQtsa/3SA+Sq8T4HW+FSxGSJK+gIhwpJ1cIePtalH5HRiWWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T22:35:17Z"
    mac: ENC[AES256_GCM,data:FfCEM1+RVg84pcKSewJ2FBI94Spr0XFMIPeEs6I3hdxiTiwNKIZ9HUOrd497R0ztPYmxccxgfXkFdp9IqVnFXXPDDSlsN24vp9KIziG46l8FgPKw2+wCtuzSsn1jayURZrnimaS6kEyzTeRSyQJn4ATiC/xy4OypSc9KVze73xA=,iv:DyCWMVdNz+UNFxhHCMDaGmoEjKHPvtHebkZy2RoqgwI=,tag:kBb2vYMcKmqz1ZTc9IEGpQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
