apiVersion: v1
kind: Secret
metadata:
    name: newt-secret
    namespace: newt
type: Opaque
stringData:
    PANGOLIN_ENDPOINT: ENC[AES256_GCM,data:/bfpumy+/M/okHWtr8f2C1hO0/6Pe7KtVrlAvLy7,iv:+F/+2tvsUI4ISpOZl9P2oknV+M/wImir8a8bN1LVwT4=,tag:b/JsNZBRfMUz7QvDZ8MdKg==,type:str]
    NEWT_ID: ENC[AES256_GCM,data:QmtMMJ3RamGd9vsqpvqG,iv:u5Kh5QojgIBIQOjkIQaepZbI/aW5FkMrnUA1yqR6jgY=,tag:HcroZMLz1ZJCC3ia0sXC2A==,type:str]
    NEWT_SECRET: ENC[AES256_GCM,data:YNLOnlfp3qiB1AQ9tFzjhOznxIEXhdvMTp9a0mH9CWuxUmC/unQQ0TgRRDUnoVaA,iv:rLPk5NWRET0nn3mcXoZJKR1PdtutDC0PStczHH8uxDQ=,tag:+pswEz6N4DjGQGV1kDLqYA==,type:str]
    ACCEPT_CLIENTS: ENC[AES256_GCM,data:DA9SUg==,iv:3JU9yG/8ddH6RJDhsGZ8GHXXJRY+/aXrWouMniSg+rU=,tag:AS9XkppugfjPDR+y2wsT2Q==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdmx3UmxZQ0xnQlFEYmtn
            VHpOeEFFK1RuNFdUSmppV09ZbWFLTDFMZ3g4CmpXQk8xMlorSDNQSVhISzJqejIx
            NGszK1RmUUZuaVR5QWJ2bG53S0FURHcKLS0tIGtxdy9kbHFOcVVaazAyODNCQkdF
            cFRoZnZVWDFJcURHNyttYXJnbWo5QzgKyLw2cdZVMbUzSh2L7KLTArf06voNoZ36
            pjSQniIQtsa/3SA+Sq8T4HW+FSxGSJK+gIhwpJ1cIePtalH5HRiWWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T21:26:33Z"
    mac: ENC[AES256_GCM,data:W8MP3iZaHumglpfJPDaIi8YVK4DDyVPIAE7tOdEmEVAuSh5h/kOL3AVB5EHACfqqPVVPlkjYIEIER9v0alnIDOfOvoToCS1gzlyxZF+Fq1mIw+hck6wwoEUKvibVG7LvSExIsqbY3YuP9/cQakUWW87CTNykAF/BjjjjoIqPlmk=,iv:VX+CR9RahFs7yki3hecIwVEO+r3HzQhZAcZW6+Zy0XM=,tag:z/vEOjWFiwl1o4ObNQ5/6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
