---
apiVersion: resources.cattle.io/v1
kind: Backup
metadata:
  name: rancher-daily-backup
  namespace: cattle-system
spec:
  resourceSetName: rancher-resource-set-full
  schedule: "0 2 * * *"
  retentionCount: 10
  storageLocation:
    s3:
      bucketName: volsync
      folder: rancher-backup
      region: us-west-1
      endpoint: garage.lab.mainertoo.com
      credentialSecretName: rancher-s3-backup-creds
      credentialSecretNamespace: cattle-system
