apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ratgdo-logger-data
  labels:
    app.kubernetes.io/name: ratgdo-logger
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 1Gi
