apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: alloy
  namespace: alloy
  annotations:
    gethomepage.dev/href: "https://alloy.lab.mainertoo.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Alloy"
    gethomepage.dev/description: "Telemetry agent (logs/metrics/traces)"
    gethomepage.dev/group: "Monitoring"
    gethomepage.dev/icon: "https://cdn.jsdelivr.net/gh/selfhst/icons/svg/grafana.svg"
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`alloy.lab.mainertoo.com`)
      kind: Rule
      middlewares:
        - name: authentik-sso
          namespace: traefik-system
      services:
        - name: alloy
          port: 12345
          scheme: http
  tls: {}