apiVersion: v1
kind: Secret
metadata:
    name: convertx-secret
    namespace: convertx
type: Opaque
stringData:
    #ENC[AES256_GCM,data:xLkf+73+v7U3,iv:Ss6OvnAyRWWkCdxqh6pP29XOAxpUp1dznbABLQc1eCQ=,tag:hPGJLOkkM125Nxsd4EFE2w==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:NtRKLZK53mQHliJipWAYObqA1CT/R4bAZWsFNl7TOldruyKKttbO9wuVCceIFnG+HFh0anj7me4PQ4pBF+r9NJyEJZ/Eo7NMLxPmpQQ5rogFCyEoUkxNWdjmTPn+8Rs7IBAXaa9EKfQmp5zgcWgubmcpHL9ODfkEIOaI7bnCDb+mg2rWrC1B1POYl0xmMdWlfRZKZadcaWwD5Z6IWMJP,iv:FbPCvw5bFDYDAzwJoh7hXzyryqsX5aSmKFA+eOgzA78=,tag:CyqMWgF6LXRAREdyKOoETA==,type:str]
    #ENC[AES256_GCM,data:mDWq6nZp7fcMjQyLQuWslDg=,iv:siZfhXQO5RrvHoDoGX1gQRzNokcqMiNqssvyMbCbAdA=,tag:lkbLrvUAoiWYKWKETHsOQw==,type:comment]
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:9fUqFwxwv9lpvMM4LCjQDYHD5pX/min+OrgqcmXwPrSyMfNzB7cNabIP/aFSdkHQ0eIZTA9V3j5Hha4=,iv:KapiexnHf17AobPrt6JFguG+r0q7LGKafI8aN/0uNy8=,tag:2ycFBZIZcCROocjcbqNknw==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:DJdIF9yMXk26W9hRc1sdBsFMNxrv3r9N7VcUz0GMOwKLudWh8kwl2Q==,iv:icHAF1ZmC3N+K9hVygPIenK+Ywhjnc/4/oqTXdfE1Aw=,tag:u9FzpLFwEJp90jCE/dkWug==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:AFDBIy6hrK5ya72McocwTpnkrW2hDDdyuTPPFkG2Zw15avAoXyYRzedTAUy7VFTsk+RREZQZdS2vP5yldxHwFlyrvSg29Cksuackioxwh89lnIWyfHAoT4laDA/g724r2SLaftyMuNKVq2cgW6LrqrwaIUbQsMzIg/lzcyTVZvs=,iv:VHodVmgTfZ6r3V+EcAmotICgHmZ2rmLaElAy4zCdxAs=,tag:aopodnHlvLFhu1cJYciGog==,type:str]
    #ENC[AES256_GCM,data:Obqf5dDpSHHY5ZdEUs3yUduNc3TkxhHyn8wAPCX5S2Q5ulauJgP+4dgEsmJzr2pFMkk=,iv:UZnGGZFrn2Fh1x5r8u7eO7Z/nPj3JmT9ErIi3fFEXoI=,tag:PnAwqW3/EJ4PxPNBzDSrPA==,type:comment]
    OIDC_REDIRECT_URI: ENC[AES256_GCM,data:szD7UQgGsHL4HPiJfucK+XWQ+eIzkOYiV0YD3yXy9RmWJg8ATwLblfWYg6UN3s8S,iv:ySyemCWmPNgIzbfHQtO978qlvjFhjjDjAEAq2ugwQEw=,tag:O1E0j70TGPXlugSvc1yLxA==,type:str]
    #ENC[AES256_GCM,data:WSfg8Tf2WZ3TVzdwjss2,iv:Amy7PeWPC8+kNkGzEvnDYlJqbYFLSyhCpKI2pu7/PKY=,tag:c6HmDb1XGLKUKXQBClOW2g==,type:comment]
    #ENC[AES256_GCM,data:9rcpWPVxCmKbvw9Iw39/FVo4O6KBGy2yTGUpfNMA1aMLxGqM0zK75vlI,iv:ztyFBQM706hhQRRmqa+YesVu2ItM+kBF6ge2OSLkkCA=,tag:aAOA1etyUbt8UyB7MUe+IQ==,type:comment]
    OIDC_ONLY: ENC[AES256_GCM,data:O2cGrLo=,iv:Hl1EBgbfz1RMTPRQ3KnBktxVPqgnYy8q5zt1eWM/qKE=,tag:QoANjBqGoRLuEM4yFc5U7Q==,type:str]
    OIDC_BUTTON_TEXT: ENC[AES256_GCM,data:227Ml01VGtFns7/zcQ==,iv:ciHQVNGKrOZAs2WAyTEB4TPpZaCW6HGmtoXSqwpEgzs=,tag:JO8k/qzcNcS7MWaevLFEtg==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5YUdOMndlT3V3c1F2cENH
            MHN5aFFINGFyUk8xYlZyazhibS95S1VKQVE4Cis1dmlqU09rZFRTQi8zNUdlcUw5
            N1BiYi9JaFZLNVdiUW01TVB3MHdRRm8KLS0tIFRDRURVVXZiS1RpVmNwWUZEbkJp
            NnVsZHl5dzRlRjFVUGdwRWNIUDdqRWcKtU8Td5aqbR3Gn3tnk2sSkzljwkXHjF2x
            nJsZc8965ZiusfTiDvnkDg/mEnBdyrV1el7kjBmJgCUHV7eig1uN+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T14:35:04Z"
    mac: ENC[AES256_GCM,data:VRnBq2/aJayRrnP5kAs+0RR9wsxJyXttSesrY5mR8q/4nc/q+4gkO1gJRb/PQt4JwvGN7bE+a2sJ7qnUvuevgtmdAYuLm/GTqeilnNH922yZYa0geNFkh/Twc2Y9VNxxBrOyrdKmWiBW2NV1v4gKIYDGbgqmxEERn1o8BD7PvtI=,iv:hXe/MeXDkKXUxS8pAihRfUqc7c1C2tHG8OzdveJFseI=,tag:/X6yViVrdnOJI+IuCJxIjw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
