apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync
type: Opaque
stringData:
    #ENC[AES256_GCM,data:jka1NE1MKvtjFMiWrHJHAVIjFLt9DmU=,iv:hSzj8coLB+3c6/oeYKeuidXbjQpHILfzlHDPMM0KBFo=,tag:P+F1TduRE2IE12QDx1I87g==,type:comment]
    #ENC[AES256_GCM,data:tx0I7bS60Jk8ibI0LNzP4//a8VHjPl50k1+pZvZTatMdxkoX0A==,iv:oTxpcZbKN5l4UuKp9aemCoWXLSCODxAGiMLZjGxJYfk=,tag:o1NawmU7OlUDFQAQmRDNHg==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:8ZUPvDDiWDwi7zaU8st0NnEOzlUZdD5bCHZcj3UUdpx/phXs8i9F9xCVW+gRc6nhYeXC6PIeHVocwFXLiA==,iv:f9pGi85EuNAhmG0n9+6YXVpuCDIkjHxsl87v2y3nf4w=,tag:zl0RbX4FcHoQV/8qUiSNEQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:fIg9M9BRim5OUhqeg7ykqRmtkZir8oC2ZXI=,iv:B2vX1+rfVjHblr7rLnLXrq6gXjs/b+ZBuq4ZwRqcfqA=,tag:4ySfBuK4YkFtrMX1gXlxmA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:CwWkmtAEZl3vFfMcX8SNF9sJBnoXzXIztsZwF7ScXg==,iv:I52WCakc/570vqW6cYtfihIm46Bc7AB5wkTDcmcCtjc=,tag:PyoIWvt1roxe3wGmCeT4HQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:F5KtbkbKTAaNMyK246cLdjllC1cDVqJwxYhYzdFMOfh5oQ0=,iv:toorViLS6NROoiBI9xpXsxasHT4JvZW6uWEWu2Vkjkw=,tag:jzvkT7sbT/5FilnyadMeZg==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:RrTWuCNipW43uBpbwEgpQ3omjWNihYpWyPIPwqbLGA==,iv:prLV5mU3EIRGWbn1siYLDKeX/bXpCWC7F4vPKaHLlFQ=,tag:7LHUtQgOoKsIK1caLdV7PA==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:x84NQiUgFQhaRkk5BZa5YtVODPw4Kx+bhqjdjKoEhw==,iv:TeL7sh+8vlpW/C95ySHWivG+Q9M//WQHMg90J+3aj2o=,tag:LLq6MYLQghtX4M6aOGuq9g==,type:str]
    #ENC[AES256_GCM,data:9ePGZ/fCIsOLe/nEyFko2E0gUY1OYp8I3bfyuzJBo3LniAv9c+3b+3tpRcE=,iv:RsgE55GWwpK673Blpns/jrTtzb7/SSXF3eLEsxeg4l8=,tag:3lNPj2IZEvdfYlEAXgveMQ==,type:comment]
    AWS_S3_FORCE_PATH_STYLE: ENC[AES256_GCM,data:rCN//Q==,iv:zH/0UmsYnbEr/O1FqPoStG7KymUc4eAJ+NGHPkm/IZU=,tag:/DE0KLrG+dSAEUh3QpbVUQ==,type:str]
    #ENC[AES256_GCM,data:50sKszF0AsiuSEGl/7xPF0nAMtT+NwMhpEd5Rn9Ifdr+ut7Ytg==,iv:EFPdjs8D24cQnf0o9QdMFVk+mZnP8el0tUZ41LbgoLc=,tag:s5bkkk/G+d/31IlqikPvgg==,type:comment]
    AWS_EC2_METADATA_DISABLED: ENC[AES256_GCM,data:KOBr/w==,iv:xKrds/eUB5R/JrVyD4sxZnY4BJ93JCspUv9L9+j8dYg=,tag:EnhX84RaM9MfpsW+D2hNnQ==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aTIrd1N4dDlKTSt5SEky
            d0plOVpTMVNxWDkwTjNNTXFVR1lYZkx0NG00CkxlNnpmblhFbHZIOFNucVNZRHN3
            RjdIcXloNGo1V2VDRW9qdmJLZ1RsSWsKLS0tIHFYYU1Sb1FhaVNVWnFRY3YxbHVj
            N3FUSmZFdkxOaUk5ZmxiVkJnaTA1TzQKSpWSugH2Eo7seHmQxYlfiiLWj6pW5OhI
            BYoz3os3jtuoSPKTL71HWBqg28jg//Ee/TAMvHqQfUXm0fqszFpDVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T05:52:30Z"
    mac: ENC[AES256_GCM,data:9l1m0MlNeFQJs7XYJjLU69z9u6Kp8tDWFrEODYR9mraLzjuHj0KNfpzkgqqVlOREaB7p9F2wiN/pKSGv/nxTc4ZY76cXGoaPa0MHZ7ccaoWMAH3BtezNdnRgbVAQnBfM5dYvbHRSxIfqlQsRZPNRYZ6QSnp+bLZZwwn/8Uvh9AU=,iv:+yawMdMMgUOmsfrkIAiIVQj+4KvYk5ssEP1Qz53FQs8=,tag:IWMsq3Ni/PSOVmDeVfwnPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
