apiVersion: v1
kind: Secret
metadata:
  name: "${APP}-volsync"
type: Opaque
stringData:
  RESTIC_REPOSITORY: "CHANGE_ME"
  RESTIC_PASSWORD: "CHANGE_ME"
  AWS_ACCESS_KEY_ID: "CHANGE_ME"
  AWS_SECRET_ACCESS_KEY: "CHANGE_ME"
  AWS_DEFAULT_REGION: "CHANGE_ME"
  AWS_REGION: "CHANGE_ME"
  AWS_EC2_METADATA_DISABLED: "true"
  S3_ENDPOINT: "CHANGE_ME"