apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: orcaslicer
resources:
  - orcaslicer-namespace.yaml
  - orcaslicer-pvc.yaml
  - orcaslicer-release.yaml
  - orcaslicer-ingressroute.yaml
