apiVersion: v1
kind: Secret
metadata:
    name: orcaslicer-secret
    namespace: orcaslicer
type: Opaque
stringData:
    #ENC[AES256_GCM,data:KSstdZrOcKTDBjVmMHxVj0LIBDW7AQmqKnaOFAfBgxSHiVzwcgE+OuueinJVZrspzVCH+aSUatu9FukqtZRBXPuWBp/X4wOJ,iv:9HqcnQcGnLNyAlG3/Gyd8KythO87AFGr5V+vaLKWOME=,tag:4eM0HMuKJlhYvBvHbcxD8A==,type:comment]
    #ENC[AES256_GCM,data:yK+0LwHDOoZcH+80TWKnXKnFnfAaClxCNShMuS2ufhvcXUibvJXXraybwddKrv7seyCjmuNJR2p2gZjOtw==,iv:bXnNf6Kq+MZfXA5PaydgYxmEkTnuCG/9L1koKY02Wcw=,tag:soa8k7vRvAGyLmyraz9EDA==,type:comment]
    CUSTOM_USER: ENC[AES256_GCM,data:fY7CqvVW0vC1,iv:jnupjg4oOw8DjPonzWP2Oxvlrw5p8qQ1jRQcP2iq4dA=,tag:nmplkOrKzq32g0SKxol22Q==,type:str]
    PASSWORD: ENC[AES256_GCM,data:IEfrIg9a9bk4V20I,iv:Ia6ARi6XZr9FTtWllkX8lh4f66+ssMjpANNiSNC5Eqs=,tag:uTI+PRzPIZI/8Hm97+yuAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZXQ2THdxWG5GQXJZQTZH
            Y0dUUmhSdUwwK2xBZXNFbGQ1OHhxL3MyWFZRCnQwUVg4Y0xyMWZrS1FMWXF1eDdW
            YSt2Y0dJSityWXhZejgrV2JkOHNvOWMKLS0tIFZRdVJDRCsyYWFJRlpmSVBPVjE3
            S1g0U1ZZNVNTYlhXSHF6MVhad1llNTgK0SYJOjBUbYQO8zEnG7NMdjS2ce4RhITE
            OkleN+A4c1RZiEnvDcFDhLKvJ0rcVi5yr/Hxjv1Fz500punL/Zhb0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T01:55:38Z"
    mac: ENC[AES256_GCM,data:g9hskbQlyT79SDdCtG/2KDlg3rSpRvvFNuzFY7sz7q4m9zLhTEXDy3yZoj/+iE2L4slEieY5I96o18DhyY4Gddz0Ax/qHvXfvLEKwQn57j9ukJTjlrhHohuMuLYWr/AEGJOZ1tI2tNbWupKsp5RCoOEAzaEQ6XIaYqqcLHqqdLE=,iv:t9Zs3SBVDKK8Al1M6ABvI2feE2F8uexv8+ELkN6OHLs=,tag:oGcAN1x0Q9GfHqOqDuCcUw==,type:str]
    version: 3.13.1
