# jellystat-backup-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellystat-backup-data
  namespace: jellystat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-rbd