apiVersion: v1
kind: Secret
metadata:
    name: jellystat-secret
    namespace: jellystat
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:OJ0x8gGKDXY=,iv:Zg+u6b6LB3HbVCHGpx8TmA5EF6BIY7oByBD7o3x6QtY=,tag:HjEeyNMMrHg/YjVV6k3BcQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:50Mo9fEi8m0W1bjT,iv:gSdKbU6dcYix60BWl8Dz+qNKLmiXMcU5gFFX904PaYw=,tag:6q01uVWyqFNMAQxCPcAaNQ==,type:str]
    JELLYSTAT_JWT_SECRET: ENC[AES256_GCM,data:6m69ydIBXQUKM3pdzKuy9PxxqfUGnUSUcZxA3qcoWXEHJTMmmAU/em+mmABrjxRbpb2zvMeLNs5Wa86AIT/8Lg==,iv:aJc5ZZRSjxyFcpGvvhbBfPKFQD7OpRQuG4h8W7FoFPU=,tag:IhhB50AV1hf6+BBG68w/bQ==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxd1dqOTl0N3dISzBGUUdu
            YnFKRWI2aXpvU1dzK2pCbUs5ZWR3UXBDV3k4Cmp0TndXYlhSeXlvakNEZjlxQk5I
            YkpJa2FZYU94ZVl2dVRRRkVFMFFmN28KLS0tIFR2UzNYeEI1SUEwSUx0bGlYc3c4
            dFNpb01FS3ZVbGRVbDFic0ZUU1U4dlkKv0ZO/GfWEjfhkmqHhqLTam0fnsW8ZKVQ
            o21Q8+yP3Yt6lcpiqlLfW3XnYSEMZVvwBVkOu9XuwBQbFy6Mhb3GwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T02:11:00Z"
    mac: ENC[AES256_GCM,data:LTUoEHnq389Ujec9I4F5z8hhIKc1kU9oEP5b2bo2lDpmH1XnvZVpy8ShCljfF164uNF91tlcQyZ6OnAaLGnDVphlTALulybp07ekNqL5TUxiSUrDBYRVYa5M8etU8URcOPGH2fx1TvJ3tXcZybjHlbkpAGgbZ5gopyes6adBUU0=,iv:AhPqBP8yZDtULhNVg5lnewgvsHFAVLQfteSdB7hAqu8=,tag:1fMOX15gSzkE/aXbEWMJHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
