apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellystat

resources:
  - jellystat-namespace.yaml
  - jellystat-postgres-pvc.yaml
  - jellystat-backup-pvc.yaml
  - jellystat-secret.sops.yaml
  - jellystat-release.yaml
  - jellystat-ingressroute.yaml