apiVersion: apps/v1
kind: Deployment
metadata:
  name: huginn
  namespace: huginn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: huginn
  template:
    metadata:
      labels:
        app: huginn
        app.kubernetes.io/name: huginn        
    spec:
      containers:
        - name: huginn
          image: ghcr.io/huginn/huginn@sha256:d316d64c02723430bf823f8e1d235f52c4d6f4dd80678d427c8fbdf98a49f011
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          tty: true
          stdin: true
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: huginn-mysql-pvc
