apiVersion: v1
kind: Secret
metadata:
    name: cwa-secret
    namespace: media
type: Opaque
stringData:
    HARDCOVER_TOKEN: ""
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVlJSTEJIbFJQM1Nvb2Jo
            NENncVZZTGRrc0F4QVIxcVd1Y0Q5TW1HaGx3CktYWXhMSWYwRmswTk1FS2h4NEVF
            NGVieDg4dEZLcHFDTjRtTmE1YVlTTlEKLS0tIGxybFF3eTlHNU00ZFl5Uzl0SnZi
            SEl6Y2RhY05oS1BlT0pLUVNETXI1RGMKq+6WiaDFoLoAIRr2Z8agVL/oesL7hYfM
            flh/SsqLX1FzT3AsOGwOTCE3PmyIph9xqqVujprwpTJ6zDfPbUSraQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T19:39:06Z"
    mac: ENC[AES256_GCM,data:1InP+6RS6usoKhR94+iN3L5zki3m1RqrU7Fap74KRu608ufPlLgcdinMhRLGNgM4i+4K82QXG20G67Fs+kQ33qwy0S6bfaAoeaI1DOeXQm/6xPZ2Gjhocn9uddTqWAj2ivlYzPzWYAVAwt0FO2wsXHik8C2/nFfMT8HHyiGP77A=,iv:3HW9e0s27l4U4pPoiOPSfyTtgS1241MW16cmUoOhK9A=,tag:rtdCv6pf8aU/0zV00EaFoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
