apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cwa-book-ingest-cephfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cephfs
  resources:
    requests:
      storage: 20Gi