apiVersion: v1
kind: Secret
metadata:
    name: cwa-secret
    namespace: media
type: Opaque
stringData:
    HARDCOVER_TOKEN: ENC[AES256_GCM,data:l+lvnPUKHwZoU2qvOBv4biHTS7OukCDbokmZvmaHIIpzrP0oIQ6fJgTOQvRfkXRnnz9TopQ5Kdl8jz6swbQDsJrMMUbWkSacUIaIQVV2YYyeG1h6/XsVI0e4BF+dJOVDLxtp0Csxpakqyp3RCP97fQYOb8L+Pe+BluAXLesNL9682N3/DHdZ1ykjmNUMZw0HCBQRoCJLsymCZyjK8+HR7MM9XHPcgUovH+hQjTUDHkdB5PmhJWWVICPzBtkU9F3ybKVGtY2pNNMNyTcrtZO7vaBMkEplqURdO2SxxoATObeBtWn9IpcWp0T8GPpa9hMR78wnSDe18bxkGwikRjrK2PUzZufM4dsF6gdqLUqgIm3Zab0lGjO469R5v+zmMVz+v+Ss58tWKOrv1CDcpkckNeUtbdtmKZy3vva6MVu0N2Gh5ra9Bhu4J/r6IX093QN7gCddogB7pB0ymjIAI//jr6WM+xTgGy0Ozk0eCKH0XfvsJTkLw0xlYwA917QKYLzxO4dS9prX/I/mOjTgK9QacyqwePU2TVMSU8JBT+e+uyxdRxdepaezg5gb/7rix8uyT4xRtV1jRvBHxByRXXYZCeZ9JeONwMvcB0gdmJaML2JSAOFqtOeMQ1/d+g92a8lChzRFKqruS1gbzSf4lmTZ1HAJOVcCiYH/TjK/SI1NxYJSLC/1jwencTV/JTdP9i79QjG4+4rElnAquE1V,iv:5kWZWHiBeMCSv5z8/pJHdYQu9ozk0f+FsMIKZFjZohY=,tag:B2TuwlB4atB2FxYkDqopPA==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVlJSTEJIbFJQM1Nvb2Jo
            NENncVZZTGRrc0F4QVIxcVd1Y0Q5TW1HaGx3CktYWXhMSWYwRmswTk1FS2h4NEVF
            NGVieDg4dEZLcHFDTjRtTmE1YVlTTlEKLS0tIGxybFF3eTlHNU00ZFl5Uzl0SnZi
            SEl6Y2RhY05oS1BlT0pLUVNETXI1RGMKq+6WiaDFoLoAIRr2Z8agVL/oesL7hYfM
            flh/SsqLX1FzT3AsOGwOTCE3PmyIph9xqqVujprwpTJ6zDfPbUSraQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-24T20:02:53Z"
    mac: ENC[AES256_GCM,data:jWnahrS7Gx8W1p8TIhjwnPE5AWY7rQdJP593QGOvVSe/2gUVvQbMSIXmPPjrlonceY05xTkRXbUB+XIKGgktHFZ1Uz93ZgblF6J+Cu41xLbJjS0NRVQ3iA/0FkX1F5WVk1hhjjVEfgAgA3WOyMq3mCnCAHRHaN5e9vhwZ9kWVlw=,iv:R4dywOxQKYwyXXR0CgJF5vRnzjCeav+teXcs2qxm9SY=,tag:weDYRZxH8AiRT578hQVzXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
