apiVersion: v1
kind: Secret
metadata:
    name: paperless-oidc
    namespace: paperless-ngx
type: Opaque
stringData:
    PAPERLESS_APPS: ENC[AES256_GCM,data:MRh8tdSZ7EA9BUowLju4UC3rDEp9g59EGDQc/IyaxDOeWGbo5PIwX0c/lmmAxg==,iv:JevqJgiiOFM30ishWPwlmWEszsCJcX8VmUAGSZde5x0=,tag:mitaovj0BCTO3hbSRQGv9A==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:GKG0an/QKLnLijXH5ITGF6mSLkdAQ2Ep1dqCuVCHQt9P67cwlNNaH+8MjBWUUp2V8e8eabhL8QuXpayIJ0quK5QZiEPOZ+W5dNZFUZNR0IwXzbUAbM1tZLKz5nH/eP6kxAb9+YJ9YUkg0QqbWTjevyf8nX6QkWGCBcNzgGjA+Bpp/fOQTcODAzmylX1zEPVGvC9rLqD7U+o3hXcnu+WfrlS3bZeYfCZYbATEBbnimFV/LE1yKALcqir4HdmWezXrtXy6xijZwUktwtu4b4mGi6foJ6y90gsS7U9r6xP1LgJUtn6DJqbR4zYc5xyvOEO31Q3lL2hwoH4CHZIfcB4S1kUMCNZXVpU5yaRmR7cF3FLHkonu2csCrLLwjNeYaR1M7C3FDHFniW6T7tk+OPeXYT/zAzc4AmJDTU2TZsRnvt5adg3PiW413oby5+MOyDyQfGibuja2M5/vjoVhV9kfYFSlQHG3jBbRUFKGkpq7WjbhmRvCx4v2mCVK8Y1QzxxpgRgfQXQ4Ty4P15mbU/6iA1uhx1wilvteiVJsFxI8tLJ/mA/r2R3ReNxJwodx1r2R4XZsAstPBjLgDpgymyGJCWvK/SThMBDoBnPUtdSIRTkpbWzxrrQvPZm7ueuau8aPx9qQ/Rk3c4VqnQ6v83t31TfN52XTV8kYYdGcTrto7nT9Zy/S9iflHHuImGpl0pfMaMK20dfuvTPfVkapXFazv5mUY8YDfPFplQJLUGsiHtPrhF8UJxqx5oZvH36RdWaBOHTiM+38MlnioojTgXS00PoclxZIamHM2/Rw235VGysZ+U3N,iv:AixSWoZNfLXamC1NaQHX/B/OYSvcZ2kqrnJeGnGTEWE=,tag:7/8DDys2WdqGG8kxpRubGQ==,type:str]
    PAPERLESS_LOGOUT_REDIRECT_URL: ENC[AES256_GCM,data:aTwvSyVvnJV/naTPptyG2G+9lgkt67uDJgP3emknU7l2kHsCoowhUGb409SUjzBteT16laTszyl0nne1hV03SVN9UJkV9890s5aV2w==,iv:bh6BzmYoQitJGUKzw8X9h4z85j6ZK/6z8T/qFjI9Rrw=,tag:BBoFXqvMfUFDdSIR/GL07g==,type:str]
    PAPERLESS_SOCIAL_AUTO_SIGNUP: ENC[AES256_GCM,data:tGllrg==,iv:nyjkQzH9vdgGfhLwi/a797kWYRUhOp1u/t88Z0BuDCE=,tag:/g7GyaYlLOi52GXGXJK89Q==,type:str]
    PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS: ENC[AES256_GCM,data:fooocg==,iv:9am4vN4CPSh5i70GVjKwpKZPGQANpfVZOn1cg1MkZQ4=,tag:8Jm6rUnhs7ablfjz0FCftw==,type:str]
    #ENC[AES256_GCM,data:VoByvAvlPSHql7DdeZyqsb3CTnCMfTW2SvA=,iv:4FQMb6eOEpIMR0rCqldM5kxccVBKmrOHJBHQvuIRdbI=,tag:K2ATF5gWbaOlDSvJ3vqeag==,type:comment]
    PAPERLESS_ENABLE_ALLAUTH: ENC[AES256_GCM,data:d6mwtw==,iv:XCaDOflCEs9oyYqqq2LsWH4IFmqc4oTLFWziYLgGK7Y=,tag:eJSy/WwBbuDD8tIkXQiKiQ==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Z2RNZmd2L25pRUphUTNY
            UlEvekZvVjk4TjB6NTNZMndoRTJvbzdEYkVVCk0zMlAxWXFSMXp2ZWRVOG1QZVhS
            L3NtbWIyWURmUDk2VTlYU2NsbUdUTlEKLS0tIGhEVE5oSkY5RG1OZGk0ZHR0Sits
            amZyK0lTQVk3bGx4cTl5Y0ZZSHRXSzAKc7AXFRiLD/CEA8CEBN9KrEHb4O/UI1Xo
            +UjOw/P0abQdldNGiUXMKJpvfe37t2KYo61xi0limgVRiYnO0dLjxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T11:38:22Z"
    mac: ENC[AES256_GCM,data:l2d1JwHAvkG5JbpjJ88bmIvaJxUrCZqa3w5W3Oc6BzxAAuaGNT0nzaVjkkftXbi5grhDhvNa3E80oJAuL0SYeikZm0gIPpAQNYlhMSQQtfkmqCGbfs3UhUJy8FQpumvHLLowy+Obqz3+OMYPL4SefMfSm4hsBunoTKuy6cdAKLE=,iv:93ajhbpRx8VtLEKOeqYx8cPcMgsLFu+F5o8gIEBs44s=,tag:ac4/KYkYOU3C4uoKgG4BUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
