apiVersion: v1
kind: Secret
metadata:
    name: paperless-oidc
    namespace: paperless-ngx
type: Opaque
stringData:
    PAPERLESS_ENABLE_ALLAUTH: ENC[AES256_GCM,data:d6mwtw==,iv:XCaDOflCEs9oyYqqq2LsWH4IFmqc4oTLFWziYLgGK7Y=,tag:eJSy/WwBbuDD8tIkXQiKiQ==,type:str]
    PAPERLESS_APPS: ENC[AES256_GCM,data:MRh8tdSZ7EA9BUowLju4UC3rDEp9g59EGDQc/IyaxDOeWGbo5PIwX0c/lmmAxg==,iv:JevqJgiiOFM30ishWPwlmWEszsCJcX8VmUAGSZde5x0=,tag:mitaovj0BCTO3hbSRQGv9A==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:apfAo4NiSnYJFOeIbInAJy7q7GUkNVrzPXhLH8YGR3+i9xcO+bVgBIXNN5Gy8a3jb29ls1p8qWHmojROU7DK0D6q0FYi3FGfqTyUFQM/RQDjPj/fAtqPWieZPD92USyXQBO4A2Bx4zrS4+Hm2RTlFVHAG+2QLQnIw7kBp7nTcgZ0+JAxgyEbBkK2vdod+aG3r2mXazWVWR45XfuZyt0BtheMAWd52jjyxDwvdMKrEuUXQt4vLbuqvn5EOGhcCG0qNjM8PE+ovL/BM8pq0aLKA1CPKgo+wlm+lEgSsvZHwU9l88HH5Sz/03othTl/ypytkRct95tDbl0aCQZDHeTbFg6rLVraE0V6kyHSkH39+BumK2OEjTUw2PwjeEqTY0Ju6xCKF1jo0a8bTYR+i70bHKBrgyG5rxbRoDEir3XkJhHBqV+s/sUSQTnecDgMYFJQVdTw4r2HPw1YmZI7Z0YJlN+ChZEjbSs8tUk4ljJYDc5iInjxxgNXL/Q7p852/VBeUugn5fOMZ7MxbQu7sMSZKIesB5M7W88YfYD6GcqyyJLjB0mnY75Sl/dKW9iQxZEYbwWd4CL+h97fbLdRLO9kY0yqYcT1EydZKjVarw3tkT1toXDvCDrBZiAstD8+QQMEtCHEwJICEnYvviFQmfv32+ivwQoR4rASfAWb5gpB8qUiRpaTQiZvYTrhOSpV0gnSZMQX0aiBim1asjUN4R9LLFtggttcgUrckDZUSbCXwkQIZyuvt6Pa25aVjL4MlH1uJSzTRTet03WvIf1jdVH3J/Ll7ri9c3uWG01Mr5uxvJHYe4s=,iv:p2CuHfyIcq59exN5w1DDj8PrZqvfzffgW/chYz2LyTs=,tag:gXKrzWH5Lw8T7dlua2hseg==,type:str]
    PAPERLESS_LOGOUT_REDIRECT_URL: ENC[AES256_GCM,data:aTwvSyVvnJV/naTPptyG2G+9lgkt67uDJgP3emknU7l2kHsCoowhUGb409SUjzBteT16laTszyl0nne1hV03SVN9UJkV9890s5aV2w==,iv:bh6BzmYoQitJGUKzw8X9h4z85j6ZK/6z8T/qFjI9Rrw=,tag:BBoFXqvMfUFDdSIR/GL07g==,type:str]
    PAPERLESS_SOCIAL_AUTO_SIGNUP: ENC[AES256_GCM,data:tGllrg==,iv:nyjkQzH9vdgGfhLwi/a797kWYRUhOp1u/t88Z0BuDCE=,tag:/g7GyaYlLOi52GXGXJK89Q==,type:str]
    PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS: ENC[AES256_GCM,data:fooocg==,iv:9am4vN4CPSh5i70GVjKwpKZPGQANpfVZOn1cg1MkZQ4=,tag:8Jm6rUnhs7ablfjz0FCftw==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:uan2sEp7j5r7KbwdlDKPw3gLx48Q+PavX16+PmAPSvS6h6SjazWOCMVCazTb7t6ydJr2lO+YgPpLEpLWP7O0Mw==,iv:z3x1f43YMZLkmNppilPTLsMzMEcI/BHBkdvnKoB3JI4=,tag:LKWs4Aw30j2SoJSu101mcg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Z2RNZmd2L25pRUphUTNY
            UlEvekZvVjk4TjB6NTNZMndoRTJvbzdEYkVVCk0zMlAxWXFSMXp2ZWRVOG1QZVhS
            L3NtbWIyWURmUDk2VTlYU2NsbUdUTlEKLS0tIGhEVE5oSkY5RG1OZGk0ZHR0Sits
            amZyK0lTQVk3bGx4cTl5Y0ZZSHRXSzAKc7AXFRiLD/CEA8CEBN9KrEHb4O/UI1Xo
            +UjOw/P0abQdldNGiUXMKJpvfe37t2KYo61xi0limgVRiYnO0dLjxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-12T04:02:06Z"
    mac: ENC[AES256_GCM,data:y2a2s3SEHavCCssnO02+E7ZCsZmyneH0w4glHHRC3HonWrH3R75Vh218WBhcPGM/0AGonH800yakV3ACMvg+zpyOFwa9Wm0wZvreYhBzU9ryDN82n/4QUuXJ2l3Qhtn9ijmx/lmU/5wEO7XkyGtxY1NF2R/HzR6LlHBKCdia3BM=,iv:FqPLywdAgs/TWq9Wl/YgcRdl31YGLfe6kBnx+63SGtk=,tag:mkzPiKdSyOsamg0Eo3QlpA==,type:str]
    version: 3.13.1
