apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie
resources:
  - mealie-namespace.yaml
  - mealie-pvc.yaml
  - mealie-release.yaml
  - mealie-ingressroute.yaml
  - mealie-sso-secret.sops.yaml