apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
  namespace: mealie
spec:
  interval: 5m
  releaseName: mealie
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    createNamespace: false

  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v3.7.0
              pullPolicy: IfNotPresent
            env:
              - name: TZ
                value: "America/Los_Angeles"
              - name: PUID
                value: "1000"
              - name: PGID
                value: "1000"
              - name: BASE_URL
                value: "https://mealie.lab.mainertoo.com"
              - name: ALLOW_SIGNUP
                value: "false"
              - name: DB_TYPE
                value: "sqlite"

            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false

    service:
      main:
        controller: main
        ports:
          http:
            port: 9000

    ingress:
      main:
        enabled: false

    persistence:
      data:
        enabled: true
        existingClaim: mealie-data
        globalMounts:
          - path: /app/data