apiVersion: v1
kind: Secret
metadata:
    name: mealie-sso-secret
    namespace: mealie
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:1tTh34LJaCJvYA3hDqaii2PSUX1581K3NcSDveWPzuGuoCb12hUidQ==,iv:fVYC5LLIy3FQHK67tLZuWnbvpdBP4rZL7xDr5OkBLCs=,tag:ucxdiJVpX1TkjlGbj44o+g==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Lc1IwLOrThisQniTUKwIZWBwot9xxlNL5wjPMmwp0gO404BIrARhhQ00kGF25HV2uqcaEWLweQGu8p9VqGe6HnrDXd9zD6wODVZpgi6+aLuh5xG7BRe2wrydaph5QRRPlh+kfCDZL9E1b2ypk6i6XMQYl6yoLP8FpyFp521Md24=,iv:RYgAqUxoXb5ioYZI0EIdq8rUC8PqKZuQ31TMokM4Itc=,tag:hM5SFVeWxMjZVkyLyBQyUQ==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cGVsVnZDc0w2alYwYytw
            RDBjNG9vUEhnakNHcTNGNEp0eStxNUhNQ1MwCkZ1akhkOTAvcE9Qam9Sc3Z4WFE1
            cEIzRG5EUkNHdlI3RnV6cVA5cUNIWWMKLS0tIEpvUmdDZzhpSFltRm8wNkJVZ2li
            aFJZVXlBTlBWekUwRU5DYWtPR1VuancKGR11tFbql0UGBVyrBqalpfks5pNDd2fo
            VftBv6Z3noA2RJWx0c3Rbqv6SYqeKHYHaCpAz/jyGzI0HtzRB7z1jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T00:14:31Z"
    mac: ENC[AES256_GCM,data:CU8Rn70/1sn5pZ+oNWJfhJk4sdtjGzdffySCzrr69y6VHmVr3Zd6l+QBtzU2SwtLBZzmv6YcmGcCSVcj2tpD4H1IPZ/mKU0r1pYhT0KFhDCF0EPheVQFAjKJKmrQ2lr4ir0WdbWDgpHEWt8l+gh+0WxxaItAX1Rpvkt7ZHt4pP0=,iv:1qK1tNIVlvdQR6jujppJU4n3pHBq4cnoaaEJJQSNNt0=,tag:0nrdTmi1sNGqe/jjS/XZ+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
