apiVersion: v1
kind: Secret
metadata:
    name: meshcentral-secret
    namespace: meshcentral
type: Opaque
stringData:
    #ENC[AES256_GCM,data:0hPGB6YOJp5WDsZig1tXD5pQLebkylW73SXBmEHELRxwcfgE++w/7gPyG0AMUacne1IQi0ClXQ7YcD3ybOz1pvTRcy2QOITw8GE=,iv:UDfBNr5lH8/cb6btoxXC0Eu7d0bIvdhffPkAHL8CsVU=,tag:BAmuaqFz6uIvxcsIyKW88g==,type:comment]
    SESSION_KEY: ENC[AES256_GCM,data:ZhjO2WqVh47ho3Z8eUDNSjrEiUiJxVYKzUZrzLNHJnf9Y91CJkBrHn3B52+4pAW/JWFI9n/t4+wqvCM3GqBzSA==,iv:nK4NcPP/szGTDUw14VnLTRondkKjPzfyU0Q8DY3x0S4=,tag:6TKWy/pIgKomO2ipJiGmZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnK3lBaGRBWE1ZOWJiajdO
            Z3NxdVI3SlVXcExlekdDMHdQZmpQNjVtSVVnCmh3L0ZrTjB3U0d5TlNYOFVvVWRs
            dVlaL2NJMUt6RDZNMW00QU1MdzVFVjgKLS0tIFNmdEpOUU9MNStlV3BBYzhPSEVF
            cXR2REd0dmxnbzlpdmVIdU5ZNFVCRjQKek0AfOZ9xTrC8WLWUbSdzF0mnJJ8wCc+
            n8m2r1SxZMsPVh6Hne0JBAiU7NkSyKAS9HI5YnPjrs0JDfh28/uhaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T04:53:22Z"
    mac: ENC[AES256_GCM,data:Z24tD7dw0yjj8Nf6D4VboriMRFXHXtrbLzMm/445I0m24UcxzZPZ0ysZ4Ev2Lsap/iCpIE19cSx0g21hNUQdJSFXxUzLChyNSsii8827nyUP5Q8U9U8y9mdrzfXOlXrI+n8OTqwWky+B83ravBsBShCE2aCQLsQpZCvuDowSDkc=,iv:bBmXfv6HRD0FM9ZsFQ41qmO8WdVwifUtTp/wPEZoTR4=,tag:aapMAXw3z0+YbJY+iZQJSw==,type:str]
    version: 3.13.1
