apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt
    namespace: zigbee2mqtt
type: Opaque
stringData:
    ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:1nz9Htq+1Tug,iv:ZoGree/6L+S2ljJxA0Sosc842D55IkwwVNa73oyGKx0=,tag:95+gj5M8eC9USAhH6KAy7g==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:6IaGmU9sikGCgS7O,iv:wo2Lt6u4hPSMP5089RhfjLDHTAisc/3SS/xMeAqC90g=,tag:bFmZZ8XBt147icsjXVsDjQ==,type:str]
    #ENC[AES256_GCM,data:tzz5Zg5a3Tp/MXwOwwNsEnkUIpuS32NrB2ELPli5DSpHEOYlHsetz/MSxy9EJjIqisk=,iv:7k87Cqxn91Y11JnlHFYX74naD77MDuR7x49ZiwR3sGY=,tag:gRe1eyHGMLVEGKjBZnV0aQ==,type:comment]
    ZIGBEE2MQTT_CONFIG_SERIAL_PORT: ENC[AES256_GCM,data:tzgLvZGLnsyiJrlPpCOM1KBNMU88tfo=,iv:fEKx+n/HIpDha2ABdH8Yu79k42pjnnI4w6QAfNGaUGM=,tag:G/WNm4y+Qk4qwU/viC5Blg==,type:str]
    #ENC[AES256_GCM,data:w1KEZHneCDwsffL7ChKVde9IZS1/ZMSo3pQjF9c0myM=,iv:QX4stympAYSwtO6uQ61ce3l8UOrzf2dpHdKV4o1eXd0=,tag:aHzJglsRqBPPZnVEfJxnMg==,type:comment]
    ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: ENC[AES256_GCM,data:SRd7l4W9,iv:+66psUKpoLSR5zs0m05H+ctGlB3ZyYqLYulrxsg5meI=,tag:lxiFFEvkbdGijL4OwOfuVQ==,type:str]
# Optional but helps keep MQTT tidy if you want a specific base topic
# ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: "zigbee2mqtt"
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZXJJcEJrdldscktBWWFl
            OXBFWTM4TXEyTThVRlMwbjdjSGttZ2IrWWdjCk9nVVg5TVRoUHJkMjNoQWs4bVV4
            L0N0dC9Nam5neWhVRkkrWEJlRldCd00KLS0tIHl6SjlQb2VST3dtMFM0Z2txbSto
            bXlBczRpL0dQbXc4WGV3dUtaT0xmbVkKMrNnK3Mjomzm2QzYrd5GeoisJgKFd2Or
            ZSXUF6z2+8lxr5sMaDw/JbpivB6OJNtAk6t1sEJpHIPL4z6k+hvW3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T18:46:16Z"
    mac: ENC[AES256_GCM,data:z98VQvnuQJzZ8ZcsolvgSILL62o98D1D+8OYWbi28OHVVqOayp8KirADQIXZ4Kg6P4lVfQJHzI047ts/Y0bapcBzRyfOmnvzi3EAAGkWAD/IbxH6s64gdzv2s1bYiMEFqLByIClC4DfBFdOSlSjmzwQDIWsCfedMZnqit/8gcWY=,iv:Ykvz6VnDj4Sx2Wp7+dJ5s33ZoYxiZECebeYvA3BRWnc=,tag:5aE/pc/DGNwXPSujDw+PpQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
