apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opencut
resources:
  - opencut-namespace.yaml
  - opencut-postgres-pvc.yaml
  - opencut-secret.sops.yaml
  - opencut-release.yaml
  - opencut-ingressroute.yaml