apiVersion: v1
kind: Secret
metadata:
    name: opencut-secret
    namespace: opencut
type: Opaque
stringData:
    #ENC[AES256_GCM,data:VEhR2Z1GWqR8,iv:dlsrXa9hXI7z7lxTohW5g6eL3/uZqtSsyOylj3gCOAs=,tag:EWfIOCAc0Ypd3zXLsnn81Q==,type:comment]
    POSTGRES_USER: ENC[AES256_GCM,data:aq2XfxsGUw==,iv:ndE/YEyU3dM2f4KpsPs/hy02FRKcc5tl/4QHxVbMAF4=,tag:M7V6MObBuyvMKaVDsnvWZQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:sin5KcNJ0wbe0DtKHIet7g==,iv:fNBLQNF7xNO49Gz7KipGJ/icdy1jOpzMgpnZVmzBQLE=,tag:DAFNCMMhrORdvy1m94BWPg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:MjAJs/raLA==,iv:5I6JGyRIiSXO2ydACldHxIDfw2oDc/Fp1lv+v3Q3/eM=,tag:4URxM1Gios593EOT11QpdA==,type:str]
    #ENC[AES256_GCM,data:ixbZFQK92R4p,iv:4IIgwMr2PgVild/jV2lQQlhnrkvkUpqWnAw9cIi/WlE=,tag:ZSimFigBigv1E5cOc/P/DA==,type:comment]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:gWNyyn74OI8fO5GgdE0odtnE0lO4tTIjY019L35FacqUW1tIQVhymth462zP/l6vLo5OljIOwy2TjwoOQtBh+w==,iv:wi+slVA4S9SgsCVUaf5jRxfo6woa1C+BuiqxKPSVFe0=,tag:50naZAo7p7Qkv9F2jt0xeA==,type:str]
    #ENC[AES256_GCM,data:aqUDn+HaUi6fbDx4YEWdip9V05U43eYuh0QV+x8Xow2N+BQ8/5QNg8a1BvYHw/K9bw==,iv:XydAceBxdf4Q5aIf3JDrXwlLKkrDLC+8RBLO6x8AncU=,tag:SwmJ4sDeoZQhFpNhTcEbEA==,type:comment]
    SRH_TOKEN: ENC[AES256_GCM,data:uVTLBwv8ebevHdAYJgOYUhmOrjRB6YAUFx69OFTqVx+tUWmk+Qz2ZlymZ5W+KWa+wDCqjfXSUlsLiY7D9KiJNQ==,iv:CDpOxxdF67D5U5V2kbUpIweEJ1lavkX0NUp+TGQKAOk=,tag:0f3esrInxTSfs/BaGuD/7w==,type:str]
    #ENC[AES256_GCM,data:vxBGVyyihPkXCXp2TV2TRZiBM3pPBaaWQlIrakcuQUzVaJdRAwMwEAEP79chJ9hFG0M8bRXxIrrzHqVnSHeDDQ==,iv:+Lu7Kf17tqGGbTrRknR9RZLIeyA7wf8jTd46JpG/FtQ=,tag:2dulBRTbM4ETY8g3vIw8IQ==,type:comment]
    FREESOUND_CLIENT_ID: ""
    FREESOUND_API_KEY: ""
    #ENC[AES256_GCM,data:eXXgBFyjd2P+1B6bH799G07dQ/oDTuLdF+aBr8wQWl5e+0KSEIJvVLbspo+xJor/,iv:guPSSe1Ius0qZeT0yGuDPWGWGhosTx0YnHvgB4DPx6c=,tag:gAfdGDWLlnKAh4ppVBgrbw==,type:comment]
    CLOUDFLARE_ACCOUNT_ID: ""
    R2_ACCESS_KEY_ID: ""
    R2_SECRET_ACCESS_KEY: ""
    R2_BUCKET_NAME: ""
    MODAL_TRANSCRIPTION_URL: ""
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbUgvcWVmanRDdndNN2w3
            TjhlYXU0SE4rYjB2eEl4Zy9WdjZUMW9PMGhZCmZKOXArdjJTOWhMN2VWTlh0bzh3
            NDFMYWlYeFhJMkZJVGVnMXlvME1hVUUKLS0tIElaVk45YVh4NUJ2M2xJcHY2ZnJo
            dGphSmdVTzlxclk1bFV3UXdZSkdPVHcKCSd+QG4SwqNY/6Eiocp3hbsNjEo/cJ/5
            5ACJDWKCRCxOWO16KAvtpWXl7vUdNGNRW85m5UyBA3DMlxBdm1dKLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T15:01:56Z"
    mac: ENC[AES256_GCM,data:Lf04vKRy4jQPPFZ5+SZEHHbZVar7cFe0Bd3lLY7ngXUN6tRBd7JcIMKBiZLWrVZXmLvPuKL9ztSUqk7Y00k1BcctRmQ2GtL4ZnUCm2GNCI6pmaoCnYMFDX1iuUwRiqsCTlPNSif3AlgOJTCj+LJ9FMNZaa14HbeFaBjToDV9gfQ=,iv:fPBLzFVdTZVHUPAUs2yNUMA5s57ayY3V6ytwlHixXq4=,tag:U8sQ0ihQLMhwVd5X0H/pJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
