apiVersion: v1
kind: Secret
metadata:
    name: sparky-fitness-secret
    namespace: sparky-fitness
type: Opaque
stringData:
    #ENC[AES256_GCM,data:UQwDSZSfQNKmkVBDynN3V+YMJlouopFCh5xtERUo8bZfKfMtRF4mYgNC+UwXu7e94uv8k1jwoHchmlDnyg==,iv:isRfE5ngAQtWwKh2pySqHB777/HkincHS3P/QXUssIE=,tag:2bf7A+UJOXPXzGDk5kBWPw==,type:comment]
    #ENC[AES256_GCM,data:5bTx7umBKlH7tJmlW9mOpEKkwMcWRlWuvrsCu1cB7Sa0jRqd9Q6E3RnTBQJd6bxfvDQMO+Zkrp/y9o0RuQ==,iv:/tuiVDjJUd5BsXncUf0ScFT2bMPTj0T8djeD4RC2eVc=,tag:15PMeczEdBJO0x457SxMsw==,type:comment]
    #ENC[AES256_GCM,data:rdPnynYpLmq/a+SdPFi2YpwzC6fGUlikgJI2f4+AYNhm3k3eux8J+MTz7+0G+QPcn6nH5JzN6hWtNj4WEw==,iv:CFbLFf5GXMXtGvkgEMV2ap8UL+e5m0QhLthaIAxmIWg=,tag:dYPFLd691zn2uu9NsQ3MkQ==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:LCMQuZ8hEC7jQq1ZHyUK9Q==,iv:PvbVOb3kzykB9IGLoRNKLKMfQjLdLjv3vLG1JZAb868=,tag:5YY1TpDLFVEIUfzhpDLHhA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:sSSoH72c,iv:eqfjYZSASnU6jToCFntepkZiX4vZjDTJZMDkobM1J20=,tag:Cag6OZSspQ2zziAbHYUkCg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:8Zgn4yNBJOgxVoIdErY80w==,iv:S1ryaCW97O1i9cjkxRUsMZi7+Q9gIU+rnLssW6b9ug8=,tag:S58KJz0pQdDnTnAVPdyyjw==,type:str]
    #ENC[AES256_GCM,data:11NUZDsZl4k8irRo/mHLfAWM8WK4web6Aca0EcaOf42ml//eYh7PDWdE8il/BJiAaGgLpY1KvOXb0EpIrg==,iv:dINrcq2VHEScQdzzQSgJ1I3V/slVx8CV+ikmydTi8vM=,tag:i9GycOl8JkIdUzcC+b12ug==,type:comment]
    #ENC[AES256_GCM,data:UzOewQ2diD8RRBBwLurLo21kOHTOpmVLFt0HSuxWApzYQtMYulTScq5x9htmpIm0mN0=,iv:LFSZAXj0rd8vcNWSz8nwBaT9AYY9WV+BliBpH2or1/g=,tag:JdJG/SojX/EleTZO6FKoAQ==,type:comment]
    #ENC[AES256_GCM,data:mVnZyOGQidPRLlAxAnDfLrNNDMYJ0dWZ+BbXRvtaXGIO9YkKXY3fvtF0k3ugUiphYCcDz5F1fxIbDUmIEw==,iv:r+723JjzVyDngrtkP0tOnDCPXkFjy5XJf0dKGb1XonU=,tag:ce1oKIjFpPnmA/hs+ILDDw==,type:comment]
    SPARKY_FITNESS_DB_NAME: ENC[AES256_GCM,data:XFaMpxESQbAvw1ASStmu6Q==,iv:izSAkn9r0CjanABKeTH/FqGMvh8m2q5rDb8tBYIVT8w=,tag:3B/fpLExf9RrS0+2SD3bRA==,type:str]
    SPARKY_FITNESS_DB_USER: ENC[AES256_GCM,data:y6vvAMTY,iv:nUQjdGVCC9WwikwYSPUK+nO2mZPNzCCaY3AT9olOi4c=,tag:4N0bt359rYVfMpvdfqAFhA==,type:str]
    SPARKY_FITNESS_DB_PASSWORD: ENC[AES256_GCM,data:6cnnj4pJEtBy3PQuXbUaRg==,iv:gePCzfAU2Y1ZggHgVzZzQrh/heeSwIsik6/fW5FCKzE=,tag:BrZ/xd8u+8zWRG4su8B8BQ==,type:str]
    #ENC[AES256_GCM,data:nSl2IW9nr6Gektc3uAueHjlNJefXHEtzvhXEt6xVqT8xUcARf7veI4poulGdzdPl2kNQRLlJZ3lIMwQwnL6bAZsn1ubi,iv:TtLAdF+yY3DU57hO3j/2AqZm5/Ld0cjdemCjANVRseE=,tag:ftFBSTitoJW8EfdVbwZGdQ==,type:comment]
    SPARKY_FITNESS_APP_DB_USER: ENC[AES256_GCM,data:ip60TNIPrVE6DQ==,iv:1d3YHeyjO01FhULVSbFHV0wHbHbSj7zBJIC0iH0FOZY=,tag:lp+JZzmjbLH7ogpLZLYtzQ==,type:str]
    SPARKY_FITNESS_APP_DB_PASSWORD: ENC[AES256_GCM,data:bBJjCPFZA7nmyp0ugjsQiJjE,iv:JCzp6VPb9JB8+riMIjrhrQRkP7t7F1Yn5OArhFjyKNA=,tag:TVER0+MLpccPnucVHGnnvg==,type:str]
    #ENC[AES256_GCM,data:3FfVxMGLH+IJnoTLKzCalU7KKKWncF+dUA==,iv:yOMI8yCaE7N3UqEDH6BipJ1XL3yXrspY+FGUl9eB5tg=,tag:0kJ8mTIfLYL6AFo7EaYa+A==,type:comment]
    #ENC[AES256_GCM,data:c/SMoCqBOSohwM5chqJRxtvLDYKMaHaPjuaWmIykH0Dfutav,iv:4fX7E3AlHzAQSaU7JbclouOzugm9UiQ+tPBh4iR7Ppc=,tag:DpcCm4rJnuTXqqAZjOGgHg==,type:comment]
    SPARKY_FITNESS_API_ENCRYPTION_KEY: ENC[AES256_GCM,data:X7BcmzAqr0qXEcrKl9s7MdL98zoGrdhLkS4uqOQ6WSEYvtSNH82S6UzjnIf06Rsqx6ypo8rD1PY6A0TVXAxuVw==,iv:k6dIp5TmwQzMkT7ie/qLpsqr87tiWvkg1Szv5O9cx0E=,tag:+WcAsBTeNRPz0yXsCZT2Hg==,type:str]
    #ENC[AES256_GCM,data:wGMWTtMaZK32P6GUm5qOBwC7EXZ9,iv:fe1Tv01ML9zP1ws41MSPgyhYzk+Vtm/LQOUKJIdTRlI=,tag:71NftU2kBeTOGxZYz9hcbg==,type:comment]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:inJIFc3fkZAlwnAHrWWU+/iz44CTNNNUSI3O0g2p8AgiLcG6+6jnR/rCyXgEzJwuVWKi33C3tIp9JUMUVmleid4/siDrPT5y/g2tjUoGz6pw1HPImK5CSEMcvPuErTNyHEqYf2srCBDhK31pSfDq67lALXhakBsER6nHtayx2hw=,iv:Lj+/1OGo7ai4CCex4Rfxu1geTGbKg+h02lANBCtk4KE=,tag:PsS2rzeeeVUKGqr7Aqrp3w==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OEw5aDZkcGQvMUlmUjNu
            RE9LNmh5QW14bWhjejVhMStRRVdXY0xac24wCmxyT3ZTTmsyT0pNMHg0d2ovcFdB
            WUtJVGdRSm1pZG1xSVFpWGlyZW96MmcKLS0tIERpS2dhNi9xS0JJQWpSSzY3RS9I
            dmhQejdVSDlJWERHNmYwa0Y4RHZvSUkK0tq8UWmzqKXxF6uZZKPAAxQJTDG1Bs4r
            8x7zIeGV2HjjXaJO9+LQWlLzvoQMpHQSzFMbV+ABiOzF5CgCUiuELQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T21:51:06Z"
    mac: ENC[AES256_GCM,data:tlpfyXGDGUTuiopb6VGI/C+H/QfwbAXMwb2nmI5p3iaRmDFd63A+z2sJ66g0Auqb+14mlqCcCPiBei4145VbX9u47F0RXcX8y2ef2uuLOPLCRvZkFPEOJWTIHQnAZPTbxXox0AueVytzXFvbs5ujZMFblkQn1vzZTsd8DSWvPXk=,iv:grKTdaZKE/PChsyANTl0LRIOSWJh4r4NCRKjE9JbK6I=,tag:XgvQsakmZOaYISCOxkBO3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
