apiVersion: v1
kind: Secret
metadata:
    name: sparky-fitness-secret
    namespace: sparky-fitness
type: Opaque
stringData:
    #ENC[AES256_GCM,data:ggHl90VvGLQGTNI=,iv:cZXIwGxvcLYt0wBpU+ZNCTgsBbmORiE6CtkkSNCJ6J0=,tag:+yUMbmTTDT0PDNipDr1Ovw==,type:comment]
    SPARKY_FITNESS_DB_NAME: ENC[AES256_GCM,data:XFaMpxESQbAvw1ASStmu6Q==,iv:izSAkn9r0CjanABKeTH/FqGMvh8m2q5rDb8tBYIVT8w=,tag:3B/fpLExf9RrS0+2SD3bRA==,type:str]
    SPARKY_FITNESS_DB_USER: ENC[AES256_GCM,data:y6vvAMTY,iv:nUQjdGVCC9WwikwYSPUK+nO2mZPNzCCaY3AT9olOi4c=,tag:4N0bt359rYVfMpvdfqAFhA==,type:str]
    SPARKY_FITNESS_DB_PASSWORD: ENC[AES256_GCM,data:6cnnj4pJEtBy3PQuXbUaRg==,iv:gePCzfAU2Y1ZggHgVzZzQrh/heeSwIsik6/fW5FCKzE=,tag:BrZ/xd8u+8zWRG4su8B8BQ==,type:str]
    #ENC[AES256_GCM,data:7zwA1A0FAeFx32u+c8gyRk/mmzOPs6LuYUMBg5wT32BIu5OQf0g=,iv:+ijvJ1HRfUG8d5gGhFY2ODsLAQT1GwCahziXhQ9BmLQ=,tag:MWjFGb0k+RzD0bx8D1RloA==,type:comment]
    SPARKY_FITNESS_APP_DB_USER: ENC[AES256_GCM,data:ip60TNIPrVE6DQ==,iv:1d3YHeyjO01FhULVSbFHV0wHbHbSj7zBJIC0iH0FOZY=,tag:lp+JZzmjbLH7ogpLZLYtzQ==,type:str]
    SPARKY_FITNESS_APP_DB_PASSWORD: ENC[AES256_GCM,data:bBJjCPFZA7nmyp0ugjsQiJjE,iv:JCzp6VPb9JB8+riMIjrhrQRkP7t7F1Yn5OArhFjyKNA=,tag:TVER0+MLpccPnucVHGnnvg==,type:str]
    #ENC[AES256_GCM,data:3FfVxMGLH+IJnoTLKzCalU7KKKWncF+dUA==,iv:yOMI8yCaE7N3UqEDH6BipJ1XL3yXrspY+FGUl9eB5tg=,tag:0kJ8mTIfLYL6AFo7EaYa+A==,type:comment]
    #ENC[AES256_GCM,data:c/SMoCqBOSohwM5chqJRxtvLDYKMaHaPjuaWmIykH0Dfutav,iv:4fX7E3AlHzAQSaU7JbclouOzugm9UiQ+tPBh4iR7Ppc=,tag:DpcCm4rJnuTXqqAZjOGgHg==,type:comment]
    SPARKY_FITNESS_API_ENCRYPTION_KEY: ENC[AES256_GCM,data:X7BcmzAqr0qXEcrKl9s7MdL98zoGrdhLkS4uqOQ6WSEYvtSNH82S6UzjnIf06Rsqx6ypo8rD1PY6A0TVXAxuVw==,iv:k6dIp5TmwQzMkT7ie/qLpsqr87tiWvkg1Szv5O9cx0E=,tag:+WcAsBTeNRPz0yXsCZT2Hg==,type:str]
    #ENC[AES256_GCM,data:wGMWTtMaZK32P6GUm5qOBwC7EXZ9,iv:fe1Tv01ML9zP1ws41MSPgyhYzk+Vtm/LQOUKJIdTRlI=,tag:71NftU2kBeTOGxZYz9hcbg==,type:comment]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:inJIFc3fkZAlwnAHrWWU+/iz44CTNNNUSI3O0g2p8AgiLcG6+6jnR/rCyXgEzJwuVWKi33C3tIp9JUMUVmleid4/siDrPT5y/g2tjUoGz6pw1HPImK5CSEMcvPuErTNyHEqYf2srCBDhK31pSfDq67lALXhakBsER6nHtayx2hw=,iv:Lj+/1OGo7ai4CCex4Rfxu1geTGbKg+h02lANBCtk4KE=,tag:PsS2rzeeeVUKGqr7Aqrp3w==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OEw5aDZkcGQvMUlmUjNu
            RE9LNmh5QW14bWhjejVhMStRRVdXY0xac24wCmxyT3ZTTmsyT0pNMHg0d2ovcFdB
            WUtJVGdRSm1pZG1xSVFpWGlyZW96MmcKLS0tIERpS2dhNi9xS0JJQWpSSzY3RS9I
            dmhQejdVSDlJWERHNmYwa0Y4RHZvSUkK0tq8UWmzqKXxF6uZZKPAAxQJTDG1Bs4r
            8x7zIeGV2HjjXaJO9+LQWlLzvoQMpHQSzFMbV+ABiOzF5CgCUiuELQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T20:29:38Z"
    mac: ENC[AES256_GCM,data:0qU2I47V4SckpFx0jmszd2aqO1cOK14GZkm05Ubafc8qvSpFBlQSTAw4VhAE8rXWYw3bWwk7XhaJP14ynd1uPd/rkLImxrejy/y3Zt7X52P4iTPPZD/uCGMouG8ejkJdH/mEIzH0jyQKLuNa1QHcHPR3oheF+F99L2GukEKuk4A=,iv:wdOpsY27rcGi3RkGF5zZhhRQyJXRIs1r/UMezrH0lx8=,tag:Po26NF/g7uxJ2bB1hvfw0w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
