apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tandoor
resources:
  - tandoor-namespace.yaml
  - tandoor-pvc.yaml
  - tandoor-sso-secret.sops.yaml
  - tandoor-release.yaml
  - tandoor-ingressroute.yaml