apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ui-toolkit
resources:
  - ui-toolkit-namespace.yaml
  - ui-toolkit-secret.sops.yaml
  - ui-toolkit-release.yaml
  - ui-toolkit-ingressroute.yaml
  - ui-toolkit-pvc.yaml
