apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openmrs
resources:
  - openmrs-namespace.yaml
  - openmrs-secret.sops.yaml
  - openmrs-mariadb-pvc.yaml
  - openmrs-data-pvc.yaml
  - openmrs-gateway-configmap.yaml
  - openmrs-release.yaml
  - openmrs-ingressroute.yaml
