apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dispatcharr
  namespace: media
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      dispatcharr:
        containers:
          app:
            image:
              repository: ghcr.io/dispatcharr/dispatcharr
              tag: latest
            env:
              - name: TZ
                value: America/Los_Angeles
              - name: DISPATCHARR_ENV
                value: aio
              # optional logging:
              - name: DISPATCHARR_LOG_LEVEL
                value: info

    service:
      app:
        controller: dispatcharr
        type: ClusterIP
        ports:
          http:
            port: 9191

    persistence:
      data:
        enabled: true
        existingClaim: dispatcharr-data
        advancedMounts:
          dispatcharr:
            app:
              - path: /data