apiVersion: v1
kind: Secret
metadata:
    name: code-server-secret
    namespace: code-server
type: Opaque
stringData:
    PASSWORD: ""
    SUDO_PASSWORD: ENC[AES256_GCM,data:Evg0LFo=,iv:7UUp0gZ8m/GQ3L+AgriiPdr+m/06w+T9dnnjuXLP/oE=,tag:Wk0MtL859kJdWSoYLX3zJg==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNHFCYysxd054aHpDdy9U
            OStLUzFVZERnYTliK1B4TFhVdEhwZHY2V3pVClE0enZKV01lR3ErTmhIakVGc0dY
            aWxQTEpWOWlCaXk3Z0NYcnBBbDBNd0EKLS0tIDhmcFFJTk1uY0tEaW1adjJaVTVw
            all4dnFBOTk5Qit5MjQrS3l2NUJlSDQKPQZf3WZmD/ub2SDES4dzp1C1dCvnAdkt
            w2BuISwYyebK1UrXgePWVG4+0+H3f6OIchlR59XkTUNfK/Z81Qs3+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-14T19:03:25Z"
    mac: ENC[AES256_GCM,data:1d67yKoiJkIG3W3NxiFToDh0lr62TtcjlYMyGgCJgQUnxZmrM+H+J/HDSygrQ03W5UYBwCdxkLiDOVgzMCqt0RMeemf2rRo/7TqSiwEx2uj4uzx9USM7irOzB7lqV3rG7FSzfOJytmtS0bMfHIjqAn02Q+N6UJNQ/yg4OjpIWjk=,iv:ytanKOkE/PuOJRJb9YyN88xQ6BRmFsvoeBdkfPWORt8=,tag:EOceQg+uPpDlq6rewVG5HQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
