apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tracefinity
resources:
  - tracefinity-namespace.yaml
  - tracefinity-pvc.yaml
  - tracefinity-release.yaml
  - tracefinity-ingressroute.yaml
