apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracefinity-config
  namespace: tracefinity
  labels:
    backup: daily
    backup-engine: kopia
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 5Gi
