apiVersion: v1
kind: Secret
metadata:
    name: mosquitto
    namespace: mosquitto
type: Opaque
stringData:
    #ENC[AES256_GCM,data:h1+kG0/nn3Mb/SUMwOcsztwVvIrMs3kvFpeV69SWhaDsJdpxjnZJkGR7X2TlDNtltapF9ihEbF/O7hDdlAuhQ82/,iv:YZG3MTd3hDRcad90BWr1wi4Cqa4jKZ9utq3AyUDBbB4=,tag:nrS3reUpOuW0555+MhGL0Q==,type:comment]
    MQTT_USERNAME: ENC[AES256_GCM,data:zdlTUfGH8Kqy,iv:dvE6cb/p1F0MVo4lVupaZIAVM2R0CkHLxIFgw1nbUFs=,tag:zjfoHHUzEUeDqzngK+jLnA==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:YFF/682UZs7JtxWr,iv:VDwL1f1I/cjuokZtwLmdqz5qVGheIfqpdNBJiBe/SoU=,tag:wfSTgCPQznjEK6ElK2o9Aw==,type:str]
# Zigbee2MQTT should point to:
# mqtt://mosquitto.mosquitto.svc.cluster.local:1883
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeDdBK0dERDkvR01NZXpL
            TFJyZGtQNm1KR2VIWjVUTEZQcjIwQXQzb0RBCkVkUlVmaW1LNnpubGo1RTB6bHhC
            Yy9VVXZTZXlUSGJLSnpmSVVkMkNuQ1UKLS0tIGtEelk1ZCs2dzJBZGQrbGVXTWtW
            eTJYODZOY0EyeGIzd3FCVGN6QkNSNEUKchP+fhoT96rDNOqxm2jp3AhCgoNDz2ie
            9dsw/HxwgrVsf9MK6JjfSC70BiwQUVRxA3YlmDHF0g8TkCCPyzj4PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T14:27:20Z"
    mac: ENC[AES256_GCM,data:y1n/QsMTR4tPtc/NuR6yQ+ib4zWhPtd779shjMD+U8P5YPknmvCaHrEnXdjQ/M3mmpcXiqVBhcCffzkI644WDHsJ8E8zeFYrfSv0BdIUtjV5tKe9K72U/uPqlH2awEWy2CUMh9i+hBYeVSVcH9UQal2vc724aL9oRoJkZToTEoM=,iv:OMuz/24mWviSFDMoSiJM+X4o6TAptL9SVhJ8QAj17Lk=,tag:digk0B9hoceQuuMiM5owCQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
