apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wallos
resources:
  - wallos-namespace.yaml
  - wallos-secret.sops.yaml
  - wallos-release.yaml
  - wallos-ingressroute.yaml
  - wallos-pvc.yaml
