apiVersion: v1
kind: Secret
metadata:
    name: wallos-secret
    namespace: wallos
stringData:
    #ENC[AES256_GCM,data:8/5yPBcFcKxlxQGZvmszMvvR3Y5S25IoZUQhmJcnRjc8HM+4RcTEvOMvVA9NmlqNlkFms/X8SGOYI+fifH952Tt2FBGknfU0,iv:S4NquQ09MzjRiI2M9DeiwHqRcqMEq7J84gHMKGWm520=,tag:EJvLYBXnvm84534j0QDdjQ==,type:comment]
    #ENC[AES256_GCM,data:wa2boSHyo7YbcMXbQb4BJqln0YuFek3YxUVrlisasm566eIvlOJ1QhJkCnf3/fFdsLVSdsdkGq/DY62MOCZkO6t3qSmX19ML,iv:MpZeDcnk1F/DJl8mdFN7Em4s1GI0ZHdbC2Q2vHrU+3Y=,tag:0IjUUJbZYF8/N9kU47QHtA==,type:comment]
    #ENC[AES256_GCM,data:cnfLjhd5yv8cnYzqDxnzDTjuzT48fW2aaeIRZXxuZzix/kOPESyoBmMCtnIznIJ2bHmjTPw8sFUHNTdnS/xImLQKGLtG2QdGAQ==,iv:+2z9vIj0ylkxQX/n6BlfdlNx5FYMN9aNkVeLB254F9g=,tag:o7nANrkNFuwWAunOodMP5A==,type:comment]
    #ENC[AES256_GCM,data:SwHyIY7SOMQQcYH/Ccb1tH9D2MD4243fLNTmxkU5Vo6iJKKUEbufjcU0,iv:JHDzhRLgMzd0kOGDCrRUJMbzX6gwUqVcMGsSRSR6Bso=,tag:10Baj37NX6A1kKTEJfr8Uw==,type:comment]
    #ENC[AES256_GCM,data:79smhI9OpRa0uum6I1S5EsRXbld33rFsEV8Zg3jm1TKT1cR9CzpXbsTeUkvsBds9zGLiiJLC6qFhkxYcbNMgZCo=,iv:W8PfsvOMSGihXlv0h2MHxAJPaMeVvXtyhrZnfUdGgZg=,tag:A9njoDnmp+kRCnEjceIMew==,type:comment]
    #
    #ENC[AES256_GCM,data:2cNOoWP8z7EmSQnZpWTeiJYx1x+vv1mbKmVqEZqBVAKc7HQ3,iv:h+dRd1q3y+38ceZrbcvkRkaLRD3UJDD8vo+vLdF8tLI=,tag:CTVYFUysWzRq/+gmwSzh7g==,type:comment]
    #ENC[AES256_GCM,data:KgqvionChYXYf8/Pg7+gk82C63YAFq7sQbKR+j5JmxJOhgQXW/aBrhaXVWV3,iv:cO5lXSv1KhFMhJ94lOqBo9rCEALYvg+OvFgjn92DcOQ=,tag:bZMwiIfXJmaeHJuhLj9kcg==,type:comment]
    WALLOS_OIDC_CLIENT_ID: ENC[AES256_GCM,data:5h/laY+AeZqD3M3APLC8Jp0wmplbpszTsRWB99/YdvVST7ePCt1wmA==,iv:gQZX9e285tu+6Zkvfbo1r1WteMB6HrP2O8kYUYBQbtc=,tag:XNl/0bgOoBjScpxYzNxu1A==,type:str]
    WALLOS_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Gw/troGQnKtJZ5SFT/Y6cQWvUKVCOYiOmVKy7Fs4X3JiMU7y4yZ5x4pX0dbdhN/fYY27dfl/8EG+DNklWiJit0OQmSmXKObYnlCeC7bXk53LjeGgLDwyebruiX8OF6YYyrL4UEY4tDLxxLcJzqACKViM9sMsfdrdCYeq5I+L+lU=,iv:P9+hKn71TyxSspdDh0ke5XqSZ/+Rsnlx+envx18ZuCc=,tag:Vp4A4l0geX+6Ace7MLWTnw==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2R2VTdFdidUhqSVg5V016
            Q2N6ak1Wak10czUvN3FjY3kvN2RzcWlZRlg4Cm5lTkdRUVViUEh6SXEyTnEzUk1L
            K1I5TE96MStDdUFMOVFLbmFia0dVS1UKLS0tIE9rTktFVXZmbkxPSzU4NTRDRXlL
            Mmw2b3dhMUFBZE5XNFh6azlnam1WY3cKcX6akBgrf5jioTertZbeKLAhcP0u62Dw
            6KH/02r4t5dOO9CKRblIKKoQu98OxTRs/kddOFaZpCb71OZvBNsdUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T09:30:09Z"
    mac: ENC[AES256_GCM,data:o1SaJ9HwW2BS9oXS7rO5Vo51EP3gV2qmhhH3SBiUbbArMTJ41Cp7j6bmu9DpfrFNi6wLroWcgrytb2Z131lzvnmLGOHhdKqgk34HyP7PkgeK1oTLR0yYNUChU5srgVDAPrGGwoNFEIPoh5P2aGp0kPRsEiW3KeRVO7sjB/BH0QY=,iv:raxVPmRoVDeVbaDQYXSFsbTXAQP9vOXRuzrmommHkcA=,tag:71b26W95G+tg8SFxD9+pGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
