ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - websecure
    matchRule: Host(`traefik.lab.mainertoo.com`) && PathPrefix(`/dashboard`)
    tls:
      secretName: wildcard-lab-mainertoo-com-tls

providers:
  kubernetesCRD:
    allowCrossNamespace: true

persistence:
  enabled: true
  path: /certs
  size: 128Mi

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
