apiVersion: v1
kind: Secret
metadata:
    name: nzbdav-rclone-secret
    namespace: rclone
type: Opaque
stringData:
    rclone.conf: ENC[AES256_GCM,data:796XbVOsGkhDmMI7QVtPi9SzPN9FofQR78+R2Lb6Ci0xi3QJFxOvYhsCh3ccQAub/C/sAjNAfZTGSoWTQduH/ecrgpc5rtTQCSegIHg1yvRpVl3WJnxQNHh9wGe1gT2SJIKjG2elFfRrflg6T/dB6cGQmmEuyPi540FNd6re44NMPVXbQ3zjBLqx5QQvl/HZ+DZM824C,iv:L7lUcTKyt6LKYWtJr4WuhzNjdpurSrzxj/SwuFzoZdc=,tag:/0kzJjZbXTemUTkRE7qQug==,type:str]
# pass = uTUAY1LuVOjCTVqQ8BBgS2mK5dkAgN7NedibDQ
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdnVqVUZqZDAwYTl2M2pQ
            b2thVDJIUjNORXNLSERuQkZ0NVVNOHEvc1dzCnlZV1pOVkpEU2ZtUFlWc01odXE3
            SS84VE9OeTJPMG00NnFScnJFVCthMXMKLS0tIGVaZkhZTGxvM1B1cEV6czJNaHFi
            T2ZURjlaaXBTOG5pTXFjM3dnNTMvam8KUvZOr9qQBoa33d6dfvC88qh2fPfD7hP3
            iq/pJ0z2ISUwVn23l7e8kLXpH0N9PNiJazt5wRNMjqYv9NbKEDRBug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T07:14:34Z"
    mac: ENC[AES256_GCM,data:oK0Txaynoc50wnIWIcMHUJ24Xm15K+MdTM30x4WL2QelHZ/ueWkKfTsod/aflseqJ59YaM+1hOha9ltkkQYk5m1z/+ufwJjxmTkHm/e/+X90U2aRY7z1cb6sADoeNFaDxD8eAt+3WFbstbuo5CYV1SKltxbqD6yy/6mmPcqh088=,iv:shYpxumykmX4PciU/yr7bg0a0Z0KMnuZ/u5P3xu0guY=,tag:tA5T8ltX7m5qL+oKd+X3EA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
