apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cephfs
  resources:
    requests:
      storage: 100Gi