apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qidistudio-config
  namespace: qidistudio
  labels:
    backup: daily
    backup-engine: kopia
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 20Gi
