---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app audiobookshelf
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app

  components:
    - ../../../components/volsync
    - ../../../components/volsync/local
    - ../../../components/gatus/internal
    - ../../../components/gatus/external

  interval: 1h
  path: ./apps/base/audiobookshelf

  postBuild:
    substituteFrom:
      - kind: Secret
        name: volsync-garage

    substitute:
      APP: *app
      APP_NAMESPACE: media

      SUBDOMAIN: *app
      GATUS_DOMAIN: lab.mainertoo.com
      GATUS_PATH: /
      GATUS_PORT: "80"

      # VolSync defaults for Ceph RBD
      APP_STORAGECLASS: ceph-rbd
      VOLSYNC_SNAPSHOTCLASS: ceph-rbd-snapclass
      VOLSYNC_CACHE_STORAGECLASS: ceph-rbd
      VOLSYNC_SCHEDULE: "05 00/12 * * *"
      CAPACITY: "10Gi"

  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  timeout: 5m
  wait: false