endpoints:
  - name: "${APP}"
    group: external
    url: "https://${SUBDOMAIN:=${APP}}.${GATUS_DOMAIN}${GATUS_PATH:=/}"
    interval: 1m
    conditions:
      # If Authentik sits in front, allow any non-5xx
      - "[STATUS] < 500"
    alerts:
      - type: discord