apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: excalidash
resources:
  - excalidash-namespace.yaml
  - excalidash-secret.sops.yaml
  - excalidash-pvc.yaml
  - excalidash-release.yaml
  - excalidash-ingressroute.yaml
