apiVersion: v1
kind: Secret
metadata:
    name: dumbdo-secret
    namespace: dumbdo
type: Opaque
stringData:
    #ENC[AES256_GCM,data:AqPuJXLa2ae2LnxZW/JHzTcqeLMbm8jC,iv:9LEtxp0bZrfwFcO6oauyFsBqKInn0CBH4+OU8BJZPQ0=,tag:qzjTZxj/9gQ2LuoyvRE97Q==,type:comment]
    DUMBDO_PIN: ""
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNK2c0Q2VaWEk5L010WmVw
            K2t0RlVKa1lqSmJSTjF5VG0xWXdjMjgwdkZJCmhqWGpIa3JEemNldVFsQUVhRVZy
            d0d1WVJwSm5FWkVtaFNmTEs1TnNlNE0KLS0tIDROVTRkY2pFMmdyRnd0dWpqRG4y
            cnkvQUdjQklVTlkwN0twMFQ2ckVSREEK50/xDVXWv1N+fauP1f8I2ztGLSIY89od
            LOFBQKTPLwYbIwITtHQg89P8Q4gi064eW/YegTQ5Z9PrekAJLmKg8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-04T18:10:52Z"
    mac: ENC[AES256_GCM,data:4G9jiuoQGr2Z315QVdbdvwLoEZ+42M2KHoXUUruggw1Av4+XuSuY2RK2ED7CyeVfb6mdxerNpL0tEyfEPM1k0+otwad4q8fR82WAjYcrbFJ/mnAF7ITRdxEwl5PStuKNpw0gc0JbNvARGgRBtRqJnxi3aGyKdwvrGS9YYZZ21TY=,iv:hS3BVaMzF8WyWYCZ1KSdJTa1Lod8bbuyr17F8Ac/PwM=,tag:XGp5+5HRtk3LdD8Zr5I25Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
