apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dumbdo
resources:
  - dumbdo-namespace.yaml
  - dumbdo-pvc.yaml
  - dumbdo-secret.sops.yaml
  - dumbdo-release.yaml
  - dumbdo-ingressroute.yaml