apiVersion: v1
kind: Secret
metadata:
    name: wrapper-secret
    namespace: media
type: Opaque
stringData:
    WRAPPER_USERNAME: ENC[AES256_GCM,data:iVIqlZvulnhWNVpHp2XT9k99MA==,iv:Pwaz+LVQsz+5NIeyVUGx00fyxYHJTk48RKiwFOLp/sw=,tag:Q69Cz25Iwid3Y8ZReB/1/A==,type:str]
    WRAPPER_PASSWORD: ENC[AES256_GCM,data:e5+8i0oDzDU=,iv:5W+Mb89PQIzSscYgAEUD+hPY6G4zlaCGi1QD3vaWYMw=,tag:BwzugKrEYcdW8Q8ZHAsHtg==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QzMxcC9pSUxnMkZpUjk1
            eEhaaCtSakNTKyt5OTBGNHg4aStWSDUxeUY0CkREVkI5dXpuNGgydmFnZjN2OUJ1
            ZTV2RERYa0pCQi9Qclgwc2xsQnlzeTAKLS0tIHYvbmJYQlpvMkZjOVd4RnEwRVF0
            NEN6NHVycE1hN0xDSkpBdHp4elM4cGMKPo8EDkrjNMO5WLrzdLzQkKGlrDVaVytk
            MxsI/0ZEFb1+VqIZGmiNXWADOAbu345qPKb2AsyiapgUmNf6UgOmxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T05:52:08Z"
    mac: ENC[AES256_GCM,data:HmSQZ+CjRYGuj6uIFwr2aTdUWesxRvUWM5tl6z0F2IcpUeHMXHpsU8IVpJS5UheAFykaUgy6yc/CUPprIAUCLQLQAXJ+uCPu/nmNo5tx3EgoqNv1jWdkooN1+gwku2jxcsqv3IS/15LJLgMlnRk9Ze17zQ9LW5bdH+1yf72Xses=,iv:8Z6/Ru3sJbXWZBSBORD19VRoRvK0PFUibYiESw4KXAo=,tag:GvHANsXvLI7/rOEIFP8i/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
