apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: esphome-ingressroute
  namespace: home-assistant
  annotations:
    gethomepage.dev/href: "https://esphome.lab.mainertoo.com"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "ESPHome"
    gethomepage.dev/description: "ESPHome dashboard (Bluetooth proxy, sensors, OTA)"
    gethomepage.dev/app: esphome
    gethomepage.dev/group: "Automation"
    gethomepage.dev/icon: "sh-esphome.svg"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`esphome.lab.mainertoo.com`)
      kind: Rule
      services:
        - name: esphome
          port: 80
      middlewares:
        - name: authentik-sso
          namespace: traefik-system
  tls: {}