apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - zilean-release.yaml
  - zilean-env.sops.yaml
  - zilean-postgres.yaml
  - zilean-postgres-secret.sops.yaml
  - zilean-ingressroute.yaml
  - zilean-pgadmin.yaml       # NEW: pgAdmin deployment+svc+PVC
  - zilean-pgadmin-ingressroute.yaml  # NEW: pgAdmin ingress
  - zilean-pgadmin-env.sops.yaml
  - zilean-pgadmin-config.sops.yaml