apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chaptarr
resources:
  - chaptarr-namespace.yaml
  - chaptarr-pvc.yaml
  - chaptarr-media-pvc.yaml
  - chaptarr-release.yaml
  - chaptarr-ingressroute.yaml
