apiVersion: v1
kind: Secret
metadata:
    name: chaptarr-oidc-credentials
    namespace: chaptarr
stringData:
    #ENC[AES256_GCM,data:9jFv3MRyoownQNCpwAcxQlCMaFHn1Ulbxar3GMMoq27nmBaNrvGchL8SMlPqzgGmzZ6ZAJoIZ43NKtAqGnwbFNZM5w==,iv:E5j4r9EqxOxGJQSfs6MMh3e/cHctTRMAkF0BPp3sBeo=,tag:XG98Rm2vXABgUBn/87TRyA==,type:comment]
    #ENC[AES256_GCM,data:Y3AjGHAiE/zF25rM1ixx1rhV5LEUuuzksakT5sb2W/P23w==,iv:yiSxuzYBS0SM6xfcVdvswAyuGXXWGFq/TKh2ey4T3Jc=,tag:mlyVkadURo9g4yunb7fkQw==,type:comment]
    CHAPTARR_URL: ENC[AES256_GCM,data:qy57ZY7jUVMks6VOxQezsNa9LAXLGLRUQy8mLmG8ddMReceGO+c=,iv:cijIEI55MAwF8AzLrQB22wPjS92Dtn7ABvHCWPyc6vY=,tag:naqY+66xIoWAC0mEfmRtjg==,type:str]
    CHAPTARR_API_KEY: ENC[AES256_GCM,data:jS+zsQNrRRbKUHLEiE+/6nVCuJc6bcHEjTV47jOP2eg=,iv:PByX3e5bYk5GZ+9+Hqz10e+vqRZ/DGDgS/47dqYU/JE=,tag:I1BxcfPcF4GI5TSQUNDNjQ==,type:str]
    #ENC[AES256_GCM,data:eVCIywfbeBssOzQFjPuVG8Lm5PcwOA/O8OLimU4DXXLlfImq9WfI8baeC0di4N7hfLp7O99b/vXZ3cLz2TsH+g0=,iv:OkL5OxYY7rVQDJPaIoaRcSDiBkBREkXVoKpMQ8pH50Q=,tag:G4S5amWpjW6yu7qAivSNWg==,type:comment]
    #ENC[AES256_GCM,data:Uu5+NED39DuU8s3yLCOYkUXY6aoPdctYSAfC9fD+Wi71KH6P3OU9fVfUhsnQrhqlER7Zf+mmt3QpzE7ChYnZZIpPLEjjkw==,iv:w3CNyktREErz0VXmkDXUMjqtMOH9F6UBeYuQXSzYQWs=,tag:hPS3TLFrSMhcqZtzxfJPxQ==,type:comment]
    #ENC[AES256_GCM,data:qyqsBTsVGkr2+Jv2fsWjmZvTYscDUp4ZkvcdnWyPwECTHpQ=,iv:IbDwtVoQ3iQUBaCMx2rl28IhZlk2rZSKEE08CDGHHAs=,tag:6eaqSYjfJS+bcvJTm/V8SA==,type:comment]
    OIDC_AUTHORITY: ENC[AES256_GCM,data:W2do/1F+PLzvheJzHMPr/iuV8TzGhqZzhWpLyjK4NyZDXl7Ha7NIA0fHZcAZuO3noex4n+Ye7g==,iv:1TRHr7W9/iBc6kn/oZB4iPU4djmn6VmRY8KvNkP3RBI=,tag:g4ARTKDLWTBhQFKxOMaSoA==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:fvFAGMHdl80NvMaQMMdc0GOKC7OlCnf/wAEpjF9MbwfnLwxg6Qt3Ww==,iv:eYJxFGikR1oy5bNVbEdJ/uFjRVbK+AiR1QgqhTLBG3s=,tag:4bLxZNT7yCLAmcBCTuVqmA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:5PJdhs3RSimkqPhmBu5yPuYrqcgIlLPvuG/FqQ9MbRljh8JBlQoHetl481DPNkFj+6wqG+Tr0XaPLMcUgqTe8o7vw/X7YXdEUNmbri2TRJV74oa+3TjTbktQtsbh60dt989VJTKD21gJQtvxBAhpAAmxcIrgSB0foZUh32wv/Io=,iv:Z8uCgsC5GmSydQ7ukjAMSPq4Oz6BohFjb5RFUXzmdlY=,tag:To1/k3SCujMNH0KDES6DGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUY1N5UDZ1alRGdTRDSmxy
            ZjZicVdHWWY4aTJGdko4Qk9YTEpRVG9IaWdzCjkxVlUrdjVrYTB5N0FJN1l2Tmdo
            RmxidSt1WHZiS2sxT0tYUlNzei9kK2cKLS0tIE4xelVpbGI3YWtwc3cvbUh5U3pK
            L3IyOUxpWVBVUlF6bFN1TFVtRFExdjAK56FsO8QiwHZKnrBVBVxDOB6FCw+3AlNK
            sP97B0ypRr2yXSyq9KQFcBKYZGwpgJUzLPFJj0RTxAGl/bORVBXxgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T03:54:36Z"
    mac: ENC[AES256_GCM,data:mlRVUvSfDOIaPFEr2ikpWBAJjaDiLRKDKA6ZSA+tTQM12Jw7mA7DV94z9YNlPnWoVkryxhVWKLXuOTi1EseHvcj7sgZ7DUaEIYfki1+OaXQpukJg0NZm2f6fjjFSI8XrjyJY4sE6Is8496xGdjdp16xoIUm6fcO706WKGoNRS80=,iv:78LV5oJjlUIxqTC4+J1lL/fqOrUjVj1KfuUE4DQgCmI=,tag:SjzcJjWRzCNJi+FYJ+zbcA==,type:str]
    version: 3.13.1
