apiVersion: v1
kind: Secret
metadata:
  name: cephfs-secret
  namespace: ceph-csi
type: Opaque
stringData:
  adminID: k3sfs-csi
  adminKey: AQAr0R5ptI0MARAABz+ZMk/rjgNBM9gFoxLUBw==
  userID: k3sfs-csi
  userKey: AQAr0R5ptI0MARAABz+ZMk/rjgNBM9gFoxLUBw==
