apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ceph-csi
resources:
  # re-use the same ceph-csi namespace manifest
  - ../ceph-csi-rbd/namespace.yaml
  - cephfs-driver.yaml
