apiVersion: v1
kind: Secret
metadata:
    name: gatus-secrets
    namespace: gatus
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:Q2QgS8L33ShIsKEMztPhHLkniyDWtS6zirifQJVF32COFbCJW8eN1yHlzSVpJXZiz0zp2vDDXD8eMPEFXGi6baHtaBJpG7g7PzpeMMudsJnXFB7L2xDCPjb/HvbShxRsRp22eZ5kLqWp6mLSJv7NWpXKjuYhiKGzig==,iv:0+kFYETBit25tmcmIg6MhUOKFflQuQd/8Y6X2/V42aY=,tag:C5l08ta4NDqDz/8PE6W0zA==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtc0tBQ0V3clduUDJaZXBo
            Zm5QU0xad3JlYzlpVE1JREw0VXpnc1dTdUJnCm42T0hPM1pZbXo1L0JIYWtURVds
            Y2NwTFRiMzZ2bWpGN0hUNnkwZlhSaHMKLS0tIHJ3MGRlWjFoaW9mdTlKMVhUOFlv
            MEkvcmloSmt5ODRpLzZ0RlFEQW5rcE0KYue9nsOe1liUfLsWrYC7VtdWSRdRrga2
            0XfqiNPeA0MMcxwYDwo1sito9D9xW6K/xmS9uVHOcZmM2RvEvIReUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T13:32:19Z"
    mac: ENC[AES256_GCM,data:EgrB3f8g4EhpdxMu1nVPsahfwNFjjV8qJyKPT/GatCdD0N8vw72S1i+mrCQy8nnWsJmjbJdQthu5vJ/E1pTtqmKwq81d4mlPXeeNTxj+CrD/XLuCSDlhHCvD8kTNjSMF4+D581rqxJR55NVBcEKkgpzqoImSYwj6BWGneNR2Nis=,iv:j+3c5nSLR+3AknkmG3o1C2S3vrxkUyoF7dyBzFX4K4k=,tag:Ds6Efz3XGOXxj/g3FGZ6CA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
