apiVersion: v1
kind: Secret
metadata:
    name: gatus-secrets
    namespace: gatus
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:2cvFIqUVikEmv5G7U9I+yJaLyZtey8U+XiKKmQQ29omEq2DV290jPbcBlFHUxQstpAq8MsSNkZTaR8YuimF/NOCeRajUj1yK6CKcSMQERhRcodfGRNM2l76/FqshdbSq0CF6poinhnkpCF+AF58lIbb6fpnDztg84A==,iv:KIYegjpGd2rhoicty0S8VQFRwstySm9cqI0vEmIoaEk=,tag:U4wwBXBNwEfc3dgBVdtDmA==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtc0tBQ0V3clduUDJaZXBo
            Zm5QU0xad3JlYzlpVE1JREw0VXpnc1dTdUJnCm42T0hPM1pZbXo1L0JIYWtURVds
            Y2NwTFRiMzZ2bWpGN0hUNnkwZlhSaHMKLS0tIHJ3MGRlWjFoaW9mdTlKMVhUOFlv
            MEkvcmloSmt5ODRpLzZ0RlFEQW5rcE0KYue9nsOe1liUfLsWrYC7VtdWSRdRrga2
            0XfqiNPeA0MMcxwYDwo1sito9D9xW6K/xmS9uVHOcZmM2RvEvIReUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T15:52:38Z"
    mac: ENC[AES256_GCM,data:ONBg7tgtUVeb1zxwD8q453M0vnPUfHa4MZ0n9adBTtICgwdspEoZBkx4t8GyKPB4swV1RmG3d7pCYbtpamlUhEAlW9CQuIrio3OR0wE7N/UUUQP9is658/8yVLfYOjxarX6tw+S99OAUrWWFBWp0/zPOAtltjhUGfz5hCE4oKzE=,iv:93156CvK/oTF7PNk0ys5WMbGNS2VBMhkQHTPcHKbON8=,tag:iW5h75f/Hz8T5QUD56ijOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
