apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gatus
  namespace: gatus
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - gatus
  selector:
    matchLabels:
      app.kubernetes.io/name: gatus
      app.kubernetes.io/instance: gatus
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s