apiVersion: v1
kind: Secret
metadata:
    name: tracearr-secret
    namespace: media
type: Opaque
stringData:
    #ENC[AES256_GCM,data:GuhjPRrYKxxs/hgYAXj6ZYK/xRAn,iv:N5AM2ORkpfiCOHf9iXC2hurlorlQ1fGsBVGURxMWupY=,tag:1vX/zp9Xl/owZs012UbL/g==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:FXolyC1+NCAKtR1M6amhRBzEx77aliP5V1KOGiYucYJRyA+5k1KYD2GmBunoXH2/UakfmjWuJD0nM7DOEHlTwg==,iv:vC17o0CHNx7oQMb7vgfWfFm5OJRKaSFjWhNSO1Hm9q8=,tag:rjFNzkTAnNpBtI8VyGnTkg==,type:str]
    #ENC[AES256_GCM,data:fhaSdltIeePfeZVweuOa7oRAgC7ZzKsyj+R0wAvXSqY1qUgYBPymxY+u5k8fMD7s2VdZHJr66PQ/7b+zBNVX/g==,iv:qVAEbBlIsCJfzv3ne0SXv/g4nFQ5WcnnmkqqforZYLE=,tag:LAnWmkUxnQJwALUiORkRCg==,type:comment]
    #ENC[AES256_GCM,data:7EKZoC/Zp32pvPE4XE9C21D1V5xrp1Tv9hXhX7MvRCc+KRM5jZetAp/2okzKBq04+8I=,iv:u+0DOPJ4lu2WoVQ45MqeqN11nVrH3mHJ3Hq9S0qOhXI=,tag:X7RCuDzGb4XE5v9kpzzIww==,type:comment]
    COOKIE_SECRET: ENC[AES256_GCM,data:3/RC5CmGS+2O7Fk8gkzXmtXMS6ZpuS2ZQOovUWBK2MwBBvo10wtGRtmabhUWGMKq70bN/SNoJvcfbWWd8XBV6A==,iv:6BXeMzrVqsAIj+8P42XR7o/YFbRibmvgPJFUp6AnTo4=,tag:nnnW+XWc0wlVwJedjdnizw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTlFVR0lPU2VXWGNwdGFl
            MDVOamlBTUtxdGl5ODVHZkg1UlZhMmFKV1ZnClJ2UFJRR1hqbi9ZczNBeS8zcUNh
            MEg1T2gwMzdqOHhHV2p6TjdTeFpwS0UKLS0tIExITGhRTVB2M2NRY3ZJQlpDRG0x
            Y0pqTDFMS0gvbytyWnMvMVE0cFNBbHcKaxg34IXCYHFCRz9OzunQo4iooBPZBOcE
            amuqavfWGre2YW7Cm0TaQh1lUonHjURfXRfIq4u/79Ux+QNKR9HLSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T02:40:34Z"
    mac: ENC[AES256_GCM,data:pK3pkONuAEBkaPpLbLvEYJOH2tery0Jt9EKwLVnK2p77RIXhTeaUGpom2PXKDYBGwJ4v4U2rmU4n+J40cTYL6PAgLsffgbHp5svzFQZdb6kM5V+gfqcypbxATI3eQe4mrhNKltXmwrkIhF9xWRrZWmjr7BLAWIi6ZAXyPEgJpW4=,iv:SYYNn1k6B3RJ+6uR6MhNVebSiVXgqn3/IrWYgNKyMnI=,tag:qEjLEkNKElwi0V/sFxt5BA==,type:str]
    version: 3.13.1
