apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless-ngx
  namespace: flux-system
spec:
  interval: 1h
  path: ./apps/base/paperless-ngx
  targetNamespace: paperless-ngx

  prune: true
  retryInterval: 2m
  timeout: 10m
  wait: false

  decryption:
    provider: sops
    secretRef:
      name: sops-age

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  components:
    - ../../../components/volsync-v2
    - ../../../components/volsync/remote
    - ../../../components/gatus/internal
    - ../../../components/gatus/external

  postBuild:
    substitute:
      APP: paperless-ngx
      APP_NAMESPACE: paperless-ngx

      VOLSYNC_STORAGECLASS: cephfs
      VOLSYNC_ACCESSMODES: ReadWriteMany
      VOLSYNC_SNAPSHOTCLASS: cephfs-snapclass
      VOLSYNC_SNAP_ACCESSMODES: ReadWriteMany
      CAPACITY: 20Gi

      # keep repo path stable
      VOLSYNC_REPO_PATH: paperless-ngx/data

      VOLSYNC_CACHE_STORAGECLASS: ceph-rbd
      VOLSYNC_CACHE_ACCESSMODES: ReadWriteOnce
      VOLSYNC_CACHE_CAPACITY: 10Gi

      SUBDOMAIN: paperless
      GATUS_DOMAIN: lab.mainertoo.com
      GATUS_PATH: /
      GATUS_PORT: "8000"
      # Gatus internal should hit the *Service* name created by app-template
      GATUS_APP: paperless-ngx-app

    substituteFrom:
      - kind: Secret
        name: volsync-garage-base