apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Ceph CSI drivers
  - ceph-csi-cephfs
  - ceph-csi-rbd

  # cert-manager + Traefik
  - cert-manager
  - traefik-proxy

  # CSI drivers & storageclasses
  - nfs-csi
  - storage          # cephfs / rbd / nfs-qnap storageclasses

  # Add hardware iGPU passthrough
  - intel-gpu

  # Tailscale operator
  - tailscale-operator

  # Cloudflared
  - cloudflared