apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-bedrock-data
  namespace: minecraft
spec:
  storageClassName: ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi