apiVersion: v1
kind: Secret
metadata:
    name: dawarich-secret
    namespace: dawarich
type: Opaque
stringData:
    #ENC[AES256_GCM,data:34u1A8YGNs3uDPwEWpLQAALBHUL59zPYZnCyRg6cERaQySxIkmfIni3JnLYUsYooE1nnZ+jxShWRICMG2g==,iv:zWlBY2zxj7r0bJOec9UnbiCCukwIkedQYheKCYFXDGg=,tag:cmIqTOmDVbgy1Sf5TL/jKw==,type:comment]
    #ENC[AES256_GCM,data:zDq+FzKfev/1ivyCAwmD/I3iziY1gFFKEFxhcA==,iv:PHFTqPQMp8Kl2DlKqtsAg09NCZUpQmyQXBYOH147M1Y=,tag:wMRtABwEpZf2X7Gc1GYzoQ==,type:comment]
    #ENC[AES256_GCM,data:34u1A8YGNs3uDPwEWpLQAALBHUL59zPYZnCyRg6cERaQySxIkmfIni3JnLYUsYooE1nnZ+jxShWRICMG2g==,iv:zWlBY2zxj7r0bJOec9UnbiCCukwIkedQYheKCYFXDGg=,tag:cmIqTOmDVbgy1Sf5TL/jKw==,type:comment]
    POSTGRES_DB: ENC[AES256_GCM,data:uReo9Wqg16I=,iv:VWvT3vuNqx93yyTb1PKE/kXzBqDGuRZXfg/q+lzrNf8=,tag:r7DkkBqbIAlhxk028VNqbQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:9FAsL09nbZo=,iv:PHtu/uZ3UbIjmuAjitL9G0Bkh0kT9R6ybmqVm3b7FEg=,tag:wgG56hwrPcthtaw9Tb4CIg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:On0Ao8SYjoRuMH1SSEg2GzULJTdwHcV/EBo=,iv:P+9vtPvg25WD9F177mv9gj58Rjm+wuUNER4JceQi4TM=,tag:mZObY9wBWrG+/MCZQbAcSA==,type:str]
    #ENC[AES256_GCM,data:34u1A8YGNs3uDPwEWpLQAALBHUL59zPYZnCyRg6cERaQySxIkmfIni3JnLYUsYooE1nnZ+jxShWRICMG2g==,iv:zWlBY2zxj7r0bJOec9UnbiCCukwIkedQYheKCYFXDGg=,tag:cmIqTOmDVbgy1Sf5TL/jKw==,type:comment]
    #ENC[AES256_GCM,data:cu0J363npqO7E8M61b8MMDJByUg8GOA=,iv:klmMpPnOQubzFnuLF+WnxqeJ/LdY+41EHD9LO4eBTRQ=,tag:x3Z3p4kKJHyFfLFgm5U+PA==,type:comment]
    #ENC[AES256_GCM,data:34u1A8YGNs3uDPwEWpLQAALBHUL59zPYZnCyRg6cERaQySxIkmfIni3JnLYUsYooE1nnZ+jxShWRICMG2g==,iv:zWlBY2zxj7r0bJOec9UnbiCCukwIkedQYheKCYFXDGg=,tag:cmIqTOmDVbgy1Sf5TL/jKw==,type:comment]
    DATABASE_NAME: ENC[AES256_GCM,data:AaOebbRCKxA=,iv:Vm8O1S7DrUNi+vFiJf5Vg8DEbvurbuVBO37otPP2Av4=,tag:8SoZ83G8Z4klFdpeq4qAMQ==,type:str]
    DATABASE_USERNAME: ENC[AES256_GCM,data:984/A5kuDfU=,iv:/188Du0ltxoRz9WivtkFl2XxUTxzBNMUCh25ewiTnrs=,tag:BZxhkOia7DDV2xYku5O5gg==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:PO+lzspLR6XD6r/fd6iJBrGim8H8ZF8QONQ=,iv:gaqVgMNWDPuQ5SiM6UFjMcQEPGeM3TRzbmIvwP/fjTY=,tag:8w2cbHC7blVXL/iFyHMDfw==,type:str]
    #ENC[AES256_GCM,data:ybTmCQkCZrGElG8QVhi0MJA1/LMzgg==,iv:m67rGw3p+oZOHj9mXS2jRJ/VEgIE/ntmbDu07DH5QSk=,tag:okoDhBP0SALlcWaxspWWXA==,type:comment]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:Vramg69QdsRFQbLxVeJYSt9QgXAU/CV4TpBD3WaS5ocTtL4HYI29d5cNvmv2I2XmBE6+0H4NEjOYmMawnzlpSg==,iv:G/mBTp9sSVlTbMRH8QCcYat0qmHGrDFXVEd98M1twCs=,tag:sfXNEuWfbZm3zcAHs2loJg==,type:str]
    #ENC[AES256_GCM,data:MRaGf6grFzZPjhXWzvtOaj+bILaAO2CGOdnofX4/HxDWziZwheMBaWThI1dO7VlQm0It8w==,iv:zSWRoowq8ktjO2NkpYR8h6IDP+vpgrdrEnfSAuY0AmE=,tag:uxsC7NpU7FddTP0k3um1Og==,type:comment]
    SIDEKIQ_USERNAME: ENC[AES256_GCM,data:EPbtIBQUDA==,iv:+YngiqPL5YipGiPQ0Ck1i9mUSwnaTu9Y3Uz++z0qvtM=,tag:N0wnCZ8FBLSr5aFaWvbKXg==,type:str]
    SIDEKIQ_PASSWORD: ENC[AES256_GCM,data:N2vfxzcDMJ+xetDX,iv:nkiTlgJDY5X1/T+FFHLjMKesy13nKZX80iS0sPnd4m4=,tag:BknqpeWVRnyLd1Ue3N4pkw==,type:str]
    #ENC[AES256_GCM,data:34u1A8YGNs3uDPwEWpLQAALBHUL59zPYZnCyRg6cERaQySxIkmfIni3JnLYUsYooE1nnZ+jxShWRICMG2g==,iv:zWlBY2zxj7r0bJOec9UnbiCCukwIkedQYheKCYFXDGg=,tag:cmIqTOmDVbgy1Sf5TL/jKw==,type:comment]
    #ENC[AES256_GCM,data:HgUUWFk0f9hs582CVVRUBP4=,iv:EMaW7axMst4ImXfnIHaUqrtqwd1W2mzuXL686bbS9ww=,tag:WKEVfFRmdvOEtDRwoKMgEA==,type:comment]
    #ENC[AES256_GCM,data:34u1A8YGNs3uDPwEWpLQAALBHUL59zPYZnCyRg6cERaQySxIkmfIni3JnLYUsYooE1nnZ+jxShWRICMG2g==,iv:zWlBY2zxj7r0bJOec9UnbiCCukwIkedQYheKCYFXDGg=,tag:cmIqTOmDVbgy1Sf5TL/jKw==,type:comment]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:JN2f9r5/YueAB7LcjGi1Re3we0q3cN/ElW5L8lMsbFrmU+d8XaTtQA==,iv:r+RJrO0x8s2G+pp5dvY79nlUcIKAxh9a4ztaKZsc9n8=,tag:SvJ1f/qIItSk6U4XxDLxWg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:uuTDzqVGimyKASJsP51G3oJnhraTrYJc0Y6JvFmOwnZGJLQjq8qLfyVm4k0rVhFzdMfgBcw5ZzAn5rXUioxCcmm1KhqdnpKe9w4C6AW4wj478KYa2ZRSiaYkuOC+2rsXvCEj4Q9kDMhkfD6l/LKRB30eDfsPT7KIp1WrQ6/V1s8=,iv:BKasQ1akGpDFfSB6VTaQbtX3c9xOd6cbeOekZ/tS5Q0=,tag:9bzCc1xPDOcFsKc7XrdYqA==,type:str]
    OIDC_ISSUER: ENC[AES256_GCM,data:ZZdOia/9H1DtFddl7EUttHv/Wpylh3VbdWYV/6wjJIqTtARXnM4zBBkIWcd2SgyAHR6zZoMiXUe3160=,iv:LH5FAJu0+DDB5/AWoK4eNsDbqOog+QlrVUG6m1IU0Ao=,tag:Mbv9XJ6SU7emHq+HlfuBiA==,type:str]
    OIDC_REDIRECT_URI: ENC[AES256_GCM,data:C+xjb+EI6VL1WB+l3doKBRk38Vtec1g4cW1uS4Z5lmMyvmBqtTNK5f9dgIMMCBFCk4eHbhpgo4CU+Hfgcaf5PN+uqNxO,iv:Bu21eEo3JcMMf24DfrcpC/hvkcY4NqGzJr115E5gYuU=,tag:Rg2rYpRQCc55nORjgsnImg==,type:str]
    OIDC_PROVIDER_NAME: ENC[AES256_GCM,data:/IPjsEdTWVjE,iv:e+p1alndeW7BMIHc48FxS95yoDAC0zUf2NSrRv3nZzY=,tag:Leh8XxkiYblYeEnB/uKLKQ==,type:str]
    OIDC_AUTO_REGISTER: ENC[AES256_GCM,data:Lm4OMg==,iv:5vADr9JMZ3Speboiv4PiFPiVwOSIzipEIAxWoyFa5Q8=,tag:hSOwrfauNafg3JYB+arzMQ==,type:str]
    #ENC[AES256_GCM,data:jJPuPkGa099VMGSnEeCJpC5WHBb/KgeJGHafVkmC2qkvMEAHsmTL7g==,iv:M07FVe8QxX0QDRAQi3NhqMCUv/K++FsCYVzrnq9QsmA=,tag:RAfnLT+DepHvqo0pvu5opA==,type:comment]
    #ENC[AES256_GCM,data:pupGvNxbD7zaJ/CUT4alZXft2M4gMyQdm5SD+4VNcNlt+Zn8i/eeo38GzgRaRGWGouaqG/I364TtSEsv1fiTFcrZ2Kn/0aPHVuwKembmqEn3RTZqQA==,iv:9sxyx6wcSNdsd1hy4rOhM5k99a/P4LmbcA3l5bWcTmk=,tag:Zo3ONFN8S2+1dokyoo8UoA==,type:comment]
    ALLOW_EMAIL_PASSWORD_REGISTRATION: ENC[AES256_GCM,data:VkfbZg==,iv:XUTW50Dl9DmcaHugJjLQqGb5GN0WTPmmPHpnm7G4PDo=,tag:aO2WHQJ4V/iu04T/7klVNw==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNGFJU2xzM0F1Y0VUVzdk
            T1JHM3lPVjQweURUSmVqZC85YmdleDRqTTFFCnlrdStZWGRtV1ZkejhUK2JuakNU
            YTc5Y3lmdFBGUVVyUEZwVzh5UHFYdlkKLS0tIHU1QUV6YXZxcTZOSXVGT3JILytS
            TWdqR2FkMzEybElVNTc0VXY5KzFvMGMK40lFlxLapfHKJHA3r8BlDNw8jbyNBJ+E
            bOaQ/a2lXVd2vvCnLehzH22eKhaxzdmJMsLnW/WL3kSqBR1uMV3ZLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T02:14:03Z"
    mac: ENC[AES256_GCM,data:lgfbmrSJLx6kdZfJLPn6RGarKujAtCPj0GjqJ3cjpyhnPNm20aITo6Wowtl/a77N4YBSaIFVNykpUo8FdUPA91XUWjYW5CPXruxP6a05Z33RV880wDrgdgCML9Uhc6Ukti2wCrj//5N/EVXcj3oDbUmO1b6J7VeLqfdZuKvT45o=,iv:SD4V8M8JzIObYR2KD/qYwwSoAcqzR8ij4owBaK6IwaI=,tag:3pfrCnMoINztzk3Le5V8GQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
