apiVersion: v1
kind: Secret
metadata:
    name: cinesync-secret
    namespace: media
type: Opaque
stringData:
    TZ: ENC[AES256_GCM,data:Ua5KPbldgqdwacY1u+Fkf0JtHQ==,iv:OREuhAKXNPqEZzVmgHYlKVq2/r8fJmLYwnSQ7tV6mOo=,tag:KCb274+oWSf/7uLrRHNCtA==,type:str]
    #ENC[AES256_GCM,data:ggraxqw=,iv:7BhdnqLI6pQh5jp/81VL7T7EXUbuMOjmsPSgw+ozPfY=,tag:1rkFUtCh1B53MWlq4WBJbA==,type:comment]
    TMDB_API_KEY: ENC[AES256_GCM,data:bDCkNMWu3AS9mxT4MzmSwi7NZOHvsJzSkvkxLBNh1I8=,iv:S+Q7CKUO7vt2oRuUYrLqKZ/ZM62HNzUYFNINXX/wlSM=,tag:/wOme+vomE9J0DYyuDN9mg==,type:str]
    #ENC[AES256_GCM,data:4XjGswAZ2Xnq,iv:dE1/dmPAnLwCUXXVPLMl4VLTkZJzZcQ59ycDBFKOhfc=,tag:0U5KqGmEkOfzTv20QCFpnA==,type:comment]
    #ENC[AES256_GCM,data:etcDvssRs0pbizm4tGrISdBBIselbS70ZwNwZJEtG6MSAMuoxEV5pAzy3+wiIMRVlD81oGw=,iv:u+h0ryLqkkuUEbeVxzXSBILUNYZ/GbZ3jbve1TXgHHo=,tag:XamgFK56eqyqlgGNfnLAnA==,type:comment]
    CINESYNC_AUTH_ENABLED: ENC[AES256_GCM,data:fPcxRsk=,iv:85fQ1NuvPFHsH5sKeD+6o/ZXBcEHUEvvK9mNLZ8uIMY=,tag:MR8PahU4sog7QhlRoYgyqA==,type:str]
    CINESYNC_USERNAME: ENC[AES256_GCM,data:QjXSZIN6jhX/,iv:J9KgvU3WC7UtsjK7TU2G+tZJrEaA18/ZAgspHKY6eFM=,tag:jWh5jGhzsghUKfkJkp3jsg==,type:str]
    CINESYNC_PASSWORD: ENC[AES256_GCM,data:BRAy3x60CCFinKL9,iv:wzioYrpAGgE+TLPzI49CNvqrEfA8ia48tRJ4Qc4aGxw=,tag:H9B7B5lhax5VlRRrh4O3Dg==,type:str]
    #ENC[AES256_GCM,data:i31RRXPOKIu4QbXBZpDDzZovWd9WVls=,iv:1LSIpZQwvSYFXfupZfl5kC+DBERlWD06cFxjkk0xJec=,tag:TeWpym8pKlprfmtY6WGneg==,type:comment]
    PUID: ENC[AES256_GCM,data:a1keVQ==,iv:/Yy3aIF/ahqIK5qXOwBaV7jQPMAL4AbKoV0R3FrMNHM=,tag:/XJZRcWDS6VfHVBpbiZ1fQ==,type:str]
    PGID: ENC[AES256_GCM,data:3ttAyg==,iv:LxUMXT3gGdPlFGTQko/MGlxUrTgMR+jTsDuHP0dI34U=,tag:BXbU4pBHw0EoKkW/PhU74Q==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTVN0ME4rZnZGYVRyQ1BP
            UHNRU2xBZnl3VXYvbENJZDJmTE9OS2swakFJCjg4a0Z5Q0tidHVEUTY0U2xJN2VI
            QWtKdE9paGNEQkRlR1VBL1JGcUJ2NGMKLS0tIEhxa3RFVGVKVXc1M3FReUFWVVI5
            M1cvQUR0UmlXTVZuYnNhNU9HZUpiUTQKz+qpbxA+TuXTVusLxD88IWSgPVgvSg/g
            XhMzpdhJO5O1jCrbbj8E8JuXGiDVEQEBW3wvqpZO0CYiUzEDVRxhxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T04:31:40Z"
    mac: ENC[AES256_GCM,data:+GZj60QKt+5YQSEqT2pLvC7PBz6gxb56vsDVq8bBzS0JuQ72Al4lSJob5sYZBVsT2HAlqqYm700d4zhi46vDKw7aJyouKfe8i7BAOBwKxa7ltz+8GxL+MUcWpninab5l0NOQeH2DwbMG1XQqCpfVDyT8Ch7pTO2O+hbX/IXmLaM=,iv:by8QFFJRumkfhVlZXPLABRV+zk70cRhkQXxy6g75d/w=,tag:0U8RPm9JIzphvPnT5uwWgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
