apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - cinesync-release.yaml
  - cinesync-ingressroute.yaml
  - cinesync-secret.sops.yaml
  - cinesync-pvc.yaml
