apiVersion: v1
kind: Secret
metadata:
    name: mkdocs-git-secret
    namespace: mkdocs
type: Opaque
stringData:
    ssh: ENC[AES256_GCM,data:pRJYsW2ZrS8fq/TBV0pGOaGfj4t8ECUmW8s1d0GsmGP3lDafsvSRK9CLKn8lXFh03y0DRioPeArCl6jDGZ2Jwi799VT/rPjrNbJ6RTlAosbnvJSxRxmlP+qCxO5FEd6lzQ3OjwiUeGDzIFnsVZV94vfpzGWnwvdgNoj+tosXLixOTeUyThC4hWPEqC5thJyUncycBcJ8xCbYglwZNJ99bXI9kqQCLDPmLwr3g1ozMXohht12qfxGSNpcc/Frq2nuJkau/PeFIQsnMlQesjdFmvjWn07QOOAETJUggUqmkS6ILLKPt8IS4Om8wJXy7h+HN4wbayQd9mJEvK0Gi38s86YTFKsXQaQXXMQZ8F8gQttDIRzH9P7WvPgO2QkvrAunAtUzHaXRYjOnsEwQUf2ahoTo3FM+tS5KQcP8koJ4uWMHKL1dISb7g/gtTQk8+exgxSZ7JLWhv4Ld7NV58ZXRNl9BdMKLCcoFfpazsRL14TozOeNXQ5pY8x47BXzIfzCcKn0TKBkFC/H8FK1GPaoV+G6SQgU+LUOB6i5ZRlKMKkxH4PI=,iv:b8KP4Q76mwsmTPJGDJCIgwuNwDXLTcNg13HU2vaaX5I=,tag:EZQR3yt6jssTRcc82A67JQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:bEn1vA7WTC3Hv9w4b87svTonuaVnT0vvw/PGlOxKlblnoRpo+9qg2G647EwPZ68jnr8RGJW2VPnoC2bEEF0Fyf919ouUWK9RfEdXIZJG+GJlbbrDdyK3vTnYQwUP6Dv8dMHDdJGafx6tOqtXK2kqePD9tMBHqeFMIhGRjUTXqTRK+JYC3UnD6QhaCjj3M0ahC19ENXEHGsMq6gyqIkdY24ExO+/qyxS6XNfKDixFMZNt1/zRgAK68IhnFPEUGd0YzKq8Ft2YScQz+nPaG8hGJe9o6Qx5pBlOSqoTpuJFcQdLx292VkeHG4+hwIJ5rco2x88JUzpER25yqVIMdgYuG3A42gdG9/tXMN/Wbuc4MH8LSt0dst9YxglLrcNiD/8O4X0xw2xiUdhbjjlHMjoCZXzSF6yRW7QHfWxSt50bFMlB3Is9QTvbRbbGVHNkVVYUjjuxsJKTEnZj+rgBJJgMGm5Fwl/DuwfSI/+GfwnvwfDH6jeWyKe6BQK3jVF6KxoV+jc5GWXp3//XXgdYSbtX77t6VoYKKIy05cFmg0IXljdiYmjtKd49zooGb8nko/uxJVDw+Dy08zjKjh+puImTiA2Z9X49dum3CVkLMBzKw+TIE7wnHLTjem7iyLQu0HavIMpMw2rNyIuTfmYCBtjhEVmqsWEwXZY9NW0jt3h9EWh3Gd4Bz3/RPnQyV/hV1tXtA9jz7enxRJqffz4D7AR7ruGIE1KSFdszFmjNSIyJyabPjjcgQus/avoOpVsLx6D0KZyEKJNUkSBuef1Gee2I0PDXeabsvBXgxJbpsIcpk4Pj6YIyVOZ7f0Tag8xXT+0Z+j+MAj18HFt6Em7JN0SqhzBlrEndK07ooH94jOQ1tjZ2JUgX8OUE5st3KgTTj92Pvh4kt88OqvWrCpMGKRYoC90vKA8YtOwCvmK4FJ+keE3w6yk3BmfU3jJxcn7jYDwq,iv:8yPPcyJqhXURRff9KjZtwx/vpFKylvZNt8iEQoFlod4=,tag:Q2RN4cjERAR01Wg5w0kheQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwL1RuMkhxcHM2bjJUQTNO
            NEl2eEJFeFpiRy82b1FRVjVrbXVPendabUhFCnJQc3Y4aWZEZGpMQUpzTWlnenRO
            UStpck5Qd3VrUzgwalYrK3B6SSsxbzgKLS0tIFJiajZPUFozZjVKSlh6cEZlRFdz
            UWkzMHhiV3ArYkFObDVFYTV5aHJ1NkUK7gOycqZfJXmmyCseOe3AeJeum/QVdiB9
            M8+aUM2LsN+vPCiUSXWwobBN1+x8AQqRUvAxBZM5iGxP2AOepPEoGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T20:51:28Z"
    mac: ENC[AES256_GCM,data:lwJ2AhtbXpCWmkwzfIoi98enbJkH+2IyBWY7PNqaN2EduosvA6HqOVPD1p3kiJF3xiUg9h31IChCQD/XBg1M/cdonbtsv3XTFqFJcm2kjSPO9xcBEyp+dnI2cFdNgZnYT3XZqzNNOLCuDkf9vsC83l8IazG0bR8tGN12achzGBk=,iv:E9G0vATHDSNbz+epWYPdI56rHGqkj+yOSlDpF0GqX2c=,tag:l3QBenZS/q5OmXIqZEtkTg==,type:str]
    version: 3.13.1
