apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api
    namespace: traefik-system
type: Opaque
stringData:
    cloudflare-dns-api-key: ENC[AES256_GCM,data:TOhejJUe9fFBY0otkjW5OOEylwWOxK3iawz/s5ZSHGW/BYj94hRKIzyP4AUHiRKY3WhU5xU=,iv:IKxPIfzpJP8SYYU84W5GjQlb+qPnBWPcZsoZFfzGZWA=,tag:tQ6dsW4N9bo3NjFxyt/S0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWEhTTFlWNDJ4ZnZ0dmRo
            RHg0Um1ZYzVudDU3eXJmUFNQWmx4Y2R2T21rCnlWamY1aHJrMi9FVHEzdGNkTzcx
            YzBTclBZSXlyUnlObVo0bitqVXF6QVEKLS0tIFhWZ0d1N2grYjlybFJOMkxiRHFI
            c0E2WFJJaXJuVWdwRVUvUDZmMFRzbm8KxUTI0vflmKO/NEjmVDOoJNNpXwjtnjyJ
            jKp9A9pVCcEP3H6+ii4G51rtCmLXz1Fvvws8jHqyIMn5pWMp9IljHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T20:38:36Z"
    mac: ENC[AES256_GCM,data:WJ3eJ0iQJT8BHRHoBCe4LtkEKLNwa0dblFnE5qWXgsI2eHGieWhME9p/+/lfhZ+JLy2OdLAnUBpFEL16JeUlWXJKvfyocztS3ltj207Qdh7Tn/UYDg9hmLANCt5UOVzGekiu6Fxf/kC7gBXqoTDcvM8xIFtrjP30vPcSdt3+7og=,iv:wag5mp5w3wwffuyogE5ABjLrvra8HGwmpH5z9ntZ1Gk=,tag:4HTCwJNyk1gVPXbk/RBGHQ==,type:str]
    version: 3.13.1
