apiVersion: v1
kind: Secret
metadata:
  name: gatus-secret-vars
  namespace: flux-system
type: Opaque
stringData:
  DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1462076990441128198/UP154KHwX7Z8uUD-jbyVtmQKfbK1gTBZ7BDNxQNWy0e1BwQawDDSrSutGlicQ56NEdYs