apiVersion: v1
kind: Secret
metadata:
    name: volsync-shared-base
    namespace: flux-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:ixk7wh2oPiX4nO4N1tOwzxLV/0e5NjCaARYKfmSSvNNj1EiM0Gm2gmARC/0JWmFancOxyarPXWdt2NgdVWzawL+gbAWRxA==,iv:U0izG4XUkh5GFsKG27U89gV7Mce6pSC0QQM+ncXyGj4=,tag:lWEs2T0OUcLSosQdof0KuQ==,type:comment]
    #ENC[AES256_GCM,data:eXLudGe+Hc8Q3cdyMqOO7SZ+LhEsPEWij3xMgHvwdFfZAP+29V/xATxPp3FOu1afUxjWeZ0GWeulRQV7g3uXVDCzQQ==,iv:uKbi/MUN14Dy6OPhnr4k+eJ/fiCTWB2lfwAYEdZNcZI=,tag:KQKFpgX7BIJriu7kOblLBQ==,type:comment]
    #ENC[AES256_GCM,data:6mcAP31zob3v8Xc+44rq7iCRj4R7C5p3XX6fdwBwLyj45dIBwDfXE7TRszUzAwLrevmlCJ6YKqESs/dU0jkOGNlmMFv1eDQoKXhs1A==,iv:YMgBW0/fdJ6/NpoT9Om15FkovNvGO9LOEr6kphcrZvQ=,tag:gLJz3/xTz/X9dMl8CHX8Lg==,type:comment]
    S3_ENDPOINT: ENC[AES256_GCM,data:BnPjee+rPws5dAv7SL4g+fvx1ADuzSIuadt/t/DEfl4=,iv:0Ftz3YmsgC7lJHied50bKef2fumA1u0Pbkf0Z42xKys=,tag:yDpjoGbGXTT7nO3XQvg+iw==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:+26wcDNyZOyLCR/PRKU=,iv:KFEDhXuK7bqsQc5IOtIiEaSKApE6OD41GSaV47V0pN8=,tag:LhJDBwcXmycnmv0ULmeF0g==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:wZ0MJHxVmjj6,iv:x2Wn9EPLmA8OG2uTHnNo1EHzLOX16fEFGC/bvEWm8qM=,tag:gnqdIyqX9cY9NbUsT1EKvA==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:fWhcSL5HraaS,iv:lym2JVMPAYZmNAumCGJz1sdrT5y4FswuaKtND4edw18=,tag:CO8c/7ciE4SLxrJ8Mx+J+w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:mqHDlMfpUq9eHio3X5Jy+hE3QsL8S96e3Rk=,iv:XXo7sR2XVmK6eYAI55Wb5HxANxJ7uTatW3rvajkw0h4=,tag:M5J5Rj846V5KoWaLUm7VoQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:mCgmke3Vl9ArJ7th2ho19Jg0i5AZm/Q15ibBkAv3Zb1uA/JhfthZivwzT6E6oo4Ly52RovpZXMyn+MPqwuPd1g==,iv:bxVas31VmINQmDVQfLuKNeeIF0c2cGU7XDdffJZH4Sg=,tag:pVcIF49mmI9Ji7lOnZXDhA==,type:str]
    AWS_EC2_METADATA_DISABLED: ENC[AES256_GCM,data:VG83DQ==,iv:p+6X42igTHIex4to4r7spqWN/rhicwDj9FIfV9nu6CA=,tag:TDM5hCA4mYgPzw8bVGlskA==,type:str]
    #ENC[AES256_GCM,data:B8trRVsu2Mg/6T5ScnF0e/Oa15GKfsyiEWvY09NNHddwP40BaUG9Z49n03xjIN8Bz5aYJTkP6lni9poTO7nzqmvNLjdzSl5Vis4=,iv:tKg03GT7hYIcHTyZiOPvh5ayc7Lfi1i3v7y3Y+8bY5Q=,tag:lE9Qwx3VDF4kVqB48eEi8w==,type:comment]
    #ENC[AES256_GCM,data:UvCg/tWF9yxqy/dbs0Rfs+96j/SkmRJoDP9UVmtj5rndEPvP0HBm9B2eZysNs6+mmSm3JefpQ03Tzrb7slbbg/Y06AbvcqBLmQk=,iv:qBzXcUB09S+/1Z40YzxRYb1pOEYyGudeyOr7CcX9GTs=,tag:unF/6MdTVejkIZstwqVzTg==,type:comment]
    #ENC[AES256_GCM,data:Plts2fIFAYb1NklDfX7GBG8yjidUeeL7LHJci90mlJoxV1wDTjNcWI3cs/w3UR8na8/6e6nywAJqS0wWyMUG06RsPLpct542,iv:Wqw+00RQAxorsL96zLFGXcRbKqZcP3hkAdeSKbuJLNU=,tag:cMFvP/5GOFu6C87h38y+qw==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:2HGODs0UyJ5JRYiFiWZRhJpFrgbig7OnnYb0+lq4m1c=,iv:l9miwW/r+dQDMhI+c9q8TdCYaafXPRDRQakayg4Roco=,tag:Vo21orWP94TTciyJ/YzeIg==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWE1lYzBNNnE3RlM3Wjl1
            R1pQTytGMkp6KzhrZVdrQ1R3aEZBNjc5dFVzCmd2UENINVVQMEs4YzdQbWFvOWhB
            SS9mTEQ1djNXVkFUc0VBL1VheGN4YkkKLS0tIDh1RG16SGE0V1E5bE5ITW9xV0Ja
            S2xtaThIeUhSa0V6bFp5UTRMV2lBRFEKdcYBGV97Xc4dUxXK6SOwJX4dODS7QUQ/
            mtcwU2ElCTca3iPhfHujkUqX6ALlveun6AVwzj1x40RZKjq7fC/d1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T07:04:52Z"
    mac: ENC[AES256_GCM,data:HgM2ywQ4klkQ4pjbuBPw22h4BEoS3nxRMS1PGyFXLzqZyWlhSQUJbH4OogwhuHaq13PCty25aWn3N9navT3hZoP9KvHC80AAp4ZtmHnO5XvwtDXppzrrQ/g8xNgkF63T793EVNEaVh1wLoSARcLCnKfM3VjGdRI/pBbRIvMuxIQ=,iv:msDbcnxC07rST2of6GewJJ5/zrTvJa1PVNO0yJX7rFw=,tag:rzv40SXNdYQyTrNVb6RVrQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
