apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-csi-config
  namespace: ceph-csi
data:
  config.json: |-
    [
      {
        "clusterID": "2b142655-7791-4f14-8934-0ea16121b652",
        "monitors": [
          "192.168.99.12:6789",
          "192.168.99.13:6789",
          "192.168.99.14:6789"
        ]
      }
    ]
