apiVersion: v1
kind: Secret
metadata:
  name: ceph-csi-rbd-secret
  namespace: kube-system
type: Opaque
stringData:
  # Ceph client user used by k8s to talk to your cluster
  userID: swarm
  userKey: "AQBCTpZoVBXTFRAAjOUYCZg6mlgVJafK/j7zNA=="
