apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - helm-cert-manager.yaml
  # - helm-traefik.yaml
  # - helm-app-template.yaml
  # - helm-authentik.yaml
  - helm-authentik.yaml
  - app-template.yaml
  - bjw-s.yaml
  - helm-rancher.yaml
  - helm-rancher-backup.yaml
  - helm-intel.yaml
  - helm-kyverno.yaml
  - helm-descheduler.yaml
  - git-firecrawl.yaml
