apiVersion: v1
kind: Secret
metadata:
    name: decypharr-secret
    namespace: media
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:oKJZ7nkhj5BFrzy+QPvpoTTGHzNYXkX3kEgfwEPAarx0+rFCKKNjeGY+eBNKyqzsoUW1FO/ihyEpTd1+uWdMmdn+vkhVyXPsI8ao+Cgl24r4ZmBRm6ql5Hvyy8Y1oftButPxK6vnpflIcggslKMB5EBoN3NhebO5ArhXBctw9AWG/WWmOKjg12oERDzPPn2c5mqg14mRCQFZZ6EpVmOPmiGAInvU1yycGBfjDFG4Mb6Th9qwsg5jgkoxjtecvX/z/ZzfzCVnHn50WOywXAxqCS+ADiYnUgXfv9BBBWLrqlYUPV+OarOOhnDCwQDnyl9i87Sap0sLFdRVTxQKZKiYIHr23J5IojmEtVZHZyLBFl8DeJH5FCEwTEIwzR/DyX2MiDPjCSHofwec3dYNJolMMiMvibKjAA99tEb4wYXeKv91603TGRPQrmkeHsdlSdjxBMEhOJchv+gXOh04axaV5oStV7imIPawmL/qLrXXhYz7H8cKZKS44B8Qe/nWjFctgF98yTV+l8wwu1ZTnctMIOYU45XRYVVQ/KxBYb9on4I6822i4HHNqgpBhyycCo9usjsBfWJJSxDxK5fncbUTHFmO9jXclFVtQrjryhqBb/tYp8RU3dmq/CxvqKCcuBIXr/Km8Ny8bRtJeGHbMqw0qZ0Tm1U0,iv:KQqbLIUqvB5QdFiWn0idLlZtZR9WmXQAZAbRSPIKy8s=,tag:hFs396+dJVhu6VHU4OQpSw==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNVJ0bzhIYjNpYzc4Qlpi
            bndWb3hFaFozckFScGQ5L1VKNmg2VUc0T0dVCkdvK0wrOXFaVTMyWU1rOWpDRUlO
            bjMxUmQvUGY1SlV6VjhyYXc3d3pFNDgKLS0tIFFuNTZCYjlLNHI2VkxhcDhqK1FW
            QlAvU2JRM1pvMWc0NkVtNXlWU3JHKzQKFlS4qriS/hlIuQs6VmDz41fO650ne5hy
            S9g7aDGliLRh+900xkNRqXlcsGmnC+LQ1F8K+Ll2PZjBgnHBV2ygKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T01:40:22Z"
    mac: ENC[AES256_GCM,data:UPk/3z/Np39ULLL0gK1TwoFzd+cVyWI9NBFar2jwjlHOgqZjp7InNI7uW3YDFrvFy+jaoEUAZnGujEBUTkNZ2ekblgErpLb4qxPYW8DSw8ak60x8efjErHehybE5BQ9YBMPYOnCtZGV0BX31TELoZqL+T3kMnqp5hJa54oj30aM=,iv:DkSCIIV2Qm2UKp96gbl1bN/EUVQBr/p9Ry9cDhPADZo=,tag:Wd6HeKvk8Uyu0DRxnZrB4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
