apiVersion: v1
kind: Secret
metadata:
    name: decypharr-secret
    namespace: media
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:r+UYs842Z0/TGs/UzXHR6SHTQK7m2hVhpHbEqcf7+320WgdQ2DMKvTkliBMcOxk9GXStKinXh55GAMob3aK0A1TbhC7w8ylnwxQe4JaHBUcYLa2cFzMw4HHOetxh0+iBNFYjiH61ZlF+RdQFbxc6P1SXWDv3J0mN34wCYmFCCKnxR3Fqh0kt7zEdtbFRMh4CT2zQFxNhp/trOw+m8tmhYERmTR1cwPBJa3/6BniISHGm41RrYZvqtWN4lCtf1MubuuXAdB7Fo7PaljuDtbgdxXRgfu+8NJvRPH2KE3aIveFrCQV8uhXgG/0r46g6vLkIxdRGgcdDCWRpBKJ71V0LpMg9x3v37VUgOmUk6RLGOtytPD0VstJd3poRIMlKKMdp64Lj6BFYCKswg6rDL5m0/G4JjwqkT5AQGKuUmLzhz37It6e8obAwahY5uLKe9gk4uHwU93ALtIvjhHrkW4aLFknvL5NH8lR6Tc268MCumSaCIndF1K1+Hgt8fuCLwSGXFiUvpIUUdy/7YYpa625I3UG2veqbitoHBDjtotqbsr8PqjLkXZ68CZcg473b4IlmxSWFaasoOHhrlnssDQLJwnVnxzkSZAgvgsiwDnJ4DpXo9FdhU1bHJf4R39kzrOwFCL7N6mQxy40DoVDqKP5yTSpHmVdVsNPXegHtOTXedj1Q1xU98FmJIY97HjPEsvu+YhN/l9bZ5mxGGLVE62NBNdxJA9hP88zl,iv:vomGfO3hQiH31PJUYh2WYKnVp3JjMJ1ebps7+Ps0J0c=,tag:oz2ICeUhnWofH+9wZZjnLg==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNVJ0bzhIYjNpYzc4Qlpi
            bndWb3hFaFozckFScGQ5L1VKNmg2VUc0T0dVCkdvK0wrOXFaVTMyWU1rOWpDRUlO
            bjMxUmQvUGY1SlV6VjhyYXc3d3pFNDgKLS0tIFFuNTZCYjlLNHI2VkxhcDhqK1FW
            QlAvU2JRM1pvMWc0NkVtNXlWU3JHKzQKFlS4qriS/hlIuQs6VmDz41fO650ne5hy
            S9g7aDGliLRh+900xkNRqXlcsGmnC+LQ1F8K+Ll2PZjBgnHBV2ygKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T21:28:36Z"
    mac: ENC[AES256_GCM,data:QYK4CVYd56YJao8tKj7YXFo2QqtLFf4nMt0qStbEyrS8TuJi4p65346Q5rZhSbPV4+2UQgT6Q13kzb/ve19EOSQ/gpu80bQQP2LnfE+W+aEl+8I0/IYzXz9oQMvLckB2f5twbkBDKodvDBhfcMu5+g3oiFin4P6j9OW2/sZC3lk=,iv:RRwqyxRrHcPcJvnnVfgvAUKXJoNrF5RjOhudyZAIQPs=,tag:CpRqWYfiE/QpVtkMxKRWIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
