apiVersion: v1
kind: Secret
metadata:
    name: decypharr-secret
    namespace: media
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:kF+ELWSEKhUW0mt/EpYj+1EwLbimFl5hgvQVdFvr11iUh7bCBbtwqmpQqFSYQG90DCHM5amCbZsP8FgMx8YBzd2bg3WEWFTxfbgiWCEScogw1Vutfed2bewjAKT5ayKjeOQBrZlamBqhh94GUixL2mPxB4djddvD6D9jpFDtycPR6BgQFhyBg6BCBMNR3xre7HuLLV1Q+MFbZpB0oaSW0w+HPHVm9ezYvpKjLEzF4uFbfjufzaFPf6B/ovmEdATXhPzOvUBt2K01oZWu7qiBPj3d9iU/3frdCTfxiUzEAzC8cz8vDwxIchJUtWyewYxVW2YfvsolxMPAefcUEHbtr9A9c4fRfqv7lB3Is6dOq5qShbwpeVZzXxLlDAeeXMsKQAg7TX9Ei7KWX2V/H6e88dlI6n2thulYjTBsOqOj0dum81Fd5+ThCwiHOTsFhh8Y33Y0ZTxJfXeb+oWNhoZs6+VABuP3ylb4UHoqqGKwPbly73qpbj6LFndAmpq9W7e2dfXBy9r78aoH55mcx/IKWSpi1WDqo9TALLAMogzoDvYY3zodUDCS6TyLmBl8nGFoNYgoWKGvcVB/2vdF1w+SdXntUkME/oz66zI+9Tb/nHQneYUtB81OPE1Mjvjb4/NuosrS0iSdv9sSN1NtnoH024Zm4skXnhWKjS1Tc22r8cY6q48f6euy8i/2ZFHLX0MxrSRAtOLJ45ngvQ==,iv:Casgmo1jnk4SBWNAlyFxAEVK/JNuFgS0JtgsMpp1MMc=,tag:nDW//pwX1Vl1YsLsnkx6VQ==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNVJ0bzhIYjNpYzc4Qlpi
            bndWb3hFaFozckFScGQ5L1VKNmg2VUc0T0dVCkdvK0wrOXFaVTMyWU1rOWpDRUlO
            bjMxUmQvUGY1SlV6VjhyYXc3d3pFNDgKLS0tIFFuNTZCYjlLNHI2VkxhcDhqK1FW
            QlAvU2JRM1pvMWc0NkVtNXlWU3JHKzQKFlS4qriS/hlIuQs6VmDz41fO650ne5hy
            S9g7aDGliLRh+900xkNRqXlcsGmnC+LQ1F8K+Ll2PZjBgnHBV2ygKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T06:38:18Z"
    mac: ENC[AES256_GCM,data:vst0WcE1D/dzzUJjque+lMtea2jfxzlAZZsAyMsWdxmIkt0aKIlLzyUOGbp/Ll6FVjLB1QmJPq1l9Oqxe3Q0jdBMAwkeIwrXSHdbTEiuqgVzCDYMlrYE1f+e7kd1Ici0vGlD8Od/O/htDusJ3697rnSsmOSST2aOlEZuhn0nVLs=,iv:bifKsPJeN7Qn2UnvHVjqhRWU7Q4O6eq07ucB2ML7ag0=,tag:eGoGh5O7DNT4TnIv0sa1dg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
