apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

resources:
  - decypharr-secret.sops.yaml
  - decypharr-release.yaml
  - decypharr-ingressroute.yaml
  - decypharr-pvc.yaml
