apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qnap-media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
  storageClassName: qnap-media-static
  volumeName: qnap-media-pv