apiVersion: v1
kind: Secret
metadata:
    name: hermes-secret
    namespace: hermes
type: Opaque
stringData:
    #ENC[AES256_GCM,data:2OcEZeLmvOGsGPvwWG8uyC+Na5fQKNZPHSICoJHlaMStbnwKSgVGyldBc+b6vvd3E9LcPBYXaU2ya24=,iv:xhmlBVkPEG78+R1BHvaXJYTBF5mCQt4civBtNeko3c8=,tag:pPO7Qdsz0+vRDC/LaiOnyA==,type:comment]
    API_SERVER_KEY: ENC[AES256_GCM,data:a+f8H33elYlaAKjtrvswrQ2fxOyWQKzhymsYHPPC8RbgXevK2+8s11x11jMGowDNC6DcxydnTrwy7fM8+KYUHg==,iv:t3Hf5SCVj7dl2sAZK6117uTCQEDGUYp5wj4orfbPbi0=,tag:Png5UP2JHGUYW2XuKpi2Ig==,type:str]
    #ENC[AES256_GCM,data:5tE70NH1kA7XCOdb8mluDMKyn0L0glJU5MqsVC+Z25wVpaljVI6sYgUNZtqBTYaaTztDBt/lvjexnvl6SDDuvE4=,iv:0J/F7TFJPxmn1AZVUVPSIEvGPI9RBCX9yHd+pMBWINo=,tag:Vf+Xd53tuN16lpjqQbMXAg==,type:comment]
    HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:Jv3jFlA=,iv:LGzDZ1qnjathiYb1WQKxHah2CrO1Z+br7StxVg2qBM8=,tag:ub3Heq9Z3t0vWTAr3VvzRw==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:cs5V9Gh7g+/Ie90CTiORQgq+mN1wAzEdOHZqcA==,iv:8MFdA6SxhC9EIGa4VcFcydDzbWBzkU20ycrQaPMfymQ=,tag:ZuD3Ue3mXSHA7LBojP6h0Q==,type:str]
    #ENC[AES256_GCM,data:7v7oOf38ZDksqs+MrX/HSjuDJHjhPml+NNxIrf60KKeLVQC43jesy1HoKXt4QVuMhDTYCLsLX2oKPIskOqdAbZC9T/4w183SKuc=,iv:HJH2rpkbMYqfRrckI73fkG/BpQVZnXUK4iLM8TPCBdo=,tag:l+74VhJMMd/hud9bd/wTHA==,type:comment]
    #ENC[AES256_GCM,data:OSuFSVxF1+qboJNu/6M4/flebY7dkHc=,iv:6XfZ72x1PvNWwn7WSNPY0qplBHlcPiyzFAksFhre+1Y=,tag:roc6tqmnofjeiJXNkcGBsg==,type:comment]
    #ENC[AES256_GCM,data:WNL2GAun1EQAcJ++4tSNumvY1fEB3A==,iv:OIBJYD8gP6U2Qf52/D/s3G4yERTp/JOkhEl/a6ERaLw=,tag:Bumot6H65JY8lH+QJh/0uw==,type:comment]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:cx4ayVQ67hJTkTg922zrnMYbkNu8LMrw3FyzI8Hr46J4krLJd/Hs6SuXZhlVMg==,iv:V2EG+KUxKzUSzjkvAEa0ePVtmvrmq08D5DzmaWBkoY8=,tag:PnPf5dFfG727QxKl63ZdHQ==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:YaRF5qAgjvx+6p3kefs7QcwFlowI53foD6CCkLf5AzlxirJKMWXPqYXaloN6EfnopGJh6rFFD3tI2hAlA5y4auaTY09rnhmB,iv:jC03L/ehUKtmpGm0DKgRZyyi+ZIJhqbsfd8G9jge+Fw=,tag:adzB4wAFMIAgLqSUH8Ls/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZmhwUWtDMlVsTWZXZFF0
            VG1mU29hdGNFQUJZZFkzTDh6dWZWL2FhQ1Q4Cm9ydGZOU2tFaWRzaDhsTFBIVWxx
            dzBxb2V3bjFGdk5zMVM4N0JORmZxNXcKLS0tIGtsa2JmSnRWcWl2MEJ2SUVYRUl4
            M3A1WFVwZDVKMmN6cGJGOWxnZG1mdFUKU8Hbg0G6uE/Zp7f5ZH6uTK6e6BtX4EpK
            78NwHPYQXn3qa8z7om3qoURbSNbMAfFPjokOj4YHbdL/aGlEqfNBMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T00:12:08Z"
    mac: ENC[AES256_GCM,data:tac+n4sqDVq3fC9kwtX0HNoVR3rMCDzJgsoy9uJeJbGADqZ6+77sEMsks5J9Y/fcjogKaQhP6UVTIIG/3Fh+iU0fh+6cn/0rlP59Mj32IHhgf3WUESazcFAqwU3QuSC2d3G28BHA02xLzIMr3pGj/8etcd8eirbnCrBcshiNCNw=,iv:tDXdAizbT4XeKMhd6bbG5dwfzvVzBzxpQs0AhzLfITY=,tag:MrO1byiM1B2cKNpmuKH1kQ==,type:str]
    version: 3.13.1
