apiVersion: v1
kind: Secret
metadata:
    name: hermes-hass-secret
    namespace: hermes
type: Opaque
stringData:
    HASS_TOKEN: ENC[AES256_GCM,data:JWbJw6tD9MHeZdLce5QtoOAeWcgepcHz2QaRpvw0KeIB5rh9M7SF9Ycd/V5hNl3VRSqTM5FIcutuaT0E2MfDPO1jEm0bfX0AKQERoo+je2I6wmmKdOogdtfaQyQANjEWj4tklpPJXnGt4YZzE2ajDJyim06UQlILLHTGEzxduSsVcHZGEdS5hM+YSZjGIDQm1RYT+4etqPS/dlRzIPDXAr2qN8w4KxgxbAi/a9n9BQsspO0Fmp8K,iv:JMr9vkDsZR5749DtmyrOFRi2YgbcF8V7rngsfzqu32I=,tag:5+9EKHNd04+WXTRJ/BR1JQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdFF0WTBVMzI5T1lCREN1
            NnhIMXN0SFI5U042dENhVGpIOFFnK3JmWENjCjZuMUd1NjdrYjZlZTFQOFlJbm1m
            czVDTW1YQ1I3Q0VRbTlxWTZXcG5mbVUKLS0tIG1xWkpBQk9Ec3huWFNCN01KYXBU
            ZTFFbXhzTHRENXAxSzZhOEpRQWZ3TEEKKSVsew/PrVZ13h7SQEztu6MyjwG1dFK5
            OP80uLJlsY6D6Ngs6Y0anpUUdhQDOYzw6vn/Y0aL2N3DnRVfiMyuTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T07:42:57Z"
    mac: ENC[AES256_GCM,data:MpZq1F/qhwq2SOjiaFkWjRzmdLgtdDxRn37hNQaRFMm3ZxhwbY697BTWlzik4RvCXwdf1D1WDRv96yCwhoCsPKs98lELGfWrk1smyUwooNqM1Sppsnf4xZz1ukt/YrpKgPAJj5T+EYwBCiev0bFzPn/AronDB9zO/w7/6ZUEATw=,iv:2h6WoThxDKPSJsCXBsw6+kOKR0FaF4U9Dc1ySSZdXFs=,tag:yfXR8BEkA3LN3CFql9KxgA==,type:str]
    version: 3.13.1
