apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
    namespace: home-assistant
type: Opaque
stringData:
    #ENC[AES256_GCM,data:5t00GzOkYWSkrx1+rlk6kJwA5VRJqOVlad98Ep58EJz8JLkqkOC4/4DGm1x9zQkZOStHMNvkiW8=,iv:DxYR13+Ywt0lr+pC3OebvMFaLI6z/i/rt9vMTubUVUw=,tag:G4GK4ySctOdnwM2n5dVEVw==,type:comment]
    secrets.yaml: ENC[AES256_GCM,data:avvF7bUIaoUPNsWew26/43RwO7EWITb385q56jcu0ERUGZtgu70l+eh2njw2JrXbXhNmB15h1E2UdcWsYbYrOzlv6i5uiZicerYVirAIldfzncccju07pvYrIGAXggKBAhF1gxHp0smV/1NXMZ18HgIPoSlm6oywnSU1mjVT7rpmv2YQdFmb39xY9OIGKdgM2COyRXAFnMBTjY+HG4/G9S1DFHVN5ghNN5hmsI0rasWEucB9N7biC2VAMZA+PXV4WWEYES+15MvthTMtd44sdv1oxvMcWgkj5Mtc,iv:ME/5MB2FZlX1DH+sv9tTqg+pCzOFqN90ZBAANpoW6qg=,tag:dJQ+yOR4XF2orJ5Zzvk0xg==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWURKT3QrS3lKbHR3YTJv
            RWhOM0M1bHBzaVJJQzZWZmtlSTlQU1NWbzIwCmxNNEo1NDR3NklsNisyM3pMdWd6
            L0p4ZExmR3pQdDZNWldMN1pkZU1neDAKLS0tIGtXQXlvVnJmQW1ma0szS291d0RD
            aWcyUkxSVDFBOG4rZlg5ekl5djVrNHMKY+oaiPdC3Caa93kajU2B5fs7tFkGoXi4
            kutO38LBmfho1VgC11py0VRP3Zz0kfCsS/z7d/65lMZI7V6KqOYwQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T10:20:16Z"
    mac: ENC[AES256_GCM,data:pTcioeuCdLW82t1kscXo7jESQ09slOZ/TtHtmFV6qTDaghZhOg1rBmWFTDcAF1GRum5EOZE+F4z/uvUPu6pmiD3kPQTzOpfOG6JFAPbQpAQJbpwcMqz9X4lgb0j/6gIjx7lwwOlAxzUf7Bd5bu7Qu1MrKSiTEJVkUxUXK3YpUBc=,iv:ER1UGkMZcnRA2H9FfssOUzKaamG027TyI+yNWYhndb0=,tag:DGhD+/MbyDePNesbKoYN9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
