apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scrypted
  namespace: scrypted
spec:
  storageClassName: ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi