apiVersion: v1
kind: Secret
metadata:
    name: ceph-rbd-secret
    namespace: kube-system
stringData:
    #ENC[AES256_GCM,data:EXKkZgpFuzuG6XnEJzkHiusmZpx54v1rpxR588+83tRTH8uunBI3URo2KROdwth6/YzQXk5y5FVDcZ+TLwxyleR+SH7tZ+Q=,iv:cUXSYJ+Jq6RixJ+zslMBGUinYYVriRUxyFrmnHkIIKY=,tag:aw2+cutnfL1s1KKzq4zlfQ==,type:comment]
    #ENC[AES256_GCM,data:n7nz22fHN9+rGa+vodc47e1Y1lqv5M6mZn5ohWHeQ+QRM1CdBNRNhJvJGdlvJVeFKlzslbuQzoIH3IoHq06tus2Sbw==,iv:KxwSvdhtbC0PNhalvSar/GChqa1rYzWh/CxJd06L1ZY=,tag:v/f/yQcoX6HI782Aqr7Bng==,type:comment]
    #ENC[AES256_GCM,data:b4TfAt4V1aRGOcOGELlSc8NqVgei+K0y2hYmqZXl+L8aAA7Sx/eiMmerIMi1JiGU4CXQ85Q=,iv:iwcmDFemVjc+hOXRKCqe229XfTC7q3KtMvDzC+WI/Wc=,tag:0T+Xpv2i/L/r8AfSbahqQg==,type:comment]
    #ENC[AES256_GCM,data:g8xQ+kWqpDzddJpwWcjTJZ5EZtQAzvNbl0XPoOU7MjZNVJ2Ngz0FaijJXA9xbI4=,iv:E484thbgbA2c556xazm3XA7D6oOLBGe5cgfhu3+Ysn0=,tag:JrfANTg2LiakAuvEhrtnBw==,type:comment]
    #ENC[AES256_GCM,data:Ax3OemSAs1RCUhmvfwym3gVin3XvbeLvUGI9ggpcA4UN4Vq+QqWxgEAkuXZ+bsZDDumswOw8Ya8Xyy71m4WJKac9+J/rEC1TMakBUmdw5TiwFI+fU3AN8YKDlhs=,iv:NeAUEhFIY2fr8fZOB0sOYX+Fn5hypaENO0Rrb2xhBnM=,tag:HAfg8l11d1XxqfcyMgH/VA==,type:comment]
    userID: ENC[AES256_GCM,data:b72QLzHklza5RhM=,iv:AQcDYnqQB7zxCkAy9UISV3+9Es3aTk1EXOUw0Y0SFPc=,tag:zMN03lEWHurlWUSyUOSJKw==,type:str]
    userKey: ENC[AES256_GCM,data:U3KFlDgHB76IJIEFM03qKO1xmQl8dnBYGJ3zKR0ERVBJRDqE2XcwRw==,iv:yb04BwdymBMYjWUgNnRcxKJFCVNiLpCVxsPJruUHz/U=,tag:99JaXXFWi97MrSyhGfmoHg==,type:str]
type: kubernetes.io/rbd
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYUQ3WG9xcHIreXJYRm96
            RUNGdWtFbWpaVUEyUjdsMWxuV1JIMGhJTGhVCmkyWUZMbE5jenNGdGNiVUIvWmd0
            TXMwNmVnSHhObXg4aWpYeU1YWTZLRzAKLS0tIDVXNjF3dytxaENzeExHUUllUFQ0
            clZDUjJtOHFqeEs1bUQvZmRKYXFadUUKuO3amkQ8sB/RDZ3f2rHxWDjgH4FAau7J
            DKXYPKTrals2ITzloUqWQvtvAO7Ox1UuJ7LAIWPoetcz/xw3EzJBpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T22:45:19Z"
    mac: ENC[AES256_GCM,data:qlFaSiWFfPoc/9PJGavyTdq6SsUJByak+A2/GwuifDZcUBPDIDvLAu7K0CZRmtTgt2sl5Z2CJsQSnXPfBWkMXPH+4UKapj4cjZmZLS3V4u8hJ32kyVuhBltm40jO5/x4l9dUrXPPWDe9kdZQPqw7Ezx6qgT4iHEE3XUzuIRHI5U=,iv:cYK4nZgo3fX/rl0IyUN0ygD4J10xF+953IJNKcHxXu4=,tag:FHJSbO9o/POdg3einWmpiQ==,type:str]
    version: 3.13.1
