apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kitchenowl-data
  namespace: kitchenowl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 5Gi