apiVersion: v1
kind: Secret
metadata:
    name: kitchenowl-secret
stringData:
    OIDC_ISSUER: ENC[AES256_GCM,data:geaw5HdB7mePXbBfAfBDLkiURxqNzR0fMWDlS+vUjWjShQ5iCyvVF5kgRUuhevIJa4F0G3qv5k/BjmGs,iv:axsDlVO0rZlqnPUhtr2LdZwbE/VORSd/vpVuFdNHeQc=,tag:3ER6fcdUYbkbuX7IsyoqOg==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:Odn/bRf3Ett/lwfB/iJpgFS7b4jYhMTZyaIVTkW+WhIYyeyOx2f4wQ==,iv:U6s+V5elCuccaK45lyH1WdSXXWkzFghOX9PNLzeeBs0=,tag:djNPwhDLZDlXrbyME22lUQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:MhpbkKjf9y4z0B5fwwXkm6L8PoN1d8xJbhQq3I2Ja62B2cZVzk/01NFutsrxSQsVRomTeASES3ePoXmp+LEaICxxhfCO/RtHxwxVs9MpYWZmJfcoXxHlgysav0fLutkxDI79cpgZk6TCNf4FDPDBtMfnqe5g9twjW3vTmI5x0jc=,iv:MMtYnr0NrszN7iTQM6w8n3W2sFS8+9MNuoBe+9/3V8c=,tag:FuEE6cKEDAiAdM3QtHDNKw==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VjVjZ1Y2cFpCSkkxd0dk
            SWhqTkRzeXY0U2huaENyNWFQUTIrMkJRQ0ZRCmo0TUgwcUQzQ0ZRdUljOVBWL0lu
            dkwvbGtiQUJzaHY3aE1Hdlk1d0tJK3MKLS0tIHo2bU1iNkxsaFptWGpNaEhocUo5
            Wi81VjVrOENGbHFpL1l2a01LSnZZd1kK1+qc+lHuyVsBdZq+tC9ZVz5HNnr4Pqy+
            ByM4XG3NsVH+tEG1Txfujik0Urwh3JksZGuUymmgd3diAy5upNb3DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T04:24:46Z"
    mac: ENC[AES256_GCM,data:iLIh3uzUcLVNqXCmZZ/kS/D0e0o/DtWZ5s388DDR6i7fpu6LxNoJDs7YNNBaRvaSpWw3P0tcBtFCqi1ue4hc2U3qtwGPW2p3f5hwoxlqtsLPQ+ZgXWRm4+F50DEiklWEKoITkmINqsWLWp6tReDrqjDPKZMAuN13eTddb3mbn9g=,iv:dgDuE77Qgdv8hWekQW0q3zspATA1guolQnDkB1gw378=,tag:av2jsdFvRL0vjLQ2ZPGFaA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
