apiVersion: v1
kind: Secret
metadata:
    name: paperless-oidc
    namespace: paperless-ngx
type: Opaque
stringData:
    #ENC[AES256_GCM,data:/0JJumdOoU6Rhvn2JJAtpt1kYQSXuq5lFSM5+KuNlygNdyph2+/rGtxOGholkK4ahsQrCbWoeX8=,iv:v7U8baQYTBN/9ozU2QQqjwfRMWRjuIK0Jf2ERW0anro=,tag:mGMNAzSQKhCIr1zIAuwWCg==,type:comment]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:uXA4YIE3jc8Q,iv:WmVpzB2AfAT7HOwyrPISaUaOkVMvufxn1q7IUbo1KL0=,tag:u0p0vww2oVJfmR1DcGYcqw==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:U1a125TFxlTJm9mx,iv:qZSRMW2yAr3YemUUX8sezsLq7jfOIGxLKp5K2gAwadk=,tag:2HH11tUKoaHaavllxBIsrQ==,type:str]
    PAPERLESS_ADMIN_MAIL: ENC[AES256_GCM,data:brgS4zYJtSP42zKzNjiq5pzhmQ==,iv:k23rEhrhx2mWIYhCPVvYFyNxt5RJVdCihOXkWTDpMJE=,tag:8u/jS9nbItQ7O//7QMMq+w==,type:str]
    #ENC[AES256_GCM,data:d3T/aBYvTzEO0TxGU8nc5tQmf/oz2+IuQwN60/Pyv5wqZa4tORi44SM/apZx5k3wxIjv+WK7q5cKflh7hg==,iv:izs/GzcaR+rkmcH9K1kSewgAn1mvgXqNnmUs7ixsgDE=,tag:ML89IL2+8/5Z7DdyxT2WXQ==,type:comment]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:xgnscAlJsnKjsPQRc/ZiFYYybmnr2/fRsoJ1Fh5c8ZBvVw/gGgOCb3dR/iGHY6vhu0mBP66B+oUSrdhzCvUHTvhe2yALw//im4EW/i119HnNXWbsXfWWgLk7GEm6brr9/FgxhKixwhgZbweqiprAE/qyMwwq//iiyXuRvhg4NIEU23WZi8jifDyvEXo5iCExEYF10TReRUkc2REGeguaQlgjeDoAjInBFmK+qKq9HgOJntZ/kPGffbKcFGec7SUfBNITdzGwKpl9HkeT2AXQpTeCryZBklSYgSXdbML1rB+ow4hzj4/fbhg7wNpzQd17K8ITIEbTMnOJmg+udCKSzgXUfG9gnH6Ij0SIuKkSRIeuuE8A7u+vDUPwLbtieWNZRVcCAxrBeWet8gJzOmUGW/xsjy++qwNNeUbZYF5+/9zSITD9Z+bUtA+yO9NqthYPD+DdbiZPbbaJ4cGg3cSIih5rOaLquDLGkvlw2f7/kFA7v8VwwPo7CCRZwHOtk+CJjSkckNRzfas5/kRTXiwgNhh6fpSY6V5AQKp7hkFaTxUIN4p0gJqg4/YliMDItkOCgZ2EihxG9Aza4rf4QDVtGEIQhtHPhvcMmTQ1oi5iJgdQynZm338q7x7Kj5der2ODrHZ1oyCplipEhzZFGVnh1+Etoq9hqJLiYPyt2hWe2M0k4U/N9NxPKqFggnOTJ9KTEUKopM+faXGZRzfUobctVIiU7lYGNqBsKNV2vFycVEV0v+D6osG47xjZkSlJEcZIFh6awMvVPzzDH2lzq6ln/qBAMFx+t8/M8Q==,iv:uRnC8LOtL7OXn0gXb3KtGa5jEkfaH4qFIKLQAGfjeZI=,tag:1E2PN5w6dc5B7XQuTPnVZg==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YzZFNGJISXJHOGxRVk1y
            MFBQS1FBekVCV0dPeWJma0R4czhXN2dGVlVZCjZ4WDZiT0RhWEoybmptWGdMc0tG
            TnVmdHQxTVdTbVVWOCsrRE4rRTNBZ1EKLS0tIE9XQWhzeEp3bjE4cDE1T3NVeDdq
            ZkRBWTNoTkhhUHVJZUNrL2RUaEFmcTAKzLpLBIcq4qjMzJAfLh6XavxfFpjDcpzh
            aSDNkaZIc4uwq+UgqIg7WjQbvKdG0a1s+elqQ2FV0De18CE9bcLr5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T02:49:26Z"
    mac: ENC[AES256_GCM,data:0kXBNq5v2EYcRyOs83jbA5FwtAIWktAUy4LZbUF5I41IsuiVeE5CO/YR3layLsffirFScL0zg111Xt0xEiXuA9gN1vd8j3XUDBFr+utW2N4GKYyOGbujaxpxAwzd2WcgxGWE+hYjYzkr1ERBNiB5FJfDIOyozqIep+IkTU7gCUY=,iv:LPOAHntvJO8m3K9GtPl1Jx5Uahgd+cn0eAgkzw+2H4k=,tag:qf/qEpqd/swVdWeKN5XPCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
