apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: obsidian
resources:
  - obsidian-namespace.yaml
  - obsidian-pvc.yaml
  - obsidian-release.yaml
  - obsidian-ingressroute.yaml
  - obsidian-syncthing-ingressroute.yaml
  - obsidian-syncthing-lb-service.yaml
