apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wg-easy
  namespace: wg-easy
spec:
  storageClassName: ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi