apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lidarr
  namespace: flux-system
spec:
  interval: 1h
  path: ./apps/base/media/lidarr
  targetNamespace: media

  prune: true
  retryInterval: 2m
  timeout: 15m
  wait: false

  decryption:
    provider: sops
    secretRef:
      name: sops-age

  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  components:
    - ../../../../components/volsync-v2
    - ../../../../components/volsync/remote
    - ../../../../components/gatus/internal
    - ../../../../components/gatus/external

  postBuild:
    substitute:
      APP: lidarr
      APP_NAMESPACE: media

      VOLSYNC_STORAGECLASS: ceph-rbd
      VOLSYNC_ACCESSMODES: ReadWriteOnce
      VOLSYNC_SNAPSHOTCLASS: ceph-rbd-snapclass
      CAPACITY: 5Gi

      VOLSYNC_REPO_PATH: media/lidarr

      VOLSYNC_CACHE_STORAGECLASS: ceph-rbd
      VOLSYNC_CACHE_ACCESSMODES: ReadWriteOnce
      VOLSYNC_CACHE_CAPACITY: 1Gi

      SUBDOMAIN: lidarr
      GATUS_DOMAIN: lab.mainertoo.com
      GATUS_PATH: /
      GATUS_PORT: "8686"
      # GATUS_STATUS_INTERNAL: "302"

    substituteFrom:
      - kind: Secret
        name: volsync-garage-base