apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - plex-ingressroute.yaml
  # - plex-config-pvc.yaml
  - plex-release.yaml
  # - qnap-media-pv.yaml
  # - qnap-media-pvc.yaml
  - plex-lb-service.yaml
  # - plex-config-pvc-restore.yaml
  - plex-pvc.yaml
