apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 30m
  releaseName: plex

  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system

  maxHistory: 2

  install:
    createNamespace: false
    remediation:
      retries: 3

  upgrade:
    force: true
    cleanupOnFail: true
    remediation:
      retries: 3

  uninstall:
    keepHistory: false

  values:
    controllers:
      plex:
        strategy: Recreate

        pod:
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
            rclone-mount: "true"

        initContainers:
          fix-config-perms:
            image:
              repository: busybox
              tag: latest
            command:
              - /bin/sh
              - -c
            args:
              - |
                echo "Fixing perms on /config..."
                chown -R 1000:1000 /config || true
                chmod -R 0775 /config || true
                echo "Done."
            securityContext:
              runAsUser: 0
              runAsGroup: 0
              runAsNonRoot: false

        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/plex
              tag: 1.43.2.10687-563d026ea-ls307
              pullPolicy: Always
            env:
              - name: TZ
                value: America/Los_Angeles
              - name: PLEX_ADVERTISE_URL
                value: "https://plex.lab.mainertoo.com"
            securityContext:
              privileged: true
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: 32400
                  periodSeconds: 10
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        supplementalGroups:
          - 991

    service:
      app:
        controller: plex
        type: ClusterIP
        ports:
          http:
            port: 32400

    persistence:
      config:
        existingClaim: plex
        advancedMounts:
          plex:
            app:
              - path: /config
            fix-config-perms:
              - path: /config

      plex-cache:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /config/Library/Application Support/Plex Media Server/Cache

      logs:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /config/Library/Application Support/Plex Media Server/Logs

      rclone:
        type: hostPath
        hostPath: /mnt/zurg/
        globalMounts:
          - path: /mnt/zurg
            readOnly: true

      rclone-decypharr:
        type: hostPath
        hostPath: /mnt/decypharr
        globalMounts:
          - path: /mnt/decypharr
            readOnly: true

      nzbdav-mount:
        type: hostPath
        hostPath: /mnt/nzbdav
        globalMounts:
          - path: /mnt/nzbdav
            readOnly: true

      library:
        existingClaim: shared-media-pvc
        advancedMounts:
          plex:
            app:
              - path: /mnt/library

      qnap-media:
        existingClaim: qnap-media-pvc
        advancedMounts:
          plex:
            app:
              - path: /data/qnas

      symlinks:
        existingClaim: symlinks-cephfs
        advancedMounts:
          plex:
            app:
              - path: /mnt/symlinks

      transcode:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /transcode

      dri:
        type: hostPath
        hostPath: /dev/dri
        globalMounts:
          - path: /dev/dri