apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi           # adjust if you want; 100–200Gi is comfy for Plex
  storageClassName: cephfs