apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - minecraft-release.yaml
  - minecraft-ingressroute.yaml
  - minecraft-configmap.yaml
  - minecraft-secret.sops.yaml
  - minecraft-bedrock-pvc.yaml
  - minecraft-namespace.yaml