apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stirling-pdf
resources:
  - stirling-pdf-namespace.yaml
  - stirling-pdf-secret.sops.yaml
  - stirling-pdf-release.yaml
  - stirling-pdf-ingressroute.yaml