apiVersion: v1
kind: Secret
metadata:
    name: stirling-pdf-oidc
    namespace: stirling-pdf
type: Opaque
stringData:
    #ENC[AES256_GCM,data:kmATs2Sj6WWxPLsBCH2p864d6kst+x0F1lFtwNEv3UgjW4E=,iv:oaHYa9xjO0gXNel+ZDNrDJ5aZcSr75OgEu26gzIN0Wo=,tag:2gElIYszzVrOVL59I80nwA==,type:comment]
    issuer: ENC[AES256_GCM,data:tgT44CpI5C2OSbJQSnqggiwl13ctqIcsXpSrbxMlljYMKOQVU0urEAwe3K6DSK5Tm3f2OIqx7PgMGF9+BlD1,iv:h88Z/G0+PCnXQhA7s6KbU3XnQCKws/+ovAJCCFwt9ic=,tag:N2W04pI0sN8pkJ3dI5kA/A==,type:str]
    clientId: ENC[AES256_GCM,data:YLwRevu2FduNGurdOL7QVgwlxwz19SCO9ndkblEflzfRlPd4J4YbnQ==,iv:62ufxp478BZLs82UJq7x/9UZyHfI4EkDBuMFocMRhdQ=,tag:KSoYJlpyrxSo9JiaySTckQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:o7Q9dWhPJ0q+g0aFiLurBtf5AfWO6SmxcgHSWrufzEUq0WpzwFpFrMPH3ReryobHnwEbpN3N/GjE9VGHc0U/Rv6plLgAk0FT0/Z30A3HdcWL8Wd2coqqNys4jM4Ubk7MsssjdUFPXOHRBJM2OSpJ2IQp07wb3cdxjRrvXY5C4B4=,iv:LyIMVCQgLsvMNdRTyDyFHaw4fAclihjcT9YcWIefhrI=,tag:n5uPCuH748SiUdZuSp7gBw==,type:str]
    #ENC[AES256_GCM,data:1i91ELRmKfL0P1Ai+VqRHw==,iv:yW9H3CoywjlvudsEwIChWI9i6umsUmqbAwMZzW4GRQA=,tag:XivEEYeE0/5Ckc/ThWYsNQ==,type:comment]
    #ENC[AES256_GCM,data:m8vjc59+NX3mFu+ydhl96KFp8GEzu3JNhv0bgLyqcUrggeLyeJH5vQMcQlK/gcDR,iv:ItRVny60OTDvv1s0aopWBl8p6nZbtkbZDpa8wonaVvs=,tag:pp/1L9t6nsXmfiBBTG3/CQ==,type:comment]
    useAsUsername: ENC[AES256_GCM,data:1xLcB+g=,iv:p63q/96IyZ515j/G1ubqjn981nutA4u+akAJUnsyQOQ=,tag:vcMPkS7+amssJ2eiYMJfDQ==,type:str]
    #ENC[AES256_GCM,data:MRFVJ+KYtDd/2OjKO4HspyvfvLjZM1pm7BbwlQ6mUs0Cg1J6dwtBd91UaaJa+AFI5gaWwd1zi6ce2+MPl6muRtHN6xs=,iv:Zy9IyLrih9ADEWvZuPQYCs2UIXcYoKnPZH9+PvZHUzA=,tag:qVbsIXeCd2noTprkFQAZmQ==,type:comment]
    loginMethod: ENC[AES256_GCM,data:lqB5Doq1,iv:vLphmthtFU1VMSjzdrVNmj9bAFkyY3+hEf+3rnv3C04=,tag:vWx5lbQgwRIxtMC05GoqZw==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNFYydjh2NHVYbWhGVUY3
            Qk50YWc3NHJMYVNhWEtXZ3o3SmNWdWVNczNnCk41VFZmUkVGdXhjMWkzZXdQR1px
            ZGwxU2Izd1lwMHlpaHV4TzhxMThIYTgKLS0tIGtpTTdpL3ROSWpQWlQwejc3SG81
            V0U4aUJlNWhBRmtYWVVKOVFtZ2pjNmcKJi06/ioGw5qJdf/mHD0m8ugjxaAA2h28
            s4Im3OhFHecnLaiozMYa0BQJyJ9Uxo1c7OLE+MzufEMB5Kk6PnzXeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T01:22:38Z"
    mac: ENC[AES256_GCM,data:ZEKLemtywx8r9dDuTZeUqiIPoD2kwwi1XGl3muG8tOy9Lf99TN5cRjeAGiGLxMb7+LEK8Vyg81MQs0HTncvBUUcn2N73kkiupeqSmqTLC45spMgPb8fQJ6kWY8dcLVeLBx/5+wv4dwVUmUHwQOzId34GDQc6CmaO6Qoo60usVUA=,iv:kL0Um9eqnreTL3c8QZmPfd6yqk/SMZNjwleTR5hLgKQ=,tag:Wtv8CZqd8an3SBAzJOkfVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
