apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: ceph-rbd-snapclass
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: rbd.csi.ceph.com
deletionPolicy: Delete
parameters:
  clusterID: 2b142655-7791-4f14-8934-0ea16121b652
  pool: k3s-rbd

  # Snapshotter auth (must be set on SnapshotClass)
  csi.storage.k8s.io/snapshotter-secret-name: ceph-rbd-secret
  csi.storage.k8s.io/snapshotter-secret-namespace: kube-system