apiVersion: v1
kind: Secret
metadata:
    name: unpackerr-secret
    namespace: media
type: Opaque
stringData:
    #ENC[AES256_GCM,data:fx8HqGnoXA==,iv:5H7yd0EjSU9iXRJuBFWB1dqS4l/1e6OKXtsJ+pDf9AI=,tag:OTxgo1W/QnH4Uhblhm/y5g==,type:comment]
    UN_SONARR_0_URL: ENC[AES256_GCM,data:G9wJuuA6+W5hPZXxbl3SbAPt,iv:e1/Ax39rL5Fp4T8yTrFuGpYlOnTWINPGU+WGgB8c92Y=,tag:7waeVnD6dCWIxidgdWUYxg==,type:str]
    UN_SONARR_0_API_KEY: ENC[AES256_GCM,data:l/FA4LZViPoMxT0nv1A+Yhsime5rLnlgKhV6Of95pkA=,iv:VR/vVYt9c2SY+duGccP/MHb8M1I0EYAdowlEr5uqkQk=,tag:kRSwQvpJQgXOq6zqj1ulag==,type:str]
    #ENC[AES256_GCM,data:qYsS1ZOiiXpTSw==,iv:a6cto97wRR85eYLH/5QIBsd62vMz4bMvYHeEMXtDH/U=,tag:4gvJZCNivjfjZ36h71bj9w==,type:comment]
    UN_SONARR_1_URL: ENC[AES256_GCM,data:WDnzj62i1JTpErpQKkvREfdT+kA=,iv:OvSvbM0XV3eVg9LMFUXvV+7Aadn5o+40xbHIZxV7qmQ=,tag:Txh1mhbOrMHjyT9nuEaa6Q==,type:str]
    UN_SONARR_1_API_KEY: ENC[AES256_GCM,data:bmQ6prFIAwCa7OHYj+l7gOpbHCqiiBFzIxNlq1MkOpM=,iv:CCBIThvEi6XpMJsN9LPWTfVxZd/f7bqhmu76lrE0nNE=,tag:xvzOUws3c0bqCZcv8DFnww==,type:str]
    #ENC[AES256_GCM,data:t3TAXpF7ug==,iv:OaG6/2fjxxUQ2RgXGR01EXXlukyYKDHMXRweyPYvWsA=,tag:jBRPZtxOvnc82XSuFOujDg==,type:comment]
    UN_RADARR_0_URL: ENC[AES256_GCM,data:kC2THfnkd5Hoh5IpV5W4DaX2,iv:dz0ZUbNDq4Fzw/lzdDKF83r3+CR1n2sOaWePCIoV+Fw=,tag:1rHULhx6QH4UCwOd37tZuw==,type:str]
    UN_RADARR_0_API_KEY: ENC[AES256_GCM,data:VYXtbg55aVCIBJrJMzQrPMX2Q/I8K9PM20U5t5bUzgQ=,iv:V90BqkN7kiZPs7Fcs7vCEElmUWbr02NJLiFoQROZJBY=,tag:2/28+smLRTrsBybyGd4zzw==,type:str]
    #ENC[AES256_GCM,data:5HHGULZ9puIw3Q==,iv:VyOwj+V2c7TcuGUI8iY9eYyH57JrQE5aIoC4QT63+m8=,tag:ebDAo2QR3AK5VWJJZ1S4Ng==,type:comment]
    UN_RADARR_1_URL: ENC[AES256_GCM,data:rR3Zn20kTu+rL76PUijUrxhFKiE=,iv:KVthzpG286ZQooYyABlJZI99nsLJAwhsWa55uEJ6IxA=,tag:y70c8emn1sAFhPA0NwNyNA==,type:str]
    UN_RADARR_1_API_KEY: ENC[AES256_GCM,data:Vrhq0XN203NzT+HhuY1uHxLoX07omKkevQGL6dlAAUM=,iv:jPhN9679DtXoXCNTgg779BEpo+gKyMmRG8DoAcSA/3Y=,tag:Ugd+08ws3u3Jd6UndvYPcQ==,type:str]
    #ENC[AES256_GCM,data:q9mO/YhY2k8=,iv:h/ECc4D4xE+FIh90OwrJSMg7odNDRBA6LAdnCO3A+7E=,tag:XnhTmv2jpu79Q6pxPwaz6A==,type:comment]
    UN_READARR_0_URL: ENC[AES256_GCM,data:uEJAMo7tihXNHiQe6da5DTY7gQ==,iv:X6NWQpU4xIUzNW2Ymq0GH7AWbkcKPe8OpXHv4CCKq+I=,tag:8Yre0DdmBZvIoC4HcAdplQ==,type:str]
    UN_READARR_0_API_KEY: ENC[AES256_GCM,data:7QGzzZkwwW1iKDHOnO4x3CvmhotSkU//nh2X2Z39fQo=,iv:GCiDFS6A1uyJu2FJQJT7Tg0uvjvB3tNcdfnrNo7zj7c=,tag:cLgPHtKqF2Srn4yOkfT0+Q==,type:str]
    #ENC[AES256_GCM,data:QIjbuXuzPQ==,iv:x+Mhh3QbDW1+YFgJTlbVrxN4JYYIpXHcvMnVUOTw990=,tag:RtKjIQ0gcz7yGyXIuLcVOg==,type:comment]
    UN_LIDARR_0_URL: ENC[AES256_GCM,data:NJo2oAx6QhPklEl6sOKULvqd,iv:nvNfpg/Aup+OnUcDjFmQFdaqX7110JxXvHvI4D+y0d8=,tag:sG7Ec6NX3QyLAYVqjTt4Yw==,type:str]
    UN_LIDARR_0_API_KEY: ENC[AES256_GCM,data:Cj1D63YBc8LEeLPmKSK7b0YBXF9Owzw/B41ZNqWXSsk=,iv:2bwt/lb3J3qzzLbvxRDO7wuf3UCv1KLDQecGmt3fs9A=,tag:mCh8i55IO8kKZ3vyMn9f7g==,type:str]
    #ENC[AES256_GCM,data:Yn0hH+L+CLrghMVwVvT8zVWaoS+CVlfWbLnO8MY03U/g3WGi+wkcBOWxUVfU46PXeOZinupiFDV3qZiqTm78BdwehJJH1C+VfPu5DQ==,iv:cLsWjAkSntzhu1HDuVkNxsHM/kkZ6eoTxpLyiRQ7S00=,tag:15xmgbcjBRuz2kT9rJAwkA==,type:comment]
    #ENC[AES256_GCM,data:nPkSsyPCSxt4X94dQJzLXBnkscRZdmRqTCPykNS1mJQyarPepWCXSJGGqVtWETqw1Zq/mrliSJxCTLQ9U1VkhlZhHBoBhflLtLEW77NYU/8fsQ==,iv:sJjTUyXv0kWxTLJc9IvTbkpCOmKT12r7pwxknjSG6ak=,tag:1cfbr8NOm6VL2SfLLqaOjg==,type:comment]
    UN_READARR_1_URL: ENC[AES256_GCM,data:cXVqMKLy1kn333jtJ7w331+SgSE=,iv:oN/wf005xgx3TOVXlO6OxHPOevLdZem211XhfVNJgbM=,tag:J77hKmmGDl7f1fw0/sUJPA==,type:str]
    UN_READARR_1_API_KEY: ENC[AES256_GCM,data:mQ4xKK3JKeNL/n/aHXNC+b6yjn6odR1eBtxSUXmD7G8=,iv:QY7Ucq2LBcI+XQ3DkRUw1I09ZxQ9JrIO+gjf4th9At8=,tag:ho2mz3lF4FRVwgjP3k0O8Q==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMczFOMlE3elFLOFpNNWlH
            SVd5TzNpcHFOOEg1eFpNRjlHVi9VY1ZSRTFZCk54VjZsUlpEUmFjWHBrc0ZsbXNq
            ZjdKOXFpTzhpS2QyT0kxYUZHVi9LK1UKLS0tIHRkdkFmU0ZHbHRVb3V6Vm9seXRG
            NURrczF4RzlpbkN6dHVZUEpJaFlpSU0KuPB+cKbehqyAbha+lBUbKL4qmWfWe7pM
            eeRVYcOoYuBQvc83IoLvMl71KN+8eDThXgOO/lhK/5nfRoAs1wg+TA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T05:51:58Z"
    mac: ENC[AES256_GCM,data:6f1dRACGjVc+o8QPh5bwnjmYRzLHoUTLNVFBf/zyPDCRuqJZxq65DKw3+8cKxky0HhhudrAaSI7Rl5ZDKJjVQ9+kiU9IayoGA3Eb4NVT4TKsS+rXNUA2GG2nKRPWgFYv88jmyW5wkU0AVjTNPlM2GADmtZCyHa4HUCwer7lp7aE=,iv:/+jRGDG+lYrSjRxbW9Z2GfFZrRlFzAdwm/hgsl/XtYE=,tag:U63tc+wfTxlGmPuGjxUFyg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
