apiVersion: v1
kind: Secret
metadata:
    name: calibre-secret
    namespace: media
type: Opaque
stringData:
    #ENC[AES256_GCM,data:IT2XRXyp5zyav8jLPoU2sZZER3A/PNPBhypqXXWLCzqcMw2512MiMnYMzG/GVpmPXxZDrWbrPGxO,iv:uln9JMOeiG44/e99NK8MrIyLYkj7T9yQCFT99/wwuz4=,tag:fV0oA+VNGpTyECGyhF9F8w==,type:comment]
    PASSWORD: ""
    #ENC[AES256_GCM,data:PKPeCbha/RGjdbHUtdVIctXNSCeMyzya2PD51rlvT6EsyTBx3lALX72l0NqDqYLLo8uzT2/jTChF,iv:u0IfFi7SPUPQaUje98UQixQpzusgt8I6gW4AFjnc6jQ=,tag:sXIUedYQ9vdNo2SDTFlDOg==,type:comment]
    CLI_ARGS: ""
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYjlFby9ZaWxCTDVtTjJ2
            Y1lZYVJBR05ISnYzdlBxUFF2aG1jR1JLYVZ3CnhXbllBanN0KzM2cGptdGYyUDVj
            aGttM0praFJVOWZNakJmMTlBeWptVVUKLS0tIE90Nk5aRnNod1ozS0ZIRDQ5RmRz
            SGVwWnBtUHpMOFpFVnhadGNIQVh5NzQKROXgJHIPWmnw21QAhpkyPZqxHVTtFyUn
            LEePByM3vq4/I5OD//p+8A9/ASiksGE4GKz3hdES2payAditEPcD2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T16:42:38Z"
    mac: ENC[AES256_GCM,data:VAu+YEZ4A1/OPKaiz7nwT4grKffEGVgnvsBcTsiudtY7z8INKBhumuzZQGRNamAuDTd1jDKZZeFxCEJT/cH3u0RFQZD/n4C8bCeXOuLB8zMnvUqmRWePI8Vi/Pr50aERZIEgNnJV/TqUB3XwhyQAy4GqOy95UpQ6HiECtDlkJSs=,iv:fZF2oX4qyGxGZEl3Mft10f7xx8SNVJaVGgM91eShglc=,tag:36AMLWsAFJEV3vMj9zFRRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
