apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-library-cephfs
  namespace: media
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi