apiVersion: v1
kind: Secret
metadata:
    name: calibre-secret
    namespace: media
type: Opaque
stringData:
    CALIBRE_PASSWORD: ""
    CALIBRE_CLI_ARGS: ""
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYjlFby9ZaWxCTDVtTjJ2
            Y1lZYVJBR05ISnYzdlBxUFF2aG1jR1JLYVZ3CnhXbllBanN0KzM2cGptdGYyUDVj
            aGttM0praFJVOWZNakJmMTlBeWptVVUKLS0tIE90Nk5aRnNod1ozS0ZIRDQ5RmRz
            SGVwWnBtUHpMOFpFVnhadGNIQVh5NzQKROXgJHIPWmnw21QAhpkyPZqxHVTtFyUn
            LEePByM3vq4/I5OD//p+8A9/ASiksGE4GKz3hdES2payAditEPcD2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T01:38:45Z"
    mac: ENC[AES256_GCM,data:dOtrRDFZMd6b4LZer3HDWdj5tNKw+WPCurf9Uvl/huRnYPV+24G+SHS/hitTaytngPncU369BYK/pDo30xGrCSiOD0HjUhI7vGee5bk0l2gHherdEQBZM3JCzoG9E9qs8vhNeQIm/1r4eiEK/cIyyJ+2mi1bRBfAa6dH5L/jS78=,iv:SFkdQuJWtKxMVPHDqfUO05NFXMO5OfPGJblX//gHGwk=,tag:wvKX3ZtIktVNk0eHDI8lJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
