apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre
  namespace: media
spec:
  storageClassName: ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi