apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - calibre-pvc.yaml
  - calibre-library-cephfs-pvc.yaml
  - calibre-secret.sops.yaml
  - calibre-release.yaml
  - calibre-ingressroute.yaml
  - calibre-lb-service.yaml