apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - volsync-helmrepo.yaml
  - volsync-release.yaml
  - volsync-namespace.yaml
  - volsync-servicemonitor.yaml
  - volsync-kopia-maintenance-secret.sops.yaml
  - volsync-kopia-maintenance.yaml
