apiVersion: v1
kind: Secret
metadata:
    name: volsync-kopia-maintenance
    namespace: volsync-system
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:7eb8Y1Vzq/Ekqm0pzvcr+GhaE6tD6VFnYxPVyQN2JuyE6R8u,iv:k6I4uJxWLZI0sSwayXqe2riRSdEY7Ovewf/ypwRjcv4=,tag:+TqkEfPLUINO2V13JE4c0Q==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:6vTuNqLOTFfnUHS1,iv:AFuP0Z7wgcR+3B2jUXd1TMXkZ1VQcgyQx7vfFcsYWjU=,tag:FHqfOyMuoucIgDXVeiAtPQ==,type:str]
    AWS_EC2_METADATA_DISABLED: ENC[AES256_GCM,data:LfSgwjPhX4g=,iv:RrZaVUc4xgsS22FQFD0ZYntX2VhpbJZvzk3JKYSNxy8=,tag:adNrLK2tEYstdv9EbfwI4A==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:XfzFoAKEMOURe+TG,iv:yItBwD1sT/6/2CXl7R9CBeVbMAcZMOKa72Ad0WjwIYI=,tag:LqTmGPunQDCxu8keB+DdRA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:noYOjT7gUN5w06HUqE/s0lQ2Da60nUPuQ4IbTCzW5UCm2WQVJUxqyCmx1EfDaby662Gwd0cGvIqLBl0oFSQOpdyUPctPgS9FpfOMAWQC9Fc9DUMeKcKI8w==,iv:JHY3bDdOYdvdIrL2wTFvg14SF+GDl1a4Obf0rWmW4T4=,tag:bOE1KXyq5KSnjZdaGnQ3Mw==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:AY0HZZYsSpDt7TiuQFwFCpVvi41iBLNSorcckDCWxw6hBxzl13zw9tco7r6VVqgtPiFfkJJulf5qShI1,iv:QlUAeIl7heHNYWj7F4BLRj/pUe0FlETlnwwgvlMKbT0=,tag:YujIs/xZCFtoV/wuI3aa9A==,type:str]
    KOPIA_REPOSITORY: ENC[AES256_GCM,data:KwpROwOL/7q+88MKw6yahRBYotBcUj3oyWS1qAh5w2OpxICHZhWDQ5GerbixKo3LjPh/UjL2xJNHASuP,iv:GDnUQmuw0BxV4kST0myexvQsAzb6k4beOU1i2qtbooQ=,tag:lUS+woCV9OIaYt2L+HT2xA==,type:str]
    KOPIA_S3_BUCKET: ENC[AES256_GCM,data:LED2oNe3v7Fg1syr1G6GSPsbdx8=,iv:pXYhAlIQyJlJD2k0bQ8Fv+0q4A+MnC2I4QbU0eAK8Vw=,tag:y/eoLBB0IKHJ8PdxOCbhrA==,type:str]
    KOPIA_S3_DISABLE_TLS: ENC[AES256_GCM,data:b4voD9WRcHQ=,iv:5gf/mxjFzMU5cPOZSurSirZFEyyjUaxceZrT0Yu63vE=,tag:ZdzW7tPCuvXSXfwg/Kutsw==,type:str]
    KOPIA_S3_ENDPOINT: ENC[AES256_GCM,data:cghS4h1sgZzUPSJFjjmdTYOuRIdQ+X3DqEG8C+qcltI=,iv:BxzIDRFOU+yu4v2ClbShRDuPkelAFVWNMHTuJh7c1Co=,tag:zFf9wpRwOD9+7xW0Srw4pw==,type:str]
sops:
    age:
        - recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QmtBcmg1T005bjBxc2hZ
            OHlWaUsydkRDSkVGQTRXTXhtRWF0L0NobTMwCm5SdnAxQlcxVXF0R0E1enJCbGhu
            Tm1nNE5FQlRRb1YwbUY3OEpLb2hyRzQKLS0tIHU4YVlEaHFBWElGN1RIUTZtRmFF
            bHNqWDl4RTdFaU1PRWRXTmlGTGF5OVEKD9oVcz8xPfi3CFjBPxo1xAgTeOZ83Dwd
            nORvd2qfWGPBPqD9OKSyqLtWR9sLxcLqwOzgM2L6l7vUnnVy4ZPwFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T23:26:27Z"
    mac: ENC[AES256_GCM,data:LRXG0N7HIfW/jk/nrVq/zIlAAL/i/5fVDOIsFaa37JsztFDjll/e6KZJX0640nh7kEGrYMMe/mkPEcxFeEaV0m/rMYae2MQ2qcN2vvfWKxRpiHUa7FbQBlfu4hX6gVCJ3Bn/SDUL4eh2DTVZKTRPj/qEUCX2oF7gcJWGk7rTUU4=,iv:JDDGPxVRSv1WGkGkE3gZJnUIzlqs9OPVZTLEyV83ZTw=,tag:XaltRzgMiAyRSN7jrBlu/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
