apiVersion: v1
kind: Secret
metadata:
  name: cephfs-secret
  namespace: kube-system
stringData:
  # CephFS user and key; e.g.:
  #   ceph auth get-or-create client.k3s-cephfs mon 'allow r' mds 'allow rw' osd 'allow rw pool=cephfs_data'
  adminID: k3s-cephfs
  adminKey: "AQA9If9o7t0vDBAAEXyOvVVpnZ0DjlB39T6PqQ=="
type: kubernetes.io/cephfs
