apiVersion: v1
kind: Secret
metadata:
    name: cephfs-secret
    namespace: ceph-csi
type: Opaque
stringData:
    adminID: ENC[AES256_GCM,data:M8LXzRf9UdHVYQ==,iv:J2+cQrXbBoSExwD9htZIUFHN6f+/bZ9s3ARxbt28+z8=,tag:wTr5nPlO4Mkg0qeG03UecA==,type:str]
    adminKey: ENC[AES256_GCM,data:7vKzyMs2+Z1UMaysfHutvDz11FhIXIWx5whpq7oRBVQZj8sEINemsSUi87v48Us3TqkJz/AGbr9rV7XY,iv:nGe7uI50qM4tBgmmfBsqIKjfwVh8DKJmubc/Ko722zE=,tag:uF5xnH2ggK66+eLPfJFq8g==,type:str]
    userID: ENC[AES256_GCM,data:OQGdCGhf2fMSHw==,iv:311fd1Nq7+JurTwYqOoCWLoXfabworaBZUd2GOK8vxY=,tag:SBrF6zscS7KGrTmPTIu9Hw==,type:str]
    userKey: ENC[AES256_GCM,data:15admegvpgQd5u+neUJL7p+df7m4eANFAkJx4JlOSYsy9dspXU8yrfd69KFj/n4yKMEFB3l5YbREiGLI,iv:7F3jyjZS8a6ajYRe9SKM886z2d2w+dWtAvnLMcwfQmo=,tag:MET/JkHUOyDdf770kOmlDg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTlYvWk1PTndRY3RBaU9j
            ejh0OFZFeGRKNkUzV3dPM0EwV0ZBNklzbkR3Clc3WWwxN2xudTdPWlhyNm1Ha0R0
            WnNwdlJhNnBranphSlJwWTFNdzJzRk0KLS0tIFVSVnY5bG5QNTdqU3NKRm5mSUdR
            KzMxTXpud3dlZzhRWVpycDJXZ09mMk0Ko9QK90OZJPZC5oz6Is3GDZJlcYgKFMbi
            mUuZ29uRhvjNsIcJaytvYQVa/shueMm6Ori/lqeZM5caXFggDul1Yw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1znqy83dnxfsdg88ahwxgt2dmazcj5aandmyg5fxty0nheup0jums6grjvk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T08:55:16Z"
    mac: ENC[AES256_GCM,data:xqW23EpJUjYOyQOClvnneSKHiWmerAIPZcxjbLlo2AzXsj7hVZtW0jo2BoQm60lfMj6XQ187+wkcINW4yqfYHcU7XwZGztIl2PTEusz69wzDznwBn7WR99tHSuBE55fMDujgGooUVkN4Vsbtp0SBPEAEt4rzJDUoiWVU6F5fwn8=,iv:AhQFkFdEp4ybWBsWwYW+kLir46Fp7OxkpkZZHwyZ3HU=,tag:/7cKL7YElH+llbbZFzso1g==,type:str]
    version: 3.11.0
